### PR TITLE
Make flow analysis more conservative in presence of entities that can point to multiple different objects

### LINKED ISSUE #6520: CA1508 false positive
### Analyzer

**Diagnostic ID**: 
CA1508: Avoid dead conditional code
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508

### Analyzer source

`dotnet --version` prints `6.0.406`

_OR_

```
"Microsoft.CodeAnalysis.NetAnalyzers" Version="7.0.0"
```

### Steps To Reproduce

See code snippet at bottom.

### Expected behavior

No error.

### Actual behavior

CA1508 is generated on lines 55, 56, and 57.

## Additional context

```csharp
using System

public class Parser
{
  private static ParsedPredicate CreateRandomPredicate()
  {
    var primitives = new[] {
      PredicateTypePrimitive.Identifier,
      PredicateTypePrimitive.Boolean,
      PredicateTypePrimitive.Integer,
      PredicateTypePrimitive.String,
    };

    var rnd = new Random();
    var p = new ParsedPredicate();
    p.Left.TypePrimitive = primitives[rnd.Next(0, 4)];
    p.Right.TypePrimitive = primitives[rnd.Next(0, 4)];
    return p;
  }

  private static ParsedPredicate ParsePredicate()
  {
    // Parse the predicate expression.
    var predicate = CreateRandomPredicate();

    // The parser returns null for an empty expression.
    if (predicate is null)
    {
      return null;
    }

    // One of the operands must be an identifier, and the
    // other must be a literal value.
    PredicateOperand identifier;
    PredicateOperand literal;

    if (predicate.Left.TypePrimitive == PredicateTypePrimitive.Identifier)
    {
      identifier = predicate.Left;
      literal = predicate.Right;
    }
    else
    {
      identifier = predicate.Right;
      literal = predicate.Left;
    }

    // Verify that the identifier is a valid identifier
    if (identifier.TypePrimitive != PredicateTypePrimitive.Identifier)
    {
      throw new InvalidOperationException();
    }

    // Verify that the other operand is a literal value.
    if (literal.TypePrimitive != PredicateTypePrimitive.Boolean &&
        literal.TypePrimitive != PredicateTypePrimitive.Integer &&
        literal.TypePrimitive != PredicateTypePrimitive.String)
    {
      throw new InvalidOperationException();
    }

    return predicate;
  }
}

public class PredicateOperand
{
  public PredicateTypePrimitive TypePrimitive { get; set; } = PredicateTypePrimitive.String;
}

public enum PredicateTypePrimitive
{
  Boolean = 400,
  Integer = 401,
  Identifier = 402,
  String = 403,
}

public class ParsedPredicate
{
  public PredicateOperand Left { get; } = new ();
  public PredicateOperand Right { get; } = new ();
}
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6520

Now we store an additional optional EntityForInstanceLocation for analysis entities that can point to more than one possible locations across all control flow paths. This is required to distinguis from other entities that can point to the same set of potential locations, but the actual runtime value of the pointed to location may not be the same for both these entities.

### CODE REVIEW

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs [hunk 1]
```diff
@@ -7280,5 +7280,124 @@ private void Method3(IReadOnlyList<int>? items3 = null)
...
+            identifier = predicate.Left;
+            literal = predicate.Right;
+        }
+        else
+        {
+            identifier = predicate.Right;
+            literal = predicate.Left;
+        }
+
+        if (identifier.TypePrimitive != PredicateTypePrimitive.F1)
```
Comment (mavasani) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs:7308]: The core issue here was that we were correctly deducing that `identifer` and `literal` can point to the exact same set of two potential runtime objects stored in `predicate.Left` and `predicate.Right`. However, the value deduction from predicate in this line `identifier.TypePrimitive != PredicateTypePrimitive.F1` shouldn't be applied to `literal.TypePrimitive`, which was the case prior to this fix. Now, for cases where an entity's i. nstance location can point to more than one runtime location, we also store the entity for this instance location, i.e. entity for `identifier` in this case, in the analysis entity created for `identifier.TypePrimitive`. This allows us to avoid applying value deduction for `identifier.TypePrimitive` to `literal.TypePrimitive`.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs [hunk 2]
```diff
@@ -7280,5 +7280,124 @@ private void Method3(IReadOnlyList<int>? items3 = null)
...
+        {
+            return predicate;
+        }
+
+        if (identifier.TypePrimitive == PredicateTypePrimitive.F2)
```
Comment (mavasani) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs:7370]: We are still able to successfully preserve the value deduction for `identifier.TypePrimitive` from the previous if statement after this fix.

**Comment by mavasani** [comment]
@Youssef1313

**Review by Youssef1313 — APPROVED** [review]
Not following that much on the core logic, but I don't see any obvious comments. Given tests are in place, LGTM

Happy to see DFA is being looked into! :tada:
