### PR TITLE
Add resource string analyzer/code fix for DiagnosticDescriptor arguments

### LINKED ISSUE #3525: Ideas for resources (resx) analyzers
Add a new analyzer for roslyn-analyzers that will check for resources keys and values.

## Rules for keys

1. Key should end with `Title`, `Message`, `Description` or `CodeFixTitle`.

## Rules for values

1. If the value is linked to a title or message key, then it shouldn't end with a period '.'.

2. If the value is linked to a description, it should end with a period '.'.

3. Placeholders should be surrounded with single-quotes.

Tagging @mavasani for other ideas.

### PR DESCRIPTION
**Pull request by mavasani**
Closes #3525
Adds a code fix for RS1031, RS1032 and RS1033
Additionally, if the resx file with analyzer resource strings is provided as an additional file to the analyzer, also validates the strings in the resx file.

### CODE REVIEW

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs [hunk 1]
```diff
@@ -323,15 +392,37 @@ public override void Initialize(AnalysisContext context)
...
+            }
         }
 
         private static bool TryGetDescriptorCreateMethodAndArguments(
             IFieldInitializerOperation fieldInitializer,
             INamedTypeSymbol diagnosticDescriptorType,
-            out IMethodSymbol creationMethod,
-            out ImmutableArray<IArgumentOperation> creationArguments)
+            [NotNullWhen(returnValue: true)] out IMethodSymbol? creationMethod,
+            [NotNullWhen(returnValue: true)] out ImmutableArray<IArgumentOperation> creationArguments)
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:425]: Not sure to understand what `NotNullWhen(true)` brings on this parameter.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs [hunk 2]
```diff
@@ -356,93 +447,427 @@ bool IsCreateHelper(IMethodSymbol method)
...
+            DiagnosticDescriptor descriptor,
+            IArgumentOperation argumentOperation,
+            string fixValue,
+            Location fixLocation,
+            Action<Diagnostic> reportDiagnostic)
+        {
+            // Additional location in an additional document does not seem to be preserved
+            // from analyzer to code fix due to a Roslyn bug.
+            // We workaround this bug by passing additional document file path and location span as strings.
+            // TODO: File a Roslyn bug.
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:528]: Open TODO without link.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs [hunk 3]
```diff
@@ -356,93 +447,427 @@ bool IsCreateHelper(IMethodSymbol method)
...
             }
+            else
+            {
+                var span = fixLocation.SourceSpan;
+                var locationInfo = $"{span.Start};{span.Length};{fixLocation.GetLineSpan().Path}";
+                properties = properties.Add(DefineDescriptorArgumentCorrectlyFixAdditionalDocumentLocationInfo, locationInfo);
+            }
+
+            var location = argumentOperation.Syntax.GetLocation();
+            var diagnostic = Diagnostic.Create(descriptor, location, additionalLocations: additionalLocations, properties: properties);
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:544]: Assuming the overload exists.

```suggestion
            var diagnostic = argumentOperation.CreateDiagnostic(descriptor, additionalLocations: additionalLocations, properties: properties);
```

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs [hunk 4]
```diff
@@ -356,93 +447,427 @@ bool IsCreateHelper(IMethodSymbol method)
...
+        {
+            Debug.Assert(diagnostic.Id == DiagnosticIds.DefineDiagnosticTitleCorrectlyRuleId ||
+                diagnostic.Id == DiagnosticIds.DefineDiagnosticMessageCorrectlyRuleId ||
+                diagnostic.Id == DiagnosticIds.DefineDiagnosticDescriptionCorrectlyRuleId);
 
-            if (IsMultiSentences(title) || EndsWithPeriod(title) || ContainsLineReturn(title))
+            if (diagnostic.Properties.TryGetValue(DefineDescriptorArgumentCorrectlyFixAdditionalDocumentLocationInfo, out var locationInfo))
             {
-                operationAnalysisContext.ReportDiagnostic(titleArgument.CreateDiagnostic(DefineDiagnosticTitleCorrectlyRule));
+                var index = locationInfo.IndexOf(';');
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:558]: [question] Maybe this is better for performance but wouldn't it be better to do a split and work with the strings rather than doing a locate, tryparse repeat approach?

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+
+        private static ImmutableDictionary<string, (string value, Location location)> GetOrCreateResourceMap(
+            AnalyzerOptions options,
+            string resourceFileName,
+            PooledResourcesDataValueConcurrentDictionary resourceMap,
+            CancellationToken cancellationToken)
+        {
+            Debug.Assert(HasResxAdditionalFiles(options));
+
+            resourceFileName += ".resx";
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs:41]: Might be worth adding an assertion that the string doesn't already end in `.resx`, don't you think?

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+                        if (indexOfDataElement < 0 ||
+                            !valueElementStr.StartsWith(valueTagPrefix, StringComparison.OrdinalIgnoreCase) ||
+                            !valueElementStr.EndsWith(valueTagSuffix, StringComparison.OrdinalIgnoreCase))
+                        {
+                            continue;
+                        }
+
+                        var indexOfValue = indexOfDataElement +
+                                dataElementStr.IndexOf(valueElementStr, StringComparison.Ordinal) +
+                                valueTagPrefix.Length;
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs:89]:
```suggestion
                            dataElementStr.IndexOf(valueElementStr, StringComparison.Ordinal) +
                            valueTagPrefix.Length;
```

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+                const string valueTagPrefix = @"<value>";
+                const string valueTagSuffix = @"</value>";
+                var builder = ImmutableDictionary.CreateBuilder<string, (string value, Location location)>();
+                var sourceText = file.GetText(cancellationToken);
+                var sourceTextStr = sourceText.ToString();
+                var parsedDocument = XDocument.Parse(sourceTextStr, LoadOptions.PreserveWhitespace);
+                foreach (var dataElement in parsedDocument.Descendants("data"))
+                {
+                    if (dataElement.Attribute("name")?.Value is { } name &&
+                        dataElement.Elements("value").FirstOrDefault() is { } valueElement)
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer_ResourceStringsFormat.cs:75]: [minor] You could revert the condition to reduce nesting.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/DefineDiagnosticDescriptorArgumentsCorrectlyFix.cs [hunk 8]
```diff
@@ -0,0 +1,183 @@
...
+                {
+                    continue;
+                }
+
+                var codeFixTitle = diagnostic.Id switch
+                {
+                    DiagnosticIds.DefineDiagnosticTitleCorrectlyRuleId => CodeAnalysisDiagnosticsResources.DefineDiagnosticTitleCorrectlyTitle,
+                    DiagnosticIds.DefineDiagnosticMessageCorrectlyRuleId => CodeAnalysisDiagnosticsResources.DefineDiagnosticMessageCorrectlyTitle,
+                    DiagnosticIds.DefineDiagnosticDescriptionCorrectlyRuleId => CodeAnalysisDiagnosticsResources.DefineDiagnosticDescriptionCorrectlyTitle,
+                    _ => throw new NotImplementedException()
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/Fixers/DefineDiagnosticDescriptorArgumentsCorrectlyFix.cs:55]: I would probably use `InvalidOperationException` instead and add some explicit message containing the diagnostic ID in case we end up in this "impossible" state.

File: src/Utilities/Compiler/Extensions/IOperationExtensions.cs [hunk 9]
```diff
@@ -764,6 +764,24 @@ public static bool IsSetMethodInvocation(this IPropertyReferenceOperation operat
...
+
+            foreach (var argument in arguments)
+            {
+                if (argument.Parameter.Ordinal == parameterIndex)
+                {
+                    return argument;
+                }
+            }
+
+            throw new NotImplementedException();
```
Comment (Evangelink) [inline src/Utilities/Compiler/Extensions/IOperationExtensions.cs:783]: I would use `InvalidOperationException` to represent invalid state and I would also include the index in the message.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:425]: I thought it ensures the array is not default?

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:528]: Yep, I need to file a Roslyn issue.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 3 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:544]: Yes, thanks. Will change.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 4 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:558]: I am not sure if file names/paths on different OS can allow ';' character. Your approach also seems reasonable.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:528]: https://github.com/dotnet/roslyn/issues/46377

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 3 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:544]: I added new overloads and made this change.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs (hunk 4 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/DiagnosticDescriptorCreationAnalyzer.cs:558]: Done.

**Comment by mavasani** [comment]
@Evangelink Thanks for the great feedback. I have resolved your comments.

**Comment by mavasani** [comment]
Thanks @Evangelink!

**Comment by mavasani** [comment]
Yep, that is correct. I was hoping to get to it in a day or two. If you are ready to get to it earlier, then go for it.
