### PR TITLE
Fix #447, Fix #303: Port CA1711, IdentifiersShouldNotHaveIncorrectSuffix

### LINKED ISSUE #303: Code analysis misdetects IReadOnlyDictionary as collection for CA1710/CA1711
Ported from https://github.com/dotnet/roslyn/issues/4133

We need to ensure that our analyzer implementation for CA1710/CA1711 accounts for IReadOnlyDictionary as a valid dictionary base type.

### LINKED ISSUE #447: Port FxCop rule CA1711: IdentifiersShouldNotHaveIncorrectSuffix
**Title:** Identifiers should not have incorrect suffix

**Description:**

By convention, only the names of types that extend certain base types or that implement certain interfaces, or types that are derived from these types, should end with specific reserved suffixes. Other type names should not use these reserved suffixes.

**Dependency:** None

**Notes:**

See if StyleCop has implemented it

### PR DESCRIPTION
**Pull request by lgolding**
@srivatsn @dotnet/roslyn-analysis @michaelcfanning @nguerrera 

#303: CodeAnalysis misdetects IReadOnlyDictionary

### CODE REVIEW

File: src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,17 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
+
+using Microsoft.CodeAnalysis;
+using Microsoft.CodeAnalysis.CSharp;
+
+namespace Analyzer.Utilities
+{
+    public static class ITypeSymbolExtensions
+    {
+        public static bool IsAssignableTo(this ITypeSymbol fromSymbol, ITypeSymbol toSymbol, Compilation compilation)
```
Comment (mavasani) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: We should **really** request this API to be added to the compiler layer. Ideally, `Conversion` and its public APIs would be exposed at the core layer. There is realistically no language specific code that you are adding here.

Comment (nguerrera) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: +1. There should be no need to write language-specific rules just to check assignability. This should be handled polymorphically by core API.

File: src/Analyzer.Utilities/Core/Extensions/StringExtensions.cs [hunk 2]
```diff
@@ -0,0 +1,58 @@
+﻿// Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
```
Comment (mavasani) [inline src/Analyzer.Utilities/Core/Extensions/StringExtensions.cs]: I am assuming this is just moving the source file under the Core folder, correct?

File: src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs (hunk 1 above)
Comment (mavasani) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: However, this is not to push back on your current effort of adding C# and VB specific utilities. :+1: on that. We can probably move common syntax related helper functions from all C# and VB analyzer project to these assemblies.

File: src/Analyzer.Utilities/Core/Extensions/StringExtensions.cs (hunk 2 above)
Comment (lgolding) [inline src/Analyzer.Utilities/Core/Extensions/StringExtensions.cs]: Yes.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs [hunk 3]
```diff
@@ -17,9 +18,7 @@ public class CSharpDefineAccessorsForAttributeArgumentsAnalyzer : DefineAccessor
     {
         protected override bool IsAssignableTo(ITypeSymbol fromSymbol, ITypeSymbol toSymbol, Compilation compilation)
         {
-            return fromSymbol != null &&
-                toSymbol != null &&
-                ((CSharpCompilation)compilation).ClassifyConversion(fromSymbol, toSymbol).IsImplicit;
+            return fromSymbol.IsAssignableTo(toSymbol, (CSharpCompilation)compilation);
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs]: We can completely avoid this file if `IsAssignableTo` was an interface method, just like the Roslyn implementation [ISemanticFactsService.IsAssignableTo](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/LanguageServices/SemanticsFactsService/ISemanticFactsService.cs,91)
Then a client at language independent layer can invoke this method (see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/GenerateMember/GenerateConstructor/GenerateConstructorHelpers.cs,75) for an example). 

We can probably create our own ISemanticFactsService deriving from [ILanguageService](http://source.roslyn.io/Microsoft.CodeAnalysis.Workspaces/R/cc9ae129c46089c0.html) in the core AnalyzerUtilities project and the CSharp and VB implementations of this interface can MEF export the language service. Feel free to open a separate work item for this refactoring if it is too much trouble right now.

Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs]: I opened #888, "Hide language-dependent code behind an interface".

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 4]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+        internal const string NewSuffix = "New";
+        internal const string PermissionSuffix = "Permission";
+        internal const string StreamSuffix = "Stream";
+        internal const string DelegateSuffix = "Delegate";
+        internal const string EnumSuffix = "Enum";
+        internal const string ImplSuffix = "Impl";
+        internal const string CoreSuffix = "Core";
+
+        // Dictionary from type name suffix to the type the suffix is required to denote.
+        private static readonly Dictionary<string, string> s_suffixToTypeDictionary = new Dictionary<string, string>
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: ImmutableDictionary?

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 5]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+            [DictionarySuffix] = "System.Collections.IDictionary",
+            [EventArgsSuffix] = "System.EventArgs",
+            [ExceptionSuffix] = "System.Exception",
+            [PermissionSuffix] = "System.Security.IPermission",
+            [StreamSuffix] = "System.IO.Stream"
+        };
+
+        // Dictionary from type name suffix to an array containing the only types that are
+        // allowed to have that suffix.
+        private static readonly Dictionary<string, string[]> s_suffixToAllowedTypesDictionary = new Dictionary<string, string[]>
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: ImmutableDictionary?

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 6]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+                    }
+
+                    string name = namedTypeSymbol.Name;
+                    Compilation compilation = context.Compilation;
+
+                    foreach (string suffix in s_suffixToTypeDictionary.Keys)
+                    {
+                        if (IsNotChildButHasSuffix(
+                            namedTypeSymbol,
+                            compilation.GetTypeByMetadataName(s_suffixToTypeDictionary[suffix]),
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: We don't want to invoke `GetTypeByMetadataName` for each symbol. You should create a map upfront in CompilationStartAction, and access it in a nested Symbol action.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 7]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
                                                                              isEnabledByDefault: false,
                                                                              description: s_localizableDescription,
-                                                                             helpLinkUri: null,     // TODO: add MSDN url
+                                                                             helpLinkUri: HelpLinkUri,
                                                                              customTags: WellKnownDiagnosticTags.Telemetry);
 
         public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(TypeNoAlternateRule, MemberNewerVersionRule, TypeNewerVersionRule, MemberWithAlternateRule);
 
+        internal const string AttributeSuffix = "Attribute";
+        internal const string CollectionSuffix = "Collection";
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: FXCop seems to also check for "Stack" and "Queue". Should we do the same?

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 8]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+            analysisContext.RegisterSymbolAction(
+                (SymbolAnalysisContext context) =>
+                {
+                    var methodSymbol = (IMethodSymbol)context.Symbol;
+                    if (methodSymbol.GetResultantVisibility() != SymbolVisibility.Public)
+                    {
+                        return;
+                    }
+
+                    if (methodSymbol.IsOverride)
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: FXCop does a bunch of additional checks in its IsOverride helper method. See [here](http://index/#FxCopSdk/RuleUtilities.cs,597). We seem to be doing only (1) here. You should probably also bail out if `IMethodSymbolExtensions.IsImplementationOfAnyInterfaceMethod` (defined in our AnalyzerUtilities) returns true to match FXCop.

Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: And write tests for the same please :)

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 9]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+                            return;
+                        }
+                    }
+
+                    if (name.HasSuffix(ImplSuffix))
+                    {
+                        context.ReportDiagnostic(
+                            methodSymbol.CreateDiagnostic(MemberWithAlternateRule, ImplSuffix, name, CoreSuffix));
+                    }
+                }, SymbolKind.Method);
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: FXCop fires the rule of all member types, not just methods. We should probably do the same.

The only non-trivial part to that would be extending IMethodSymbolExtensions.IsImplementationOfAnyInterfaceMethod to be an ISymbolExtension.IsImplementationOfAnyInterfaceMember that works for all member kinds. @basoundr also needs the latter functionality in a rule he is implementing, so you both should collaborate and use the same helper.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 4 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Done

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 5 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Done

File: src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs (hunk 1 above)
Comment (heejaechang) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: but this still require explicit link to this dll from csharp specific project. once we have things like this, people would want to just create analyzer in common layer and delegate all language specific logic to this dll. like how code fixer does it. can we use things like MEF to do dependency injection?

Comment (lgolding) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: It's been explained to me that the compiler does not do MEF.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs (hunk 3 above)
Comment (heejaechang) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs]: hey, manish has same opinion as me :). we need to compose MEF catalog though :)

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 6 above)
Comment (heejaechang) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: this should be cached +1

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 10]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+                    {
+                        context.ReportDiagnostic(
+                            namedTypeSymbol.CreateDiagnostic(TypeNewerVersionRule, ExSuffix, name));
+                        return;
+                    }
+
+                    if (name.HasSuffix(NewSuffix))
+                    {
+                        context.ReportDiagnostic(
+                            namedTypeSymbol.CreateDiagnostic(TypeNewerVersionRule, NewSuffix, name));
```
Comment (heejaechang) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: I think there should be cancellation check somewhere

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 11]
```diff
@@ -56,13 +61,182 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+                        if (MethodNameExistsInHierarchy(nameWithoutSuffix, containingType))
+                        {
+                            context.ReportDiagnostic(
+                                methodSymbol.CreateDiagnostic(MemberNewerVersionRule, NewSuffix, name));
+                            return;
+                        }
+                    }
+
+                    if (name.HasSuffix(ImplSuffix))
+                    {
```
Comment (heejaechang) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: there seems no cancellation check as well here.

**Comment by heejaechang** [comment]
:+1:

File: src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs (hunk 1 above)
Comment (heejaechang) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: they don't put we can.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 6 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Done

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 7 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Fixed.

---
In reply to: [57399973](https://github.com/dotnet/roslyn-analyzers/pull/885#discussion_r57399973) [](ancestors = 57399973)

File: src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs (hunk 1 above)
Comment (lgolding) [inline src/Analyzer.Utilities/CSharp/ITypeSymbolExtensions.cs]: This is all moot now. I turned out not to need `IsAssignableTo` after all. I needed a method `DerivesFromOrImplementsAnyConstructionOf` (see INamedTypeSymbolExtensions.cs), which is language-independent.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs (hunk 3 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/CSharp/CSharpDefineAccessorsForAttributeArguments.cs]: Again, moot because I don't need `IsAssignableTo`.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 8 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Done!

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 9 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Wow, I totally missed that. The FxCop method is `public override ProblemCollection Check(Member member)`, and its implementation does not restrict itself to methods. Good catch. Working on this -- which is your last comment -- now.

Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Done!

**Comment by lgolding** [comment]
@dotnet-bot retest Windows Debug please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn-analyzers/job/master/job/windows_debug_prtest/110/
// Retest reason: dotnet/roslyn#925

File: src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs [hunk 12]
```diff
@@ -18,6 +19,53 @@ public static IEnumerable<INamedTypeSymbol> GetBaseTypesAndThis(this INamedTypeS
...
+        /// then this method will return <code>true</code> for <code>List&gt;int></code>
+        /// or any other class that extends <code>IList&gt;></code> or an class that implements it,
+        /// because <code>IList&gt;int></code> is constructed from <code>IList&gt;T></code>.
+        /// </para>
+        /// </example>
+        public static bool DerivesFromOrImplementsAnyConstructionOf(this INamedTypeSymbol type, INamedTypeSymbol parentType, Compilation compilation)
+        {
+            if (!parentType.IsDefinition)
+            {
+                throw new ArgumentException($"The type {nameof(parentType)} is not a definition; it is a constructed type", nameof(parentType));
```
Comment (srivatsn) [inline src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs]: The ArgumentException from StringExtensions is being localized - this should be as well then?

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs [hunk 13]
```diff
@@ -56,13 +62,219 @@ public abstract class IdentifiersShouldNotHaveIncorrectSuffixAnalyzer : Diagnost
...
+        internal const string DelegateSuffix = "Delegate";
+        internal const string EnumSuffix = "Enum";
+        internal const string ImplSuffix = "Impl";
+        internal const string CoreSuffix = "Core";
+        internal const string QueueSuffix = "Queue";
+        internal const string StackSuffix = "Stack";
+
+        // Dictionary that maps from a type name suffix to the set of base types from which
+        // a type with that suffix is permitted to derive.
+        private static readonly ImmutableDictionary<string, ImmutableArray<string>> s_suffixToBaseTypeNamesDictionary = ImmutableDictionary.CreateRange(
```
Comment (srivatsn) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: Are these dictionaries not shareable with the rule that @basoundr wrote IdentifiersShouldHaveCorrectSuffix?

**Comment by srivatsn** [comment]
:+1:

File: src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs (hunk 12 above)
Comment (lgolding) [inline src/Analyzer.Utilities/Extensions/INamedTypeSymbolExtensions.cs]: Per discussion: We don't localize exception strings in Roslyn, so un-localizing the one in `StringExtensions`.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs (hunk 13 above)
Comment (lgolding) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: They're not quite the same:

* `DataSet`/`DataTable`: In CA1710, FxCop correctly requires the name of a `DataSet`-derived class to end in `DataSet`, but in CA1711, FxCop incorrectly does not complain if a non-`DataSet`-derived class does end in `DataSet`. So these appear in his dictionary but not in mind.

* Balaji's dictionary has the additional information of whether it's ok for a the name of a variable of each type to end in "Collection" instead of the more specific type. Mine doesn't have/need that information.

This could be DRY'd out with not too much work, but I'd rather not do it now.

Comment (srivatsn) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/IdentifiersShouldNotHaveIncorrectSuffix.cs]: I see. Ok.
