### PR TITLE
Fix RS1024: Do not report on overloads not comparing symbols

### LINKED ISSUE #4413: False positive for RS1024 (Compare symbols correctly) when not comparing symbols
It seems that in some cases, when a method has an overload that takes an `IEqualityComparer<T>`, and one of the generic arguments to that method is `ISymbol` or a type that derives from `ISymbol`, the analyzer assumes that the symbols are being compared. That is not necessarily true.

### Steps To Reproduce

Consider this method:

```cs
ILookup<string, IFieldSymbol> GetNames(IFieldSymbol[] fields) => fields.ToLookup(f => f.Name);
```

### Expected behavior

No symbols are being compared, so no diagnostic is reported.

Note that the method has an overload taking a `IEqualityComparer<string>`, it seems this may confuse the analyzer.

### Actual behavior

The following diagnostic is reported:

    warning RS1024: Compare symbols correctly

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #4413

### CODE REVIEW

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 1]
```diff
@@ -182,22 +184,28 @@ private static void HandleBinaryOperator(in OperationAnalysisContext context, IN
...
                 if (method is null)
                 {
                     return false;
                 }
                 else if (!method.TypeArguments.IsEmpty)
                 {
-                    return IsSymbolType(method.TypeArguments[0], symbolType);
+                    var destinationTypeIndex = method.TypeParameters
+                        .Select((type, index) => type.Name == "TKey" ? index : -1)
+                        .FirstOrDefault(x => x >= 0);
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:197]: /!\ This is a bit hacky. /!\ 

I am not sure whether we can safely rely on a generic type parameter name.

As far as I can tell, the non-hacky solution forces us to resolves all overloads, and map them with the index we should look at.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 2]
```diff
@@ -168,9 +169,10 @@ private static void HandleBinaryOperator(in OperationAnalysisContext context, IN
                 default:
                     if (equalityComparerMethods.TryGetValue(method.Name, out var possibleMethodTypes))
                     {
+                        var xx = method.GetOverloads();
```
Comment (mavasani) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:172]:
```suggestion
```

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:197]: I'll let @ryzngard review/approve this change.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 3]
```diff
@@ -170,7 +171,7 @@ private static void HandleBinaryOperator(in OperationAnalysisContext context, IN
                     {
                         if (symbolEqualityComparerType != null &&
```
Comment (KrisVandermotten) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:172]: Suggestion: collapse the two `if` statements, and move the `symbolEqualityComparerType != null` check before the `TryGetValue` call.

Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:172]: I'd rather do the change in a separate PR as it's not really related to this fix.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs (hunk 1 above)
Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Ping @ryzngard

Comment (ryzngard) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Looking, sorry for delay

Comment (ryzngard) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Agree this does seem hacky, but maybe no more hacky than depending on ordering. At the end of the day we're at least working on a known set of functions that we don't expect to change drastically, so if it works for the known set maybe it's good enough.

I was looking at the test you wrote without the change, and a surprising piece for me: the type arguments are not in the order I would expect. 

Method display is showing `ILookup<string, IFieldSymbol>` but type arguments are `{ IFieldSymbol, string }`. Going to try and find documentation to see if that's expected.

Comment (ryzngard) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Oh nm, this makes sense. Just got slightly confused with how the information was display. `ToLookup<IFieldSymbol, string>` is the method here so the first type argument is correct. Maybe for things like `ToLookup`, `ToDictionary`, and `GroupBy` we should be looking at the return type and it's typearguments instead of the method signature arguments

Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: I can but this will add some complexity to the current solution. Let me know what's your preference.

Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Tagging @ryzngard for last question

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 4]
```diff
@@ -7,6 +7,7 @@
 using Microsoft.CodeAnalysis;
 using Microsoft.CodeAnalysis.Diagnostics;
 using Microsoft.CodeAnalysis.Operations;
+using System.Diagnostics;
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:10]: nit: Move before `using Analyzer.Utilities`.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs (hunk 1 above)
Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Ping @ryzngard

Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: Ping @ryzngard

Comment (ryzngard) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:196]: This looks fine for now

**Review by ryzngard — APPROVED** [review]
