### PR TITLE
Fix nullability for SymbolNamesWithValueOption

### LINKED ISSUE #4350: Remove the pragma suppression added to 'SymbolNamesWithValueOption'
Remove the pragma suppression added to `SymbolNamesWithValueOption` to unblock https://github.com/dotnet/roslyn-analyzers/pull/4347

### PR DESCRIPTION
**Pull request by sharwell**
* Support global options in Roslyn 3.7+
* Fix nullability for `SymbolNamesWithValueOption`

Fixes #4350

### CODE REVIEW

File: src/Utilities/Compiler/Analyzer.Utilities.projitems [hunk 1]
```diff
@@ -11,6 +11,9 @@
   <PropertyGroup Condition="'$(MicrosoftCodeAnalysisVersion)' == '' OR '$(MicrosoftCodeAnalysisVersion)' &gt;= '3.3'">
     <DefineConstants>$(DefineConstants),CODEANALYSIS_V3_OR_BETTER</DefineConstants>
   </PropertyGroup>
+  <PropertyGroup Condition="'$(MicrosoftCodeAnalysisVersion)' == '' OR '$(MicrosoftCodeAnalysisVersion)' &gt;= '3.7'">
+    <DefineConstants>$(DefineConstants),CODEANALYSIS_V3_7_OR_BETTER</DefineConstants>
```
Comment (mavasani) [inline src/Utilities/Compiler/Analyzer.Utilities.projitems:15]: I am wondering that now that we don't support FxCopAnalyzers, would it be worth just repurposing `CODEANALYSIS_V3_OR_BETTER` define above to mean `3.7` and also bump up the underlying `Microsoft.CodeAnalysis` version used by the repo to `3.7`? What do you think? https://github.com/dotnet/roslyn-analyzers/blob/690be1702a6ae8f915da3bf6cc1b935e3ff264dd/eng/Versions.props#L28?

Comment (sharwell) [reply src/Utilities/Compiler/Analyzer.Utilities.projitems:15]: No objection, but perhaps better as a follow-up?

Comment (mavasani) [reply src/Utilities/Compiler/Analyzer.Utilities.projitems:15]: Sounds good.

Comment (mavasani) [reply src/Utilities/Compiler/Analyzer.Utilities.projitems:15]: I am still confused though, when is this condition true? None of our existing packages in this repo set `MicrosoftCodeAnalysisVersion` to 3.7 or greater.

Comment (sharwell) [reply src/Utilities/Compiler/Analyzer.Utilities.projitems:15]: Roslyn.Diagnostics.Analyzers sets it.

Comment (mavasani) [reply src/Utilities/Compiler/Analyzer.Utilities.projitems:15]: Ah, thanks :-)

**Review by mavasani — APPROVED** [review]

File: src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs [hunk 2]
```diff
@@ -19,7 +19,7 @@ public sealed class SymbolNamesWithValueOptionTests
         public void WhenNoSymbolNames_ReturnsEmpty()
         {
             // Arrange & act
-            var options = SymbolNamesWithValueOption<Unit>.Create(ImmutableArray<string>.Empty, GetCompilation(), null, null);
+            var options = SymbolNamesWithValueOption<Unit>.Create(ImmutableArray<string>.Empty, GetCompilation(), null, static name => new SymbolNamesWithValueOption<Unit>.NameParts(name, Unit.Default));
```
Comment (Evangelink) [inline src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs:22]: That looks like a possible good improvement for the make static rule, WDYT?

Comment (sharwell) [reply src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs:22]: I like it, but maybe should be a separate diagnostic ID so it can be turned off?

Comment (Evangelink) [reply src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs:22]: I am actually curious if it would be hard technically to allow fine-tuning of rule descriptor through the `.editorconfig` so that we can keep rules with a same scope under the same ID but allow specific descriptors to be tweaked.

For example, `dotnet_code_quality.CAXXXX.severity = warning` would keep the same behavior (it controls all descriptor for this ID) but `dotnet_code_quality.CAXXXX-desc1.severity = warning` only change the severity of one of the descriptors.

Comment (sharwell) [reply src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs:22]: Or something like https://github.com/dotnet/roslyn/issues/27712?

Comment (mavasani) [reply src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs:22]: I believe @sharwell has a compiler design proposal for allowing sub-diagnostics for similar configuration - different severity buckets for same ID. We should wait for that feature before attempting anything similar ourselves from an analyzer package.

Comment (Evangelink) [reply src/Utilities.UnitTests/Options/SymbolNamesWithValueOptionTests.cs:22]: Of course you thought about it before me xD And I even upvoted but forgot about it.
