### PR TITLE
CA2213: Fix false positive on disposable field

### LINKED ISSUE #6172: CA2213: False positive on disposable fields
### Analyzer

**Diagnostic ID**: [CA2213](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2213): `Disposable fields should be disposed`

### Steps To Reproduce

See linked draft PR.

### PR DESCRIPTION
**Pull request by Evangelink**
Fixes #6172

### CODE REVIEW

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs [hunk 1]
```diff
@@ -145,6 +149,16 @@ public bool HasAnyDisposableCreationDescendant(ImmutableArray<IOperation> operat
                 HasDisposableOwnershipTransferForConstructorParameter(containingMethod);
         }
 
+        public bool IsDisposableTypeNotRequiringToBeDisposed(ITypeSymbol typeSymbol) =>
```
Comment (Evangelink) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisHelper.cs:152]: Name is a little verbose but explain well (IMO) the goal. Let me know if you prefer something else.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs [hunk 2]
```diff
@@ -100,14 +100,14 @@ public sealed class DisposeAnalysisContext : AbstractDataFlowAnalysisContext<Dis
...
-                DisposeOwnershipTransferAtMethodCall, TrackInstanceFields, ControlFlowGraph, interproceduralAnalysisData, InterproceduralAnalysisPredicate, IsConfiguredToSkipAnalysis);
+                DisposeOwnershipTransferAtMethodCall, TrackInstanceFields, ControlFlowGraph, interproceduralAnalysisData, InterproceduralAnalysisPredicate, IsDisposableTypeNotRequiringToBeDisposed);
         }
 
         internal ImmutableHashSet<INamedTypeSymbol> DisposeOwnershipTransferLikelyTypes { get; }
         internal bool DisposeOwnershipTransferAtConstructor { get; }
         internal bool DisposeOwnershipTransferAtMethodCall { get; }
         internal bool TrackInstanceFields { get; }
-        internal Func<ISymbol, bool> IsConfiguredToSkipAnalysis { get; }
+        internal Func<ITypeSymbol, bool> IsDisposableTypeNotRequiringToBeDisposed { get; }
```
Comment (Evangelink) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs:110]: Maybe keeping old name and adding some xml doc would be better, wdyt?

**Comment by Evangelink** [comment]
@mavasani I spent some time trying to understand what's going on and I am a bit hesitant between two ways to solve the issue. First is the one implemented here and second would be to remove special casing from the dataflow and handle exclusions at the end. The second solution would require more changes through the dataflow but could help with discovery by allowing normal workflow during the analysis and special casing only when about to report.

WDYT?

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs (hunk 2 above)
Comment (mavasani) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysisContext.cs:110]: I think either way is fine given this is an internal property.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 3]
```diff
@@ -4020,11 +4018,6 @@ public sealed override TAbstractAnalysisValue VisitLocalFunction(ILocalFunctionO
         /// </summary>
         protected INamedTypeSymbol? TaskNamedType { get; }
 
-        /// <summary>
-        /// <see cref="INamedTypeSymbol"/> for <see cref="System.IO.MemoryStream"/>
-        /// </summary>
-        protected INamedTypeSymbol? MemoryStreamNamedType { get; }
```
Comment (mavasani) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:4026]: Technically these are breaking changes for any third-party sub-types of DataflowOperationVisitor, as can be seen from the build errors. However, we have never guaranteed back compat for this package, so I'll be fine with us deleting the corresponding entries in the public API file OR you can revert the changes to this source file. Either way should be fine.

**Comment by mavasani** [comment]
> @mavasani I spent some time trying to understand what's going on and I am a bit hesitant between two ways to solve the issue. First is the one implemented here and second would be to remove special casing from the dataflow and handle exclusions at the end. The second solution would require more changes through the dataflow but could help with discovery by allowing normal workflow during the analysis and special casing only when about to report.
> 
> WDYT?

I think the approach you chose in this PR is the one I'd prefer. Dispose analysis is used by multiple analyzer rules, and the checks within the dataflow visitor might be implicitly avoiding false positives in some of these rules.

**Comment by mavasani** [comment]
So the change here does address the regression, and should fix the false positive seen by the customer. However, I don't know if it fixes the underlying issue: a type that implements IDisposable has a Dispose call within the Dispose(bool) override, and the analysis is still unable to detect that the dispose call will happen on possible program paths. I think we did add some special analysis in dispose visitor to detect code patterns such as below and identify that the dispose calls within such if statements which checks the boolean disposing parameters actually ensure dispose on all paths, not some paths:

```csharp
            if (disposing)
            {
                // free managed resources
                _stream.Dispose();
            }
``` 

I think for now we should go ahead with the fix in this PR, as it is a correct change by itself, and fixes the customer issue. We may want to create a separate tracking issue to track the core bug though, likely with a user-defined type field instead of a `MemoryStream` field.

**Review by mavasani — APPROVED** [review]

**Comment by Evangelink** [comment]
@mavasani Thanks for the reminder! I wanted to create another ticket to investigate how/if we handle the fact that conditional disposing when following the dispose pattern should be considered as "always disposing".

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs (hunk 3 above)
Comment (Evangelink) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:4026]: Let me revert, that's fine, it will just not be used but the impact should be minimal.

**Comment by Evangelink** [comment]
@mavasani I didn't follow if you were in a snap or something. Can we merge this PR? Also shall we cherry-pick it for some .NET servicing?

**Comment by Evangelink** [comment]
ping @mavasani

**Comment by mavasani** [comment]
> I didn't follow if you were in a snap or something. Can we merge this PR?

@jmarolf - I presume main branch is still targeting .NET7, correct?

> Also shall we cherry-pick it for some .NET servicing?

I don't think that is necessary. This rule is disabled by default.
