### PR TITLE
Perform exceptions path analysis for all flow analyses

### LINKED ISSUE #4984: False positive CA1508: '{0}' is always 'null'. Remove or refactor the condition(s) to avoid dead code.
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 1.0
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

</Project>
```

**Steps to Reproduce**:
```csharp
namespace Ca1508FalsePositive
{
    using System;
    using System.Collections.Generic;

    class Program
    {
        private static object AutoDetectAndConnect(string host)
        {
            List<Exception> exceptions = null;
            foreach (string registeredScheduler in s_schedulers)
            {
                try
                {
                    object conn = Connect(registeredScheduler, host);
                    if (conn != null)
                        return conn;
                }
                catch (Exception ex)
                {
                    // warning CA1508: 'exceptions' is always 'null'. Remove or refactor the condition(s) to avoid dead code.
                    (exceptions ??= new List<Exception>()).Add(ex);
                }
            }

            // Commenting out this code block will "resolve" CA1508 above
            if (exceptions == null)
            {
                throw new NotSupportedException(host);
            }

            throw new AggregateException(exceptions);

            static object Connect(string a, string b) => throw new NotImplementedException($"{a}{b}");
        }

        static List<string> s_schedulers = new List<string>();
        static void Register(string scheduler) => s_schedulers.Add(scheduler);

        static void Main(string[] args)
        {
            Register("abc");
            Register("def");

            try
            {
                var conn = AutoDetectAndConnect(args.Length > 0 ? args[0] : args.GetHashCode().ToString());
                Console.WriteLine(conn);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}
```

**Expected Behavior**:
I should not be warning that `exceptions` is always `null`. It is only `null` with the first exception encountered.

**Actual Behavior**:
I receive CA1508 when lazily allocating the list. Interestingly enough, I do not receive CA1508 when I comment out the check for a null list below.

### LINKED ISSUE #5160: CA1508: false positive inside catch block nested in for loop
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.301](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

I enabled all the analyzers on 1 of my projects and noticed this false positive:

```csharp
public static void Main()
{
    const int attempts = 5;

    for (int i = 0; i < attempts; i++)
    {
        try
        {
            Console.WriteLine($"Hello world: {i}");

            if (i == attempts - 1) // Last iteration.
            {
                throw new InvalidOperationException("Oops, something went wrong!");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Exception caught: {ex.Message}");

            // CA1508: 'i == attempts - 1' is always 'false'. Remove or refactor the condition(s) to avoid dead code.
            if (i == attempts - 1)
            {
                Console.WriteLine("This should never happen, according to CA1508.");
            }
        }
    }
}
```

### Steps To Reproduce

Compile the above program with the following properties set in your `.csproj` file:

```xml
<PropertyGroup>
  <EnableNETAnalyzers>true</EnableNETAnalyzers>
  <AnalysisMode>AllEnabledByDefault</AnalysisMode>
</PropertyGroup>
```

### Expected behavior

`if (i == attempts - 1)` should not be flagged as dead code.

### Actual behavior

It gets flagged.

## Additional context

N/A.

### LINKED ISSUE #5199: Analyzer complaining about not disposing object (False positives)
<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

### Describe the bug

var item = new ItemData(scannedFileName: filePath);
return parseChannel.Writer.WriteAsync(item);

The class ItemData is indeed IDisposable and WriteAsync can throw, so yep I would an IDisposable error, which there is.

Changing to:

So, to address the issue I change that to this.

var item = new ItemData(scannedFileName: filePath);
try
{
    var parseTask = parseChannel.Writer.WriteAsync(item);
    item = null;
    return parseTask;
}
finally
{
    item?.Dispose();
}

Only results in:

Severity | Code | Description | Project | File | Line | Suppression State | Tool
-- | -- | -- | -- | -- | -- | -- | --
Warning | CA1508 | 'item' is always 'null'. Remove or   refactor the condition(s) to avoid dead code. | ItemCheck | ... | 636 | Active | Microsoft.CodeAnalysis.NetAnalyzers

Severity | Code | Description | Project | File | Line | Suppression State | Tool
-- | -- | -- | -- | -- | -- | -- | --
Warning | CA2000 | Call System.IDisposable.Dispose on object   created by 'new ItemData(scannedFileName: filePath)' before all   references to it are out of scope | ItemCheck | ... | 627 | Active | Microsoft.CodeAnalysis.NetAnalyzers

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #5199
Fixes #5160
Fixes #4984

We already had implementation and option based support to perform exception path analysis to handle all operations that can potentially throw an exception, and hence need flow analysis data at the point of operation to be merged with analysis data at start of reachable catch blocks from that operation. However, we were only performing this analysis post pass when flow analysis is looking at exceptions data. Now we do it for all analysis as this is required for more accurate input analysis data at start of catch and finally blocks.

**NOTE:** Fixing this issue led to an assert firing in CodeAnalysis dataflow operation visitor for an existing unit test, which has also been fixed in this PR

### CODE REVIEW

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs [hunk 1]
```diff
@@ -115,7 +115,12 @@ protected DataFlowAnalysis(AbstractAnalysisDomain<TAnalysisData> analysisDomain,
                     blockToUniqueInputFlowMap, loopRangeMap, exceptionPathsAnalysisPostPass: false);
                 normalPathsExitBlockData = resultBuilder.ExitBlockOutputData;
 
-                if (analysisContext.ExceptionPathsAnalysis)
+                // If we are executing exception paths analysis OR have at least one try/catch/finally block
+                // in the method, execute an exception path analysis post pass.
+                // This post pass will handle all possible operations within the control flow graph that can
+                // throw an exception and merge analysis data after all such operation analyses into the
+                // catch blocks reachable from those operations.
+                if (analysisContext.ExceptionPathsAnalysis || hasAnyTryBlock)
```
Comment (mavasani) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs:123]: This is the core fix

**Comment by mavasani** [comment]
@Youssef1313

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs [hunk 2]
```diff
@@ -286,11 +291,9 @@ protected DataFlowAnalysis(AbstractAnalysisDomain<TAnalysisData> analysisDomain,
 
                 // Check if we are starting a try region which has one or more associated catch/filter regions.
                 // If so, we conservatively merge the input data for try region into the input data for the associated catch/filter regions.
-#pragma warning disable CA1508 // Avoid dead conditional code - https://github.com/dotnet/roslyn-analyzers/issues/4408
```
Comment (Youssef1313) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowAnalysis.cs:289]: Nice!

**Review by Youssef1313 — APPROVED** [review]
