### PR TITLE
Port FxCop rule CA1064: ExceptionsShouldBePublic

### LINKED ISSUE #406: Port FxCop rule CA1064: ExceptionsShouldBePublic
**Title:** Exceptions should be public

**Description:**

An internal exception is visible only inside its own internal scope. After the exception falls outside the internal scope, only the base exception can be used to catch the exception. If the internal exception is inherited from T:System.Exception, T:System.SystemException, or T:System.ApplicationException, the external code will not have sufficient information to know what to do with the exception.

**Dependency:** None

**Notes:**

### PR DESCRIPTION
**Pull request by natidea**
Fixes #406 

Original Rule: [ExceptionsShouldBePublic.cs](http://index/#DesignRules/ExceptionsShouldBePublic.cs,1545b1171e2f2e3d)

### CODE REVIEW

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs [hunk 1]
```diff
@@ -24,16 +26,50 @@ public abstract class ExceptionsShouldBePublicAnalyzer : DiagnosticAnalyzer
...
+                context.ReportDiagnostic(symbol.CreateDiagnostic(Rule));
+            }
+        }
+
+        private bool IsExceptionType(SymbolAnalysisContext context, INamedTypeSymbol baseType)
+        {
+            return GetExceptionTypes(context).Contains(baseType);
+        }
+
+        private HashSet<INamedTypeSymbol> exceptionTypes;
```
Comment (srivatsn) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs]: Don't do this. Since an analyzer lives for the life time of VS, this will field will hold on to the exception symbols from the very first compilation and that will cause the entire compilation to stay alive causing a leak. Worse, for new compilation the symbol for System.Exception might not be the same as the one for the first compilation and this could result in a functional error as well.

Register a CompilationStartAction and put this HashSet there so that it goes away when the compilation is done.

Comment (natidea) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs]: Fixed with CompilationStartAction

**Comment by srivatsn** [comment]
:+1:

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs [hunk 2]
```diff
@@ -24,16 +28,48 @@ public abstract class ExceptionsShouldBePublicAnalyzer : DiagnosticAnalyzer
...
+
+        private void AnalyzeCompilationStart(CompilationStartAnalysisContext csContext)
+        {
+            // Get named type symbols for targetted exception types
+            var exceptionTypes = s_exceptionTypeNames
+                .Select(name => csContext.Compilation.GetTypeByMetadataName(name))
+                .Where(t => t != null)
+                .ToImmutableHashSet();
+
+            // register symbol action for named types
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs]: check for empty `exceptionTypes` and bail out here?

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs [hunk 3]
```diff
@@ -24,16 +28,48 @@ public abstract class ExceptionsShouldBePublicAnalyzer : DiagnosticAnalyzer
...
+            csContext.RegisterSymbolAction(saContext => 
+            {
+                var symbol = (INamedTypeSymbol)saContext.Symbol;
+
+                // skip public symbols
+                if (symbol.IsPublic()) return;
+
+                // only report if base type matches 
+                if (exceptionTypes.Contains(symbol.BaseType))
```
Comment (mavasani) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs]:
```
non-public AException {MyLibrary.dll} ->
    public BException {ReferencedLibrary.dll} ->
      System.Exception
```
We should fire on AException.

Comment (natidea) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/ExceptionsShouldBePublic.cs]: Current FxCop implementation matches [MSDN doc](https://msdn.microsoft.com/en-us/library/bb264484.aspx), specifically:
> But, if the code has a public exception that later is used as the base for a internal exception, it is reasonable to assume the code further out will be able to do something intelligent with the base exception. The public exception will have more information than what is provided by T:System.Exception, T:System.SystemException, or T:System.ApplicationException.

Even if the public exception is in a different library, it is still likely more specific than `Exception`

**Comment by mavasani** [comment]
:+1:
