### PR TITLE
Report a warning for APIs marked removed but are not removed

### LINKED ISSUE #1506: Roslyn Public API analyzer tool passes invalid configuration
In this PR: https://github.com/dotnet/roslyn/pull/24023

A few changes were made to rename an API. Thus adding `*REMOVED*` entries in the `Unshipped.txt` file, and adding new entries for the new API. To guard against breaking compatibility, the removed APIs were added again to source.

I expected the tool to fail, as the `Unshipped.txt` file has `*REMOVED*` entries that still exists in source, but the tool didn't. It was passing and jenkins was green. The tool should be modified to handle this case.

### LINKED ISSUE #3329: Public API Analyzers do not complain on removed apis that are not removed
#### Analyzer package

Microsoft.CodeAnalysis.PublicApiAnalyzers

#### Package Version

v2.9.8 (Latest)

#### Diagnostic ID

None

#### Repro steps

1. Check out dotnet/roslyn to commit f265123a657ca6c27e5ad68d6edf4bdbb9be1b6f
2. Note that there is a `*REMOVED*Microsoft.CodeAnalysis.CommandLineArguments.ErrorLogPath.get -> string` entry in `src/Compilers/Core/Portable/PublicAPI.Unshipped.txt`
3. Note that the API does, in fact, exist: https://github.com/dotnet/roslyn/blob/f265123a657ca6c27e5ad68d6edf4bdbb9be1b6f/src/Compilers/Core/Portable/CommandLine/CommandLineArguments.cs#L133-L137

#### Expected behavior

Error about API that was removed but is still present.

#### Actual behavior

No error.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #3329
Fixes #1506

### CODE REVIEW

File: src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs [hunk 1]
```diff
@@ -610,6 +610,37 @@ public class C
...
+}
+";
+
+            var shippedText = @"
+C
+C.C() -> void
+C.Field -> int
+C.Property.get -> int
+C.Property.set -> void
+C.Method() -> void
```
Comment (mavasani) [inline src/PublicApiAnalyzers/UnitTests/DeclarePublicApiAnalyzerTests.cs:632]: Can you also add a test where `C.Method() -> void` is not present in the shipped text?

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@Youssef1313 I can merge the PR once the requested test has been added. Thanks!

**Review by mavasani — APPROVED** [review]
Thanks!
