### PR TITLE
Exclude GetPinnableReference from CA1024 analysis

### LINKED ISSUE #4634: CA1024: False positive for special method GetPinnableReference
### Analyzer

**Diagnostic ID**: [CA1024](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1024): Use properties where appropriate

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Describe the bug

Rule CA1024 doesn't treat `GetPinnableReference` (used for allowing the type to be `fixed`) as a special method name, like it does with `GetHashCode` or `GetEnumerator` and instead triggers a warning on such methods.

### Steps To Reproduce

1. Add some code looking something like this:
```cs
public unsafe class Foo {
    private int _bar;
    public ref int GetPinnableReference() { return ref _bar; }
    public void Baz() { fixed (int* bar = this) { } }
}
```
2. Enable the CA1024 diagnostic
3. Analyze the code
3. Note the warning regarding `GetPinnableReference` being better off as a property.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #4634

### CODE REVIEW

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs [hunk 1]
```diff
@@ -117,6 +117,11 @@ public IEnumerator GetEnumerator()
         return null;
     }
 
+    public int GetPinnableReference() // Ideally, the method return type must be `ref`.
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs:120]: Let me know if you want this to report a diagnostic, and only ref-returns doesn't.

Comment (sharwell) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs:120]: Does pattern-based `fixed` allow `GetPinnableReference` to return a pointer type?

I believe the exclusion should only apply to methods that match the pattern by filtering to `ref` and `ref readonly` returns.

Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs:120]: According to the doc it's even more restrictive than this: https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/fixed-statement

Comment (sharwell) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs:120]: The `ref` check seems easy and catches most cases. I don't think we need to check the unmanaged type restriction.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs [hunk 2]
```diff
@@ -117,6 +117,11 @@ public IEnumerator GetEnumerator()
         return null;
     }
 
+    public ref string GetPinnableReference() // If the method isn't ref-returning, there will be a diagnostic.
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs:120]: Could you add a test for `readonly ref` (or the other way around, I can't recall the expected order). Also, could you add a test for a managed type.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs [hunk 3]
```diff
@@ -76,8 +77,8 @@ public override void Initialize(AnalysisContext analysisContext)
                     if (methodSymbol.IsGenericMethod ||
                         methodSymbol.IsVirtual ||
                         methodSymbol.IsOverride ||
-                        methodSymbol.Name == GetHashCodeName ||
-                        methodSymbol.Name == GetEnumeratorName ||
+                        methodSymbol.Name is GetHashCodeName or GetEnumeratorName ||
+                        (methodSymbol.Name == GetPinnableReferenceName && (methodSymbol.ReturnsByRef || methodSymbol.ReturnsByRefReadonly)) ||
```
Comment (Youssef1313) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs:81]: Is there a better way to write this condition using the new pattern matching enhancement?

Comment (Evangelink) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs:81]: It's non C# 9 but you could simply extract the code in a function `IsPinnableReferenceMethod`, also this could maybe be part of the helpers, I suspect some other rules will have to use it.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs (hunk 2 above)
Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs:120]: I think you missed the managed type case.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs (hunk 3 above)
Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs:81]: Do we need to special case ref and ref readonly checks only to methods named `GetPinnableReference` or should we do it regardless of the method name? @sharwell for thoughts.

Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs:81]: Tag @sharwell again for the last question. Otherwise, LGTM.

Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/UsePropertiesWhereAppropriate.cs:81]: Going to keep the current restrictive check - if needed, we can adjust it in future.

**Review by mavasani — APPROVED** [review]
