### PR TITLE
Find tainted data parameter SyntaxNodes more robustly, and don't treat ASP.NET MVC Controller property setter parameters as tainted

### LINKED ISSUE #4495: Multiple IndexOutOfRangeExceptions with public Controller properties
### Analyzers

**Diagnostic IDs**:
-  [CA3001](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3001): "Review code for SQL injection vulnerabilities"
-  [CA3003](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3003): "Review code for file path injection vulnerabilities"
-  [CA3006](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3006): "Review code for process command injection vulnerabilities"
-  [CA3008](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3008): "Review code for XPath injection vulnerabilities"
-  [CA3009](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3009): "Review code for XML injection vulnerabilities"
-  [CA3011](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3011): "Review code for DLL injection vulnerabilities"
-  [CA3012](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca3012): "Review code for regex injection vulnerabilities"

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

If a `Microsoft.AspNetCore.Mvc.Controller` class contains a public non-static property setter, each of the above seven analyzers will throw an `IndexOutOfRangeException`.

### Steps To Reproduce

1. Create an ASP.NET Core project or .NET class library with a `<FrameworkReference />` set to `Microsoft.AspNetCore.App`.
2. Set the `<AnalysisMode />` to `AllEnabledByDefault` to enable the extended collection of code analyzers.
3. Create a class deriving from `Microsoft.AspNetCore.Mvc.Controller`.
4. Add a property with a public, non-auto-implemented setter.

### Minimum Reproducible Example

**`csproj`:**
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp5.0</TargetFramework>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
```

**`cs`:**
```cs
public class MyController: Microsoft.AspNetCore.Mvc.Controller 
{
  public bool IsValue 
  {
    set => _ = value;
  }
}
```

### Expected behavior

The above analyzers should evaluate the public setter, if appropriate, without throwing an exception.

### Actual behavior

The following is one example of the exceptions thrown in Visual Studio in this scenario. Each of the seven exceptions follow the same basic pattern, varying exclusively by the analyzer name.
```
Analyzer 'Microsoft.NetCore.Analyzers.Security.ReviewCodeForCommandExecutionVulnerabilities' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: MyProject
ISymbol: set_IsValue (Method)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataAnalysis.TaintedDataOperationVisitor.GetDefaultValueForParameterOnEntry(IParameterSymbol parameter, AnalysisEntity analysisEntity)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.AnalysisEntityDataFlowOperationVisitor`4.SetValueForParameterOnEntry(IParameterSymbol parameter, AnalysisEntity analysisEntity, ArgumentInfo`1 assignedValue)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.OnStartEntryBlockAnalysis(BasicBlock entryBlock)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowOperationVisitor`4.OnStartBlockAnalysis(BasicBlock block, TAnalysisData input)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.Flow(DataFlowOperationVisitor`4 operationVisitor, BasicBlock block, TAnalysisData data)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.RunCore(ControlFlowGraph cfg, PooledSortedSet`1 worklist, PooledSortedSet`1 pendingBlocksNeedingAtLeastOnePass, TAnalysisData initialAnalysisData, DataFlowAnalysisResultBuilder`1 resultBuilder, PooledHashSet`1 uniqueSuccessors, PooledDictionary`2 finallyBlockSuccessorsMap, PooledDictionary`2 catchBlockInputDataMap, PooledDictionary`2 inputDataFromInfeasibleBranchesMap, PooledDictionary`2 blockToUniqueInputFlowMap, PooledDictionary`2 loopRangeMap, Boolean exceptionPathsAnalysisPostPass)
   at Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.DataFlowAnalysis`5.Run(TAnalysisContext analysisContext)
   at Analyzer.Utilities.SingleThreadedConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataAnalysis.TryGetOrComputeResult(ControlFlowGraph cfg, Compilation compilation, ISymbol containingMethod, AnalyzerOptions analyzerOptions, TaintedDataSymbolMap`1 taintedSourceInfos, TaintedDataSymbolMap`1 taintedSanitizerInfos, TaintedDataSymbolMap`1 taintedSinkInfos, InterproceduralAnalysisConfiguration interproceduralAnalysisConfig)
   at Microsoft.NetCore.Analyzers.Security.SourceTriggeredTaintedDataAnalyzerBase.<>c__DisplayClass6_1.<Initialize>b__9(OperationBlockAnalysisContext operationBlockAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__67`2.<ExecuteBlockActions>b__67_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: CA3006
```

> _Note:_ Obviously, these exceptions bubble up to the IDE as an AD0001.

## Additional context

This exception is **not** thrown in the following scenarios:
- The property is configured as a `static` member.
- The property's access modifier is set to anything other than `public`.
- The property's setter uses an auto-implemented accessor.
- The property's setter does not make a reference to `value`.

> _Note:_ We can debate about whether or not it makes sense to have a public property on a controller. I find it useful in some unit testing scenarios. Regardless, this is an otherwise valid construction and should not result in an exception.

### PR DESCRIPTION
**Pull request by dotpaul**
Fixes #4495

### CODE REVIEW

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs [hunk 1]
```diff
@@ -119,7 +119,23 @@ protected override TaintedDataAbstractValue GetDefaultValueForParameterOnEntry(I
...
                 if (this.DataFlowAnalysisContext.SourceInfos.IsSourceParameter(parameter, WellKnownTypeProvider))
                 {
-                    return TaintedDataAbstractValue.CreateTainted(parameter, parameter.DeclaringSyntaxReferences[0].GetSyntax(), this.OwningSymbol);
+                    // Location of the parameter, so we can track where the tainted data appears in code.
+                    SyntaxNode parameterSyntaxNode;
+                    if (!parameter.DeclaringSyntaxReferences.IsEmpty)
+                    {
+                        parameterSyntaxNode = parameter.DeclaringSyntaxReferences[0].GetSyntax();
+                    }
+                    else if (!parameter.ContainingSymbol.DeclaringSyntaxReferences.IsEmpty)
```
Comment (Evangelink) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs:128]: Could we add a comment with an example for this case so that later on when reviewing we easily understand.

Also, you said you would want to ignore the case but as far as I understand this case is going to consider the property as tainted (I mean at least as tracked), isn't it?

Comment (Evangelink) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs:128]: Ah ok, it is excluded with the change in `WebInputSources` but you still want robustness here in case we have another similar case. 

Depending on people there seems to be different approach but I have seen a couple of comments on roslyn going in the direction of let's fail if that's an unexpected scenario so that we can figure them out and do the right fix/change. So do we want to keep failures to discover other cases where we don't have the syntax?

**Review by Evangelink — APPROVED** [review]
1 open question and 1 suggestion but LGTM

**Review by mavasani — APPROVED** [review]

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs (hunk 1 above)
Comment (dotpaul) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs:128]: Sure, added comments

For this case, I think I prefer robustness (and if anyone uses debug builds, debug asserts will show up). Worst case is a false negative.

**Comment by dotpaul** [comment]
Thank you @Evangelink and @mavasani !
