### PR TITLE
CA1068: Do not report when last argument is of type IProgress<T>

### LINKED ISSUE #2281: Let CA1068 not report on a method taking IProgress as the last parameter
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.1

#### Diagnostic ID

CA1068

#### Repro steps
```cs
using System;
using System.Threading;
using System.Threading.Tasks;

public class C
{
    public Task SomeAsync(CancellationToken cancellationToken, IProgress<int> progress)
    {
        throw new NotImplementedException();
    }
}
```

#### Expected behavior
CA1068 is not reported.
Because some Microsoft's documentations take IProgress as the last parameter:
1. https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/implementing-the-task-based-asynchronous-pattern#io-bound-tasks
1. https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap#choosing-the-overloads-to-provide

#### Actual behavior
CA1068 is reported:
`Method 'C.SomeAsync(System.Threading.CancellationToken, System.IProgress<int>)' should take CancellationToken as the last parameter`

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #2281

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs [hunk 1]
```diff
@@ -37,76 +37,88 @@ public override void Initialize(AnalysisContext context)
 
             context.RegisterCompilationStartAction(compilationContext =>
             {
-                INamedTypeSymbol cancellationTokenType = compilationContext.Compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemThreadingCancellationToken);
-                if (cancellationTokenType != null)
+                var wellKnownTypeProvider = WellKnownTypeProvider.GetOrCreate(compilationContext.Compilation);
+                INamedTypeSymbol cancellationTokenType = wellKnownTypeProvider.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemThreadingCancellationToken);
+                INamedTypeSymbol iprogressType = wellKnownTypeProvider.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemIProgress1);
+                if (cancellationTokenType == null)
```
Comment (Evangelink) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: I am not exiting here when `iprogressType` to keep the previous behavior.

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs [hunk 2]
```diff
@@ -37,76 +37,88 @@ public override void Initialize(AnalysisContext context)
 
             context.RegisterCompilationStartAction(compilationContext =>
             {
-                INamedTypeSymbol cancellationTokenType = compilationContext.Compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemThreadingCancellationToken);
-                if (cancellationTokenType != null)
```
Comment (Evangelink) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: I reverted the if statement to reduce nesting.

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs [hunk 3]
```diff
@@ -37,76 +37,88 @@ public override void Initialize(AnalysisContext context)
...
+                        last--;
+                    }
+
+                    // Ignore parameters passed by reference when they appear at the end of the parameter list.
+                    while (last >= 0 && methodSymbol.Parameters[last].RefKind != RefKind.None)
+                    {
+                        last--;
+                    }
+
+                    // Ignore IProgress<T> when last
```
Comment (Evangelink) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: Shall I handle multiple `IProgress` arguments?

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs [hunk 4]
```diff
@@ -238,6 +238,66 @@ public static void M1(this object p1, CancellationToken p2, object p3)
...
+Imports System.Threading
+Imports System.Threading.Tasks
+
+Public Class C
+    Public Function SomeAsync(ByVal cancellationToken As CancellationToken, ByVal o As Object, ByVal progress As IProgress(Of Integer)) As Task
+        Throw New NotImplementedException()
+    End Function
+End Class",
+            new DiagnosticResult(CancellationTokenParametersMustComeLastAnalyzer.Rule).WithLocation(7, 21)
+                .WithArguments("Public Function SomeAsync(cancellationToken As System.Threading.CancellationToken, o As Object, progress As System.IProgress(Of Integer)) As System.Threading.Tasks.Task"));
```
Comment (Evangelink) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs]: The message is quite weird compared to C#, was it expected? I have seen that there isn't any test for VB.NET while the analyzer actually targets VB.NET.

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs (hunk 3 above)
Comment (sharwell) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: I've never seen guidelines allowing for this, so I would say only allow one for now. A test would be good so show the current behavior.

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs (hunk 4 above)
Comment (sharwell) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs]: I'd say it's fine unless either:

1. We have specific guidelines for how to format signatures in messages like this, and this isn't following it
2. Someone is complaining about it and wants to propose a solution

Comment (sharwell) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs]: Either way, since it didn't _change_ as part of this pull request I would not expect it to need a fix here. 😄

**Comment by sharwell** [comment]
@Evangelink In the future can you avoid force-pushes that change the base commit after the review starts unless absolutely necessary? It caused the diff to pick up a large number of unrelated changes: https://github.com/dotnet/roslyn-analyzers/compare/1ae96c3808c79ddbac1ee07b1b0030b4ebe4ea8b..f3ca827359bd681a2c152895ae59b83938d57012

**Comment by sharwell** [comment]
I was waiting for @mavasani to second review and merge
