### PR TITLE
CA2225: array types for implicit and explicit conversions

### LINKED ISSUE #4063: CA2225 alternate name is wrong if operator type is SomeType[] (read SomeTypeArray)
### Describe the bug

Alternate method name for operator is wrong (type missing), if that type is an array such as `byte[]`.

### Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Create a struct named MyStruct
2. Create an explicit operator method with signature `public static explicit operator byte[](MyStruct myStruct)`
3. Look in the warning window
4. See error `Warning	CA2225	Provide a method named 'To' or 'FromMyStruct' as an alternate for operator op_Explicit`

### Expected behavior

Suggests `ToByteArray` or `FromMyStruct`.

### Actual behavior

Suggests `To` or `FromMyStruct`.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.0 (Latest)

**Diagnostic ID**: [CA2225](https://docs.microsoft.com/visualstudio/code-quality/ca2225)

## Additional context

My code is using `byte[]` type operator specifically.

I have done my research and the bug is not the same as #3834. (Though, that bug still exists)

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #4063

### CODE REVIEW

**Review by mavasani — APPROVED** [review]

File: src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs [hunk 1]
```diff
@@ -80,6 +80,15 @@ internal static class DiagnosticExtensions
             return symbol.Locations.CreateDiagnostic(rule, args);
         }
 
+        public static Diagnostic CreateDiagnostic(
```
[the remark this answers is not in the document]
Comment (Evangelink) [reply src/Utilities/Compiler/Extensions/DiagnosticExtensions.cs:83]: Oops no it's not. I wanted to do a little refactoring on the analyzer but thought it'd be best as a separate PR.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.cs [hunk 2]
```diff
@@ -213,6 +213,96 @@ struct C
...
+            await VerifyCS.VerifyAnalyzerAsync(
+@"
+public struct MyStruct
+{
+    public static implicit operator byte[,](MyStruct myStruct)
+    {
+        return new byte[1,1];
+    }
+}",
+                VerifyCS.Diagnostic(OperatorOverloadsHaveNamedAlternatesAnalyzer.MultipleRule).WithSpan(4, 37, 4, 44).WithArguments("ToByteArray", "FromMyStruct", "op_Implicit"));
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.cs:258]: We might want to have `ToByteMultiDimensionalArray` instead.

Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternatesTests.cs:258]: I think `ToByteArray` also seems fine to me.
