### PR TITLE
Fix CA2119 to report only on correct interface members

### LINKED ISSUE #4566: CA2119 false positive
### Analyzer

**Diagnostic ID**: [https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2119): `Seal methods that satisfy private interfaces`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Describe the bug

See attached project.

### Steps To Reproduce

Load and compile the attached project.

### Expected behavior

CA2119 should not fire.

### Actual behavior

CA2119 fires.

## Additional context

It would be beneficial if CA2119 reported which interfaces/methods caused the rule violation.

[CA2119.ZIP](https://github.com/dotnet/roslyn-analyzers/files/5682491/CA2119.ZIP)

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #4566

Feel free to drop 1st commit if you don't want it to be included in this fix.

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs [hunk 1]
```diff
@@ -46,37 +46,44 @@ private static void CheckTypes(SymbolAnalysisContext context)
...
             {
-                // look for implementations of interfaces members declared on this type
-                foreach (var iface in type.AllInterfaces)
+                return;
+            }
+
+            // look for implementations of interfaces members declared on this type
+            var directInterfacesAndTheirInterfaces = type.Interfaces.SelectMany(i => Enumerable.Repeat(i, 1).Concat(i.AllInterfaces))
+                .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default);
+            foreach (INamedTypeSymbol iface in directInterfacesAndTheirInterfaces)
```
Comment (Evangelink) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs:60]: This if the fix.

**Review by mavasani — APPROVED** [review]
