### PR TITLE
Fix issues with FixAll application for RS0036 and RS0037 (add #nullab…

### LINKED ISSUE #3965: RS0037 fix-all duplicate `#nullable enable` lines if some API baselines exist
### Describe the bug

Ran the RS0037 fixer on one of the filtered solutions in dotnet/aspnetcore, built again, and saw up to three RS0024 errors.

### Steps To Reproduce

1. `git clone --recurse-submodules git@github.com:dotnet/aspnetcore.git` # or use https://github.com/dotnet/aspnetcore.git
2. `.\restore.cmd` # to install the .NET SDK and any needed runtimes as well as restore all projects
3. `git switch --detach e13368391b` # ensure only some projects have `PublicApi.*.txt` files
4. `.\src\Analyzers\startvs.cmd` # open default Visual Studio instance on Analyzers.slnf
5. Build the filtered solution e.g. `F6`
6. Run RS0016 fix-all
7. `dir -r PublicApi.Shipped.txt |? {$_.Length -gt 25} |% FullName`

### Expected behavior

All of the `PublicApi.Shipped.txt` files except the one in src\submodules\MessagePack-CSharp\src\MessagePack\ should be essentially empty i.e. only that file should be listed.

### Actual behavior

All `PublicApi.Shipped.txt` files that previously existed in the repo are listed. These files are now invalid due to RS0024 errors.

### Analyzer

**Package**: [Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/)

(Actually using the https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json feed.)

**Version**: 3.3.0-beta3.20405.2

**Diagnostic ID**: [RS0037](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

## Additional context

Ideal would be to remove the need to have `#nullable enable` in the API baseline files at all. See #3962 for more on that.

See also #3957

### PR DESCRIPTION
**Pull request by mavasani**
…le enable to public API files)

Fixes #3965

I was unable to add unit tests as this requires multiple projects with differing contents of input and fixed public API files, I am unable to figure out how to write a unit test with the new test library for this scenario.

### CODE REVIEW

**Comment by mavasani** [comment]
@dougbu I verified that using the locally built package after this change, fix all works for RS0016, RS0037 and RS0036 (in that order) and resolves the issues you have been seeing.

**Comment by mavasani** [comment]
Attempt at writing a unit test led to https://github.com/dotnet/roslyn-sdk/issues/578

File: src/PublicApiAnalyzers/Core/CodeFixes/NullableEnablePublicApiFix.cs [hunk 1]
```diff
@@ -80,16 +81,21 @@ protected override async Task<Solution> GetChangedSolutionAsync(CancellationToke
...
-                foreach (KeyValuePair<Project, ImmutableArray<Diagnostic>> pair in _diagnosticsToFix)
+                using var uniqueShippedDocuments = PooledHashSet<string>.GetInstance();
+                foreach (var project in _projectsToFix)
                 {
-                    Project project = pair.Key;
                     TextDocument? shippedDocument = DeclarePublicApiFix.GetShippedDocument(project);
-                    SourceText? shippedSourceText = shippedDocument is null ? null : await shippedDocument.GetTextAsync(cancellationToken).ConfigureAwait(false);
-                    if (shippedSourceText is object)
+                    if (shippedDocument == null ||
+                        shippedDocument.FilePath != null && !uniqueShippedDocuments.Add(shippedDocument.FilePath))
```
Comment (Evangelink) [inline src/PublicApiAnalyzers/Core/CodeFixes/NullableEnablePublicApiFix.cs:89]: I would add parenthesis around the and block just to avoid confusion for maintenance later on. Feel free to ignore.

```suggestion
                        (shippedDocument.FilePath != null && !uniqueShippedDocuments.Add(shippedDocument.FilePath)))
```

Comment (mavasani) [reply src/PublicApiAnalyzers/Core/CodeFixes/NullableEnablePublicApiFix.cs:89]: This is common code style in both Roslyn reps and we only put parentheses where either both sides of or have complex expressions or parentheses are needed for precedence.

Comment (Evangelink) [reply src/PublicApiAnalyzers/Core/CodeFixes/NullableEnablePublicApiFix.cs:89]: Fine by me :)

**Comment by mavasani** [comment]
Thanks @Evangelink
