### PR TITLE
Fix CA1508 for compound assignments

### LINKED ISSUE #6532: CA1508 false-positive when using compound assignments and ternary expressions
### Analyzer

**Diagnostic ID**: [CA1508](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 7.0.201](https://dotnet.microsoft.com/download/dotnet/7.0)

### Describe the bug

CA1508 produces false-positives when the modification is a compound assignment with a ternary expression.

### Steps To Reproduce

```csharp
void M()
{
    var i = 0;
    i += M2() ? 1 : 0;
    _ = i != 0; // CA1508: 'i != 0' is always 'false'. Remove or refactor the condition(s) to avoid dead code.
}

bool M2() => true;
```

### Expected behavior
No diagnostic.

### Actual behavior
CA1508 recognizes the expression as "always false", even though it may be true if `M2` returns `true`.

## Additional context
* If the compound assignment's RHS is a simple expression (e.g. invocation of a method returning an integer), the diagnostic is not emitted.
* If the compound assignment is converted into a regular assignment with a binary expression, the diagnostic is not emitted.

### PR DESCRIPTION
**Pull request by CollinAlpert**
The `DataFlowOperationVisitor` does not handle `IFlowCaptureReferenceOperation`s in compound assignments, only in simple assignments.
Since this is deep in the ValueContentAnalysis, an area I am not at all familiar in, I would appreciate any feedback regarding side-effects this change might have.
Fixes #6532

### CODE REVIEW

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 1]
```diff
@@ -2767,7 +2767,15 @@ public override TAbstractAnalysisValue VisitCompoundAssignment(ICompoundAssignme
             TAbstractAnalysisValue targetValue = Visit(operation.Target, argument);
             TAbstractAnalysisValue assignedValue = Visit(operation.Value, argument);
             var value = ComputeValueForCompoundAssignment(operation, targetValue, assignedValue, operation.Target.Type, operation.Value.Type);
```
Comment (sharwell) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2769]: 📝 Note to self: `ValueContentDataFlowOperationVisitor` overrides this method to properly account for the binary operation that is part of the compound assignment.

**Review by sharwell — CHANGES_REQUESTED** [review]

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 2]
```diff
@@ -2767,7 +2767,15 @@ public override TAbstractAnalysisValue VisitCompoundAssignment(ICompoundAssignme
...
-            SetAbstractValueForAssignment(operation.Target, operation.Value, value);
+            if (operation.Target is IFlowCaptureReferenceOperation flowCaptureReference)
+            {
+                HandleFlowCaptureReferenceAssignment(flowCaptureReference, operation.Value, assignedValue);
+            }
+            else
+            {
+                SetAbstractValueForAssignment(operation.Target, operation.Value, assignedValue);
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2776]: 📝 Assigned value is the value on the right-hand side of the compound assignment. `value` is the computed value after applying the binary operation.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 3]
```diff
@@ -2767,7 +2767,15 @@ public override TAbstractAnalysisValue VisitCompoundAssignment(ICompoundAssignme
             TAbstractAnalysisValue targetValue = Visit(operation.Target, argument);
             TAbstractAnalysisValue assignedValue = Visit(operation.Value, argument);
             var value = ComputeValueForCompoundAssignment(operation, targetValue, assignedValue, operation.Target.Type, operation.Value.Type);
-            SetAbstractValueForAssignment(operation.Target, operation.Value, value);
+            if (operation.Target is IFlowCaptureReferenceOperation flowCaptureReference)
```
Comment (sharwell) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: 📝 The lack of a test failure with this change means we have a test gap. Please try to add a test for `ValueContentDataFlowOperationVisitor` that includes a compound assignment, and depends on a correct calculation coming from this method.

Comment (CollinAlpert) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: I'm not quite sure I understand. Do you mean a unit test for the class `ValueContentDataFlowOperationVisitor`? If so, could you direct me to an example of where a `DataFlowOperationVisitor`is already being tested, since it has quite a few dependencies I'd need to recreate.

Comment (sharwell) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: It would probably be a unit test for some analyzer that already depends on `ValueContentDataFlowOperationVisitor`, implemented by providing inputs to that analyzer that include compound operators that affect the overall output of the analysis.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs (hunk 2 above)
[the remark this answers is not in the document]
Comment (CollinAlpert) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs]: Done.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs (hunk 3 above)
Comment (CollinAlpert) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: Got it. I'll see if I can get that to work.

Comment (CollinAlpert) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: Indeed, that worked, thanks. I've added the test.

Comment (sharwell) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: Did you also locally test that it failed prior to changing `assignedValue`&rarr;`value`?

Comment (CollinAlpert) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:2770]: Yes, I did. The test failed.

**Comment by CollinAlpert** [comment]
Is there still anything left to do @sharwell?

**Review by mavasani — APPROVED** [review]
LGTM

@sharwell Are you fine to sign off/merge?

**Comment by mavasani** [comment]
Merging as the original concern has been addressed. We can have a follow-up PR for any further feedback.
