### PR TITLE
CA1822: Update rule to flag more cases

### LINKED ISSUE #3019: CA1822 doesn't suggest method be made static if called from xUnit fact
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v2.9.7

#### Diagnostic ID

CA1822 Mark members as static

#### Repro steps

```c#
using Xunit;

public class Program
{
    [Fact]
    private void M()
    {
        N();
    }

    private void N() // expected suggestion to convert to static
    {
    }
}
```

#### Expected behavior

Suggests method `N` should be static.

#### Actual behavior

No suggestion.

Removing the `FactAttribute` from `M` causes the suggestion to appear as expected.

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #3019 

With this change the analyzer will look for invocations located in _ALL_ methods but will keep raising issues only on correct ones. Thanks to this change we shall be able to report a lot more cases where the method could be made `static`.

### CODE REVIEW

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 1]
```diff
@@ -577,6 +577,70 @@ End Class
...
+                TestState =
+                {
+                    Sources =
+                    {
+                        @"
+using Xunit;
+
+public class Program
+{
+    [Fact]
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs]: I only made a test with `Fact` as it is the one reported in the ticket. Is it worth adding test cases for all of the exit conditions of the `ShouldAnalyze` method?

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs [hunk 2]
```diff
@@ -70,29 +69,36 @@ public override void Initialize(AnalysisContext analysisContext)
 
                 compilationContext.RegisterOperationBlockStartAction(blockStartContext =>
                 {
-                    if (!(blockStartContext.OwningSymbol is IMethodSymbol methodSymbol) || !ShouldAnalyze(methodSymbol, wellKnownTypeProvider, skippedAttributes))
```
Comment (mavasani) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs]: Wow, I wonder how it took so long to discover this bug. Thanks!

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 1 above)
Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs]: I think this coverage is fine.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 2 above)
Comment (Evangelink) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs]: It was probably simply not reported.
