### PR TITLE
Bail out early for delegates and interfaces in serialization analyzer

### LINKED ISSUE #1335: Null reference exception in Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer
**Version Used**: Install latest d15rel drop 27031.1.d15rel

**Steps to Reproduce**:

1. git clone https://github.com/JamesNK/Newtonsoft.Json
2. add myget package feed for roslyn-analyzers: https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json
3. install latest preview of Microsoft.CodeAnalysis.FxCopAnalyzers version 2.6.0-beta1-62231-02 to all projects in solution
4. enable FSA for C#

Got the following AD0001 diagnostic for NRE in `Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer`

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	Newtonsoft.Json.Tests(net40)		1	Active	Analyzer 'Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Newtonsoft.Json.Tests
ISymbol: IExample (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NetFramework.Analyzers.SerializationRulesDiagnosticAnalyzer.SymbolAnalyzer.AnalyzeSymbol(SymbolAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteSymbolActionsCore>b__38_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

### LINKED ISSUE #1348: CA2229 (Implement serialization constructors) reported for delegate declaration
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

SerializationRulesDiagnosticAnalyzer

#### Repro steps

```
using System;

class A
{
    [Serializable]
    public delegate void B();
}
```

#### Expected behavior
No CA2229

#### Actual behavior
`warning CA2229: Add a constructor to B with the following signature: 'protected B(SerializationInfo info, StreamingContext context)'.`

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #1335
Fixes #1348

### CODE REVIEW

File: src/Microsoft.NetFramework.Analyzers/UnitTests/MarkISerializableTypesWithSerializableTests.cs [hunk 1]
```diff
@@ -199,6 +199,39 @@ End Class
...
+{
+    string Name { get; }
+}");
+
+            VerifyBasic(@"
+Imports System
+Imports System.Runtime.Serialization
+
+Class A
+	<Serializable> _
```
Comment (333fred) [inline src/Microsoft.NetFramework.Analyzers/UnitTests/MarkISerializableTypesWithSerializableTests.cs]: Tabs -> spaces for all the VB indentation added.

**Comment by mavasani** [comment]
test this please
