### PR TITLE
No CA1822 diagnostic if attribute implements NUnit's ITestBuilder

### LINKED ISSUE #4995: CA1822 (Mark member as static) fires for NUnit is not fully covered.
### Analyzer

**Diagnostic ID**: [CA1822](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822)

### Describe the improvement

This issue is reslove and closed at: https://github.com/dotnet/roslyn-analyzers/issues/1399
But I met this problem in Unity3D environment:
https://forum.unity.com/threads/is-there-a-way-suppress-the-ca1822-when-using-unitytestattribute.1084388/#post-6992105

### Describe suggestions on how to achieve the rule

Check the test not only by match the WellKnownTypes. If any attribute inherit from the [ITestBuilder](https://docs.nunit.org/articles/nunit/extending-nunit/ITestBuilder-Interface.html), this issue should be ignored.

### LINKED ISSUE #5110: CA1822 raises for custom TheoryAttribute
### Analyzer

**Diagnostic ID**: [CA1822](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822): `Mark members as static`

### Analyzer source

**VisualStudio**: Built-in CA analyzers, `dotnet --version 5.0.201`
```
Microsoft Visual Studio Professional 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional
```

### Describe the bug

I am using a custom `Theory` attribute based on the `Theory` attribute in the `NUnit` framework. I am not inheriting from the `Theory` attribute but reimplementing it with small changes. When I use the new attribute I get the CA1822 warning on my test methods. 

It appears to me like a duplicate of #2785 but I am not 100% certain since that issue was closed as being not reproducible almost 2 years ago.

### Steps To Reproduce

1. Add project set up as follows, e.g. `Testproject.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0"/>
  </ItemGroup>

</Project>
```

2. Add a test class set up as follows, e.g. `Tests.cs`
```c#
using System;
using NUnit.Framework;
using NUnit.Framework.Interfaces;
using NUnit.Framework.Internal.Builders;

namespace TestProject
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public class OtherTheoryAttribute : CombiningStrategyAttribute, ITestBuilder, IImplyFixture
    {
        public OtherTheoryAttribute() : base(
            new CombinatorialStrategy(),
            new ParameterDataProvider(new DatapointProvider(), new ParameterDataSourceProvider()))
        {
        }
    }

    public class Tests
    {
        [OtherTheory]
        public void Test1()
        {
            Assert.Pass();
        }
    }
}
```

### Expected behavior

No warning on the test method

### Actual behavior

Warning on the test method (see image below)
image

## Additional context

Nothing relevant that I am aware of.

### PR DESCRIPTION
**Pull request by louis-z**
Fixes #4995 
Fixes #5110

A method that has an attribute implementing `NUnit.Framework.Interfaces.ITestBuilder` will not receive a CA1822 diagnostic (mark method as static).

Some of those attributes are:
- `NUnit.Framework.TestCaseAttribute`
- `NUnit.Framework.TestCaseSourceAttribute`
- `NUnit.Framework.TheoryAttribute`

### CODE REVIEW

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 1]
```diff
@@ -600,6 +600,84 @@ End Namespace
...
+            }.RunAsync();
+
+            await new VerifyVB.Test
+            {
+                ReferenceAssemblies = referenceAssemblies,
+                TestState =
+                {
+                    Sources =
+                    {
+                        $@"
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:652]: Same here

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 2]
```diff
@@ -600,6 +600,84 @@ End Namespace
...
+            var referenceAssemblies = AdditionalMetadataReferences.DefaultWithNUnit;
+
+            await new VerifyCS.Test
+            {
+                ReferenceAssemblies = referenceAssemblies,
+                TestState =
+                {
+                    Sources =
+                    {
+                        $@"
```
[the remark this answers is not in the document]
Comment (louis-z) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs]: Nope. Fixed it.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 1 above)
Comment (louis-z) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs]: Fixed

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 3]
```diff
@@ -600,6 +600,84 @@ End Namespace
...
+                TestState =
+                {
+                    Sources =
+                    {
+                        @"
+public class Test
+{{
+    [CustomNUnit.MyTestBuilder]
+    public void Method1() {{}}
+}}
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:622]:
```suggestion
{
    [CustomNUnit.MyTestBuilder]
    public void Method1() {}
}
```

Comment (louis-z) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs]: Thanks @Youssef1313. Sorry I made the change too quickly... 🤦‍♂️

**Review by Youssef1313 — APPROVED** [review]

**Review by Evangelink — APPROVED** [review]

File: src/Utilities/Compiler/WellKnownTypeNames.cs [hunk 4]
```diff
@@ -83,14 +83,12 @@ internal static class WellKnownTypeNames
         public const string NewtonsoftJsonJsonSerializerSettings = "Newtonsoft.Json.JsonSerializerSettings";
         public const string NewtonsoftJsonTypeNameHandling = "Newtonsoft.Json.TypeNameHandling";
         public const string NUnitFrameworkAssert = "NUnit.Framework.Assert";
+        public const string NUnitFrameworkInterfacesITestBuilder = "NUnit.Framework.Interfaces.ITestBuilder";
         public const string NUnitFrameworkOneTimeSetUpAttribute = "NUnit.Framework.OneTimeSetUpAttribute";
         public const string NUnitFrameworkOneTimeTearDownAttribute = "NUnit.Framework.OneTimeTearDownAttribute";
         public const string NUnitFrameworkSetUpAttribute = "NUnit.Framework.SetUpAttribute";
         public const string NUnitFrameworkTearDownAttribute = "NUnit.Framework.TearDownAttribute";
         public const string NUnitFrameworkTestAttribute = "NUnit.Framework.TestAttribute";
-        public const string NUnitFrameworkTestCaseAttribute = "NUnit.Framework.TestCaseAttribute";
```
Comment (mavasani) [inline src/Utilities/Compiler/WellKnownTypeNames.cs:91]: Can you point to the documentation where it shows this attribute derives from `NUnit.Framework.Interfaces.ITestBuilder`?

Comment (Evangelink) [reply src/Utilities/Compiler/WellKnownTypeNames.cs:91]: https://docs.nunit.org/articles/nunit/extending-nunit/ITestBuilder-Interface.html

Comment (mavasani) [reply src/Utilities/Compiler/WellKnownTypeNames.cs:91]: Thanks!

**Review by mavasani — APPROVED** [review]
