### PR TITLE
Fix CA1801 false positive with positional records primary ctor

### LINKED ISSUE #4397: CA1801 false positive on record with property-targeting attribute on parameter
### Analyzer

**Diagnostic ID**: [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801): `Review unused parameters`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

```csharp
    public sealed record AuthProfileImageUrls(
        [property: JsonPropertyName("px_16x16")]
        Uri PixelSize16,
        [property: JsonPropertyName("px_50x50")]
        Uri PixelSize50,
        [property: JsonPropertyName("px_170x170")]
        Uri PixelSize170);
```

If **any** of the parameters have a `[property:` attribute, then CA1801 will fire on **all** parameters.

## Additional context

I wonder the relationship between CA1801 and IDE0060. IDE0060 used to fire a false positive on this, but get fixed later. Once IDExxxx analyzers are available in CLI builds, I will consider to use IDE0060 to replace CA1801.

### LINKED ISSUE #4462: CA1801 false positive on record parameter if any parameter has a default value
### Analyzer

**Diagnostic ID**: [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801): `Review unused parameters`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

If any parameter of a positional record has a default value, CA1801 is reported on all parameters.

### Steps To Reproduce

Write this code:

```csharp
public record Foo(string Name, int Age = 0);
```

### Expected behavior

No warning

### Actual behavior

CA1801 is reported on all parameters:

> Parameter Name of method .ctor is never used. Remove the parameter or use it in the method body.
> Parameter Age of method .ctor is never used. Remove the parameter or use it in the method body.

## Additional context

Looks very similar to #4397

### PR DESCRIPTION
**Pull request by Evangelink**
Replace #4476 and fix #4462 and fix #4397

### CODE REVIEW

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpReviewUnusedParametersAnalyzer.cs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+
+namespace Microsoft.CodeQuality.CSharp.Analyzers.Maintainability
+{
+    /// <summary>
+    /// CA1801: Review unused parameters
+    /// </summary>
+    [DiagnosticAnalyzer(LanguageNames.CSharp)]
+    public sealed class CSharpReviewUnusedParametersAnalyzer : ReviewUnusedParametersAnalyzer
+    {
+        private const SyntaxKind RecordDeclaration = (SyntaxKind)9063;
```
Comment (Evangelink) [inline src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpReviewUnusedParametersAnalyzer.cs:17]: I was lazy to create a new shared project for common elements for C# projects.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs [hunk 2]
```diff
@@ -1197,6 +1197,17 @@ public async Task CA1801_TopLevelStatements_NoDiagnostic()
...
         }
 
+        [Fact, WorkItem(4462, "https://github.com/dotnet/roslyn-analyzers/issues/4462")]
+        public async Task CA1801_CSharp_ImplicitRecord()
+        {
+            await new VerifyCS.Test
+            {
+                LanguageVersion = CodeAnalysis.CSharp.LanguageVersion.CSharp9,
+                ReferenceAssemblies = ReferenceAssemblies.Net.Net50,
+                TestCode = @"public record Person(string Name, int Age = 0);",
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs:1207]: You may want to add another test where the record has braces instead of a semi colon.

```csharp
"public record Person(string Name, int Age = 0) {}"
```

Comment (Youssef1313) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs:1207]: What about:

```csharp
public record Person(string Name, int Age = 0)
{
    public int Age { get; init; }
}
```

AFAIL, the parameter `Age` is unused for this case.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs [hunk 3]
```diff
@@ -241,5 +246,7 @@ private static void AddParameters(IMethodSymbol method, ConcurrentDictionary<IPa
 
             return true;
         }
+
+        protected abstract bool IsInlineRecord(IMethodSymbol methodSymbol);
```
Comment (Youssef1313) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs:250]: The official name for this kind of records is "Positional Record", and for the constructor that it gets generated by the compiler is called "Primary Constructor". So, I'd suggest renaming the method to "IsPrimaryConstructor" or something like that.

Comment (Evangelink) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs:250]: I was looking for the name but couldn't find it... Could you point me to the source please?

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs (hunk 2 above)
Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs:1207]: For the first example, do we agree that issue should be reported for the 2 arguments? Or is it the body of the record and not the record ctor?

Comment (Youssef1313) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs:1207]: > For the first example, do we agree that issue should be reported for the 2 arguments? Or is it the body of the record and not the record ctor?

The first example I mentioned (`"public record Person(string Name, int Age = 0) {}"` is identical to `"public record Person(string Name, int Age = 0);"`).

Both compile to the same code. I think the test will just pass without any further modifications, but just to confirm.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs (hunk 3 above)
Comment (Youssef1313) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParameters.cs:250]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/records#positional-record-members

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpReviewUnusedParametersAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/Maintainability/CSharpReviewUnusedParametersAnalyzer.cs:16]: That seems fine.

**Comment by mavasani** [comment]
@Evangelink There are still build failures. You will need to run `msbuild /t:pack` for both solutions at root of the repo to update the auto-generated documentation files.

**Review by mavasani — APPROVED** [review]

**Comment by Youssef1313** [comment]
@Evangelink I think you can target master and the build error should go away by itself.

File: eng/Versions.props [hunk 4]
```diff
@@ -2,7 +2,7 @@
   <PropertyGroup>
     <VersionPrefix>3.3.2</VersionPrefix>
     <PreReleaseVersionLabel>beta1</PreReleaseVersionLabel>
-    <NetAnalyzersVersionPrefix>5.0.1</NetAnalyzersVersionPrefix>
+    <NetAnalyzersVersionPrefix>6.0.0</NetAnalyzersVersionPrefix>
```
Comment (Evangelink) [inline eng/Versions.props:5]:
```suggestion
    <NetAnalyzersVersionPrefix>5.0.1</NetAnalyzersVersionPrefix>
```
