### PR TITLE
Do not raise CA1065 when in delegate

### LINKED ISSUE #6963: CA1065 raised inappropriately in lambda in static constructor
### Analyzer

**Diagnostic ID**: [CA1065](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1065): `Do not raise exceptions in unexpected locations`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: SDK 7.0.401

### Describe the bug

When writing a static constructor which constructs a lambda that throws an exception (not inside the constructor itself), CA1065 is inappropriately triggered.

### Steps To Reproduce

Given the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AnalysisLevel>latest-All</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

</Project>
```

and source:

```csharp
#pragma warning disable CA1810  // Disabled because it's orthogonal to this bug

using System;

namespace Empty;

public class ShouldViolate
{
    static ShouldViolate()
    {
        throw new DivideByZeroException();  // line 11
    }
}

public class ShouldNotViolate
{
    static readonly Action a;

    static ShouldNotViolate()
    {
        a = () => throw new DivideByZeroException();  // line 21
    }
}
```

### Expected behavior

Only `ShouldViolate` should be flagged.

### Actual behavior

Both classes are flagged:

```
MSBuild version 17.7.3+8ec440e68 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Dev\repro\empty\Sample.cs(11,9): warning CA1065: .cctor creates an exception of type DivideByZeroException. Exceptions should not be raised in this type of method. If thisexception instance might be raised, change this method's logic so it no longer raises an exception. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1065) [C:\Dev\repro\empty\empty.csproj]
C:\Dev\repro\empty\Sample.cs(21,19): warning CA1065: .cctor creates an exception of type DivideByZeroException. Exceptions should not be raised in this type of method. If this exception instance might be raised, change this method's logic so it no longer raises an exception. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1065) [C:\Dev\repro\empty\empty.csproj]
```

### PR DESCRIPTION
**Pull request by CollinAlpert**
Fixes #6963

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs [hunk 1]
```diff
@@ -109,6 +115,22 @@ public override void Initialize(AnalysisContext context)
             });
         }
 
+        private static bool ThrowOperationOccursInDelegate(IThrowOperation throwOperation)
```
Comment (mavasani) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs:118]: Couple of suggestions:
- Should we consider using the below helper instead? https://github.com/dotnet/roslyn-analyzers/blob/5a5b8c68f488b4a8c7037c4b78008f1545e3344b/src/Utilities/Compiler/Extensions/IOperationExtensions.cs#L1121
- If not, consider using the below extension method instead of defining this new method: https://github.com/dotnet/roslyn-analyzers/blob/5a5b8c68f488b4a8c7037c4b78008f1545e3344b/src/Utilities/Compiler/Extensions/IOperationExtensions.cs#L245

Comment (CollinAlpert) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs]: That's a good tip, thanks.

**Review by mavasani — APPROVED** [review]
