### PR TITLE
Fixes for CA1801 (ReviewUnusedParameters)

### LINKED ISSUE #1359: Do not fire CA1801 on lone parameter of struct constructor
```
public struct S
{
  public S(bool ignored)
  { }
  public S(...)
  { }
}
```

Removing unused parameter `ignored` causes C# compiler error that structs cannot contain explicit parameter-less constructors.

### LINKED ISSUE #2465: CA1801 shouldn't fire for generic functions with inferred-type parameters
#### Analyzer package

Example: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

Functions like the Newtonsoft "DeserializeAnonymousType" must use a generic type paramater that allows the compiler to infer anonymous types (as there's no other way of instantiating a generic function with an anonymous type).  But this parameter by design should not be actually used by the function, so it seems unnecessary to have to suppress CA1801.
E.g.

```
public static T DeserializeAnonymousType<T>(string value, T _)
{
   /* ... */
}

```
Perhaps if it's a generically typed parameter with a name of _ it should just be ignored automatically?

Of course it would be nicer if C# had a better way of doing this (e.g. being able to use `typeof(new { ... })` for specifying the generic type for such functions).

### LINKED ISSUE #2466: CA1801 doesn't fire for local functions
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

```
void Foo(string data)
{
    T Deserialize<T>(string val, T _) { return this.Deserialize<T>(val); }
    var myObj = Deserialize(data, new { prop1 = "", prop2 = "" });
    Print(myObj.prop1);
}

```
Used this as a workaround to the fact that you can't easily call template functions with anonymous types, but as part of doing so noticed that the CA1801 doesn't fire at all for local functions. In this case I wouldn't want it to, but in this case:

```
void Foo(string data)
{
   int Bar(string d, string important) { return d.Length; }
   Print(Bar(data, "this matters"));
}
```

I would want it to (but it doesn't).

### LINKED ISSUE #2589: CA1801 in Azure Functions where attribute is needed, but parameter is not
I'm not sure this a bug, or an odd use case, but I'm interested in workarounds if it's not.

#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.3 (Latest)

#### Diagnostic ID

[CA1801](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters?view=vs-2019)

#### Repro steps

1. Create an Azure Function defined as

```csharp
[FunctionName(nameof(DoSomethingFunction))]
public async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "delete", Route = "something/{id:int}")] HttpRequest _, int id)
{
    // Do something based on `id`
    return new OkResult();
}
```

#### Expected behavior

No warning is generated. The parameter has to be there because the attribute needs to be there.

#### Actual behavior

Warning is generated.

### LINKED ISSUE #2593: CA1801 is reported for event-handler method
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.3

#### Diagnostic ID

[CA1801](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters)

#### Repro steps

1. Create a new UWP project
2. Add button to MainPage.xaml
3. Add event handler for button click
4. Build project and change show issue generated to Build Only

Example:

**XAML**

```csharp
<Page
    x:Class="App.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Button Click="Button_Click"/>
    </Grid>
</Page>
```

**CS**

```csharp
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
        }
        private void Button_Click(object sender, RoutedEventArgs e)
        {
        }
    }
```

#### Expected behavior
CA1801 is not reported as the method is event handler.

#### Actual behavior
Similar to #2458, CA1801 is being reported. Although the sub type is not EventArgs, the intention is the same and should be ignored. It is also impossible to change RoutedEventArgs to EventArgs to mitigate this issue.

### PR DESCRIPTION
**Pull request by mavasani**
1. https://github.com/dotnet/roslyn-analyzers/commit/97d6b44dc23aad5413e99181294e2fcb8ef1b416: Bail out on discard symbol names.
Fixes #2589
Fixes #2593
Fixes #2465
Fixes #1359

2. https://github.com/dotnet/roslyn-analyzers/commit/9255c80106d85526c03dc7aad524fd6c7d3a6215: Analyze local function parameters.
Fixes #2466

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs [hunk 1]
```diff
@@ -85,65 +85,19 @@ public override void Initialize(AnalysisContext context)
                 compilationStartContext.RegisterOperationBlockStartAction(startOperationBlockContext =>
                 {
                     // We only care about methods.
-                    if (startOperationBlockContext.OwningSymbol.Kind != SymbolKind.Method)
+                    if (!(startOperationBlockContext.OwningSymbol is IMethodSymbol method))
                     {
                         return;
                     }
 
-                    // We only care about methods with parameters.
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: The code here just refactored into a separate static method

**Comment by mavasani** [comment]
Thanks @dotpaul
