### PR TITLE
#5021 CA1065 Enhancement: Report on more operators

### LINKED ISSUE #5021: CA1065 Enhancement: Report on more operators
### Analyzer

**Diagnostic ID**: [CA1065](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1065)

### Describe the improvement

Currently, the rule reports `==` and `!=` operators that throw exceptions. I think it makes sense to extend that to `>`, `<`, `>=`, and `<=`.

### PR DESCRIPTION
**Pull request by NewellClark**
Fix #5021

### CODE REVIEW

**Review by mavasani — APPROVED** [review]
Thanks @NewellClark!

Can you please retarget to `main` or `release\6.0.1xx` branch?

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs [hunk 1]
```diff
@@ -621,6 +621,67 @@ End Class
                         GetBasicNoExceptionsResultAt(9, 9, "op_Inequality", "Exception"));
         }
 
+        [Fact]
+        public async Task CSharpComparisonOperatorWithExceptions()
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs:625]: Can you add a work item here?

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs [hunk 2]
```diff
@@ -329,6 +332,21 @@ private static bool IsEqualityOperator(IMethodSymbol method, Compilation compila
...
+
+            return method.Name switch
+            {
+                WellKnownMemberNames.LessThanOperatorName
+                or WellKnownMemberNames.GreaterThanOperatorName
+                or WellKnownMemberNames.LessThanOrEqualOperatorName
+                or WellKnownMemberNames.GreaterThanOrEqualOperatorName => true,
+                _ => false,
+            };
+        }
```
Comment (Youssef1313) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs:348]: nit: Per spec, `==` and `!=` are also comparison operators. So you might want to consider merging `IsComparisonOperatror` and `IsEqualityOperator` into one method `IsComparisonOperator`.

https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#integer-comparison-operators

image

Feel free if you don't want to do that since @mavasani has already approved.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs (hunk 1 above)
Comment (NewellClark) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocationsTests.cs]: Fixed.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs (hunk 2 above)
Comment (NewellClark) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs]: I went ahead and fixed it. It's a simple change.
