### PR TITLE
Fix 'Compare symbols correctly' false positive with custom comparers

### LINKED ISSUE #5715: False positive for RS1024 when using ToDictionary(...)
### Analyzer

Diagnostic ID: [RS1024](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/rs1024): `Compare symbols correctly`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 6 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.100](https://dotnet.microsoft.com/download/dotnet/6.0)

_AND_

**NuGet Package**: [Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers)

**Version**: 3.3.3 (Latest)

### Describe the bug

When using the `Enumerable.ToDictionary(...)` extension method on something like an `IEnumerable<ITypeSymbol>`, it is not possible (from what I can tell) to satisfy the analyzer.

### Steps To Reproduce

Consider the following example code:

```csharp
IEnumerable<ITypeSymbol> symbols = GetTypeSymbolsFromSomewhere();
IDictionary<ITypeSymbol, string> symbolNameMap = symbols.ToDictionary(s => s, s => s.ToDisplayString());
# ^ Raises warning | RS1024: Use 'SymbolEqualityComparer' when comparing symbols
```

However, you can't fix the warning by using `SymbolEqualityComparer.Default` because it causes the wrong type to be returned. In this case an `IDictionary<ISymbol, string>` instead of an `<IDictionary<ITypeSymbol, string>`.

```csharp
IEnumerable<ITypeSymbol> symbols = GetTypeSymbolsFromSomewhere();
IDictionary<ITypeSymbol, string> symbolNameMap = symbols.ToDictionary(s => s, s => s.ToDisplayString(), SymbolEqualityComparer.Default);
# ^ Raises error | CS0266: Cannot implicitly convert type 
#    'System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.ISymbol, string>' to
#    'System.Collections.Generic.IDictionary<Microsoft.CodeAnalysis.ITypeSymbol, string>'.
#    An explicit conversion exists (are you missing a cast?)
```

So, I figured I'd create an implementation of an `IEqualityComparer<ITypeSymbol?>`, since one doesn't already exist, using something like the following:

```csharp
internal class TypeSymbolEqualityComparer : IEqualityComparer<ITypeSymbol?>
{
    public static readonly TypeSymbolEqualityComparer Default = new(SymbolEqualityComparer.Default);

    private readonly IEqualityComparer<ITypeSymbol?> symbolComparer;

    private TypeSymbolEqualityComparer(IEqualityComparer<ITypeSymbol?> symbolComparer)
        => this.symbolComparer = symbolComparer ?? throw new ArgumentNullException(nameof(symbolComparer));

    public bool Equals(ITypeSymbol? x, ITypeSymbol? y)
        => this.symbolComparer.Equals(x, y);

    public int GetHashCode([DisallowNull] ITypeSymbol? obj)
        => this.symbolComparer.GetHashCode(obj);
}
```

Then, back in our code, we'd write the following:

```csharp
IEnumerable<ITypeSymbol> symbols = GetTypeSymbolsFromSomewhere();
IDictionary<ITypeSymbol, string> symbolNameMap = symbols.ToDictionary(s => s, s => s.ToDisplayString(), TypeSymbolEqualityComparer.Default);
# ^ Raises warning | RS1024: Use 'SymbolEqualityComparer' when comparing symbols
```

But again, the analyzer isn't satisfied.

### Expected behavior

I can cleanly compare symbols properly using the `Enumerable.ToDictionary(...)` extension without getting an RS1024 warning.

### Actual behavior

I can't cleanly compare symbols without getting the RS1024 warning, so I disable the warning.

### Additional information

The same appears to be true for other extension methods like `Enumerable.Union(...)`.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #5715

### CODE REVIEW

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 1]
```diff
@@ -81,20 +81,22 @@ public override void Initialize(AnalysisContext context)
...
                 var systemHashCode = compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemHashCode);
+                var iEqualityComparer = compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemCollectionsGenericIEqualityComparer1);
 
                 context.RegisterOperationAction(
-                    context => HandleInvocationOperation(in context, symbolType, symbolEqualityComparerType, equalityComparerMethods, systemHashCode),
+                    context => HandleInvocationOperation(in context, symbolType, symbolEqualityComparerType, equalityComparerMethods, systemHashCode, iEqualityComparer),
                     OperationKind.Invocation);
 
-                if (symbolEqualityComparerType != null)
+
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:90]:
```suggestion
```

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 2]
```diff
@@ -81,20 +81,21 @@ public override void Initialize(AnalysisContext context)
...
                 var systemHashCode = compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemHashCode);
+                var iEqualityComparer = compilation.GetOrCreateTypeByMetadataName(WellKnownTypeNames.SystemCollectionsGenericIEqualityComparer1);
 
                 context.RegisterOperationAction(
-                    context => HandleInvocationOperation(in context, symbolType, symbolEqualityComparerType, equalityComparerMethods, systemHashCode),
+                    context => HandleInvocationOperation(in context, symbolType, symbolEqualityComparerType, equalityComparerMethods, systemHashCode, iEqualityComparer),
                     OperationKind.Invocation);
 
-                if (symbolEqualityComparerType != null)
+                if (symbolEqualityComparerType is not null && iEqualityComparer is not null)
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:90]: I'm still keeping the `symbolEqualityComparerType` null check so that we don't report diagnostics when `SymbolEqualityComparer` doesn't exist, even if `IEqualityComparer` can be implemented.

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 3]
```diff
@@ -230,23 +232,23 @@ static bool IsBehavingOnSymbolType(IMethodSymbol? method, INamedTypeSymbol symbo
...
+             INamedTypeSymbol iEqualityComparerType, ImmutableHashSet<INamedTypeSymbol> collectionTypes)
         {
             var objectCreation = (IObjectCreationOperation)context.Operation;
 
             if (objectCreation.Type is INamedTypeSymbol createdType &&
                 collectionTypes.Contains(createdType.OriginalDefinition) &&
                 !createdType.TypeArguments.IsEmpty &&
                 IsSymbolType(createdType.TypeArguments[0], symbolType) &&
-                !objectCreation.Arguments.Any(arg => IsSymbolType(arg.Value, symbolEqualityComparerType)))
+                !objectCreation.Arguments.Any(arg => IsSymbolType(arg.Value, iEqualityComparerType)))
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:243]: Now we look for any `IEqualityComparer<T>` parameter, not necessarily `SymbolEqualityComparer`.

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 4]
```diff
@@ -1248,9 +1248,156 @@ public int GetHashCode(object o1, object o2)
...
+                FixedCode = code,
+                ReferenceAssemblies = CreateNetCoreReferenceAssemblies(),
+
+            }.RunAsync();
+        }
+
         private static ReferenceAssemblies CreateNetCoreReferenceAssemblies()
             => ReferenceAssemblies.NetCore.NetCoreApp31.AddPackages(ImmutableArray.Create(
-                new PackageIdentity("Microsoft.CodeAnalysis", "3.0.0"),
+                new PackageIdentity("Microsoft.CodeAnalysis", "4.0.1"),
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1400]: `SymbolEqualityComparer` didn't exist in 3.0.0.

**Comment by Youssef1313** [comment]
@Evangelink In case you want to review

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs (hunk 2 above)
Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:90]: As you are not using the type symbol per say, I would change the first part of the if to use `UseSymbolEqualityComparer` helper.

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 5]
```diff
@@ -1248,9 +1248,156 @@ public int GetHashCode(object o1, object o2)
             }.RunAsync();
         }
 
+        [Fact]
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1251]: Could you add the various vbnet parts?

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 6]
```diff
@@ -1248,9 +1248,156 @@ public int GetHashCode(object o1, object o2)
...
+        public async Task RS1024_CustomComparer()
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1252]:
```suggestion
        public async Task RS1024_CustomComparer_Instance_Is_Interface()
```

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 7]
```diff
@@ -1248,9 +1248,156 @@ public int GetHashCode(object o1, object o2)
...
+            {
+                TestCode = code,
+                FixedCode = code,
+                ReferenceAssemblies = CreateNetCoreReferenceAssemblies(),
+
+            }.RunAsync();
+        }
+
+        [Fact]
+        public async Task RS1024_CustomComparer2()
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1288]:
```suggestion
        public async Task RS1024_CustomComparer_Instance_Is_Type()
```

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 8]
```diff
@@ -1248,9 +1248,156 @@ public int GetHashCode(object o1, object o2)
...
+            var code = @"
+using System.Collections.Generic;
+using System.Linq;
+using Microsoft.CodeAnalysis;
+
+public class C
+{
+    public void M(IEnumerable<ITypeSymbol> symbols)
+    {
+        _ = symbols.ToDictionary(s => s, s => s.ToDisplayString(), SymbolNameComparer.Instance);
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1335]: I would move this line (and the method arg) to the 1st test. We could even consider copying all the methods declared in the test `CollectionMethodsKnownToRequireComparer_DiagnosticAsync`.

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs (hunk 6 above)
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1252]: I don't know when this was done but it seems that all tests were renamed to follow the `Async` suffix pattern, could you please update your tests?

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 9]
```diff
@@ -1248,9 +1248,156 @@ public int GetHashCode(object o1, object o2)
...
```
Comment (Evangelink) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1373]: Same remark about moving this to test 2 this time.

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs (hunk 5 above)
Comment (Youssef1313) [reply src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1251]: Will fix, probably in few days :(

Feel free to re-ping me if I forgot.

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs (hunk 6 above)
Comment (Youssef1313) [reply src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs]: That looks weird. We shouldn't follow `Async` suffix for tests.

Comment (Evangelink) [reply src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs]: I agree, don't know why it was done.

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@Youssef1313 @Evangelink - do we need any more iterations on this PR?

**Comment by Evangelink** [comment]
@mavasani I think that's ok.
