### PR TITLE
CA1024: Do not report on implicit interface implementation

### LINKED ISSUE #1551: CA1024 False-positive when class implements IXmlSerializable
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

CA1024: Use properties where appropriate

#### Repro steps

Create a class that implements IXmlSerializable:

    public class Example : IXmlSerializable
    {
        public XmlSchema GetSchema()
        {
            return null;
        }

        public void ReadXml(XmlReader reader) {...}

        public void WriteXml(XmlWriter writer) {...}
    }

#### Expected behavior

No warning is shown for GetSchema(). 

#### Actual behavior

A warning is shown for GetSchema().

When the method declaration comes from an interface, maybe it would make sense to show this warning only in the interface and never in the implementing classes. This would solve this issue and potentially similar issues. If user has a reason to use a method instead of a property, he would just need to suppress the warning once in the interface and not in all implementations.

### PR DESCRIPTION
**Pull request by Evangelink**
- Add a test to show that no issue is reported on explicit interface.

- Update the rule (and add a test) to stop reporting on implicit interface implementation.

- Do nothing regarding `override` as it is already handled.

Fix #1551

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs [hunk 1]
```diff
@@ -4,12 +4,6 @@
 using Microsoft.CodeAnalysis.Testing;
 using Test.Utilities;
 using Xunit;
-using VerifyCS = Test.Utilities.CSharpCodeFixVerifier<
```
Comment (Evangelink) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs]: Unused

Comment (sharwell) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/UsePropertiesWhereAppropriateTests.cs]: These should not be removed. They are only unused because the tests are written using the legacy test framework and still needed to be updated to use these. I added them to all the tests so it's easier for users to aid in this conversion (as separate pull requests).

**Comment by Evangelink** [comment]
My bad! I will revert the remove

**Comment by Evangelink** [comment]
@sharwell anything left to do on my side here?

**Comment by sharwell** [comment]
I was waiting for @mavasani to second review and merge

**Comment by RobSwDev** [comment]
When will this fix be released? I have Microsoft.CodeQuality.Analyzers 2.9.8, and it still shows the warning. 
Looking at the il code, I see

`if (val != null && ... && !(val.get_Name() == "GetEnumerator"))`

i.e. the last check is against GetEnumerator, and there's no check for `methodSymbol.IsImplementationOfAnyImplicitInterfaceMember()`

**Comment by Evangelink** [comment]
@RobSwDev AFAIK there will be a new release coming up soon. Tagging @mavasani
