### PR TITLE
Do not report CA1812 (Make static) on public APIs for web projects

### LINKED ISSUE #3835: Disable CA1822 on ASP.Net Startup Classes etc
Classes like `ConfigureServices` are being marked with `CA1822` as a fix. If the method is static it will not work unless I am missing something.

This also occurs in controller methods which don't access any instance data. (Again won't work if you apply the fix)

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #3835

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs [hunk 1]
```diff
@@ -308,24 +319,6 @@ void Add(INamedTypeSymbol? symbol)
             return builder?.ToImmutable() ?? ImmutableArray<INamedTypeSymbol>.Empty;
         }
 
-        private static bool IsSkippedMethod(IMethodSymbol methodSymbol, WellKnownTypeProvider wellKnownTypeProvider)
```
Comment (Evangelink) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:311]: Is there any need to keep all the web attribute exclusions (see https://github.com/dotnet/roslyn-analyzers/pull/3875/files#diff-b71c5f4c8942242dec4740ebf6efda72R282-R298) now that we don't report on public APIs for web projects?

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 2]
```diff
@@ -1016,9 +1016,18 @@ public class C : System.Web.HttpApplication
     // The following controller methods can't be made static
     protected void Application_Start() { }
     protected void Application_End() { }
-}");
+}";
 
-            await VerifyVB.VerifyAnalyzerAsync(@"
+            const string editorConfigText = "build_property.UsingMicrosoftNETSdkWeb = true";
+            var csTest = new VerifyCS.Test()
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1022]: Any reason you have split the test and the `RunAsync`? You could write something like

```csharp
await new VerifyCS.Test
{
	TestCode = csSource,
	AnalyzerConfigDocument = editorConfigText,
}.RunAsync();
```

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 3]
```diff
@@ -1016,9 +1016,18 @@ public class C : System.Web.HttpApplication
...
+            {
+                TestCode = csSource,
+                AnalyzerConfigDocument = editorConfigText
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1025]: [minor] @sharwell likes to have the trailing comma here :)

```suggestion
                AnalyzerConfigDocument = editorConfigText,
```

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 2 above)
Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1022]: In case you apply this comment, note that it applies to the various tests you have changed.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 3 above)
Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1025]: If you decide to apply this comment, note that you will have to do the change for the various tests you have changed.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs [hunk 4]
```diff
@@ -1016,9 +1016,18 @@ public class C : System.Web.HttpApplication
     // The following controller methods can't be made static
     protected void Application_Start() { }
     protected void Application_End() { }
-}");
+}";
 
-            await VerifyVB.VerifyAnalyzerAsync(@"
+            const string editorConfigText = "build_property.UsingMicrosoftNETSdkWeb = true";
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1021]: Just to confirm I got things right, we don't expect user to set this in their `.editorconfig` file? This is a msbuild property that is present for web apps, right?

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs [hunk 5]
```diff
@@ -191,7 +194,15 @@ private static bool ShouldAnalyze(IMethodSymbol methodSymbol, WellKnownTypeProvi
...
-            if (IsSkippedMethod(methodSymbol, wellKnownTypeProvider))
+            // Do not analyze constructors and finalizers.
+            if (methodSymbol.IsConstructor() || methodSymbol.IsFinalizer())
+            {
+                return false;
+            }
+
+            // Do not analyze public APIs for web projects
+            // See https://github.com/dotnet/roslyn-analyzers/issues/3835 for details.
+            if (isWebProject && methodSymbol.IsExternallyVisible())
```
Comment (Evangelink) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:205]: Shall we really skip `protected` members? I don't know exactly if they expect the member to be `public` for the reflection or if `protected` is ok.

File: src/Utilities/Compiler/Extensions/CompilationExtensions.cs [hunk 6]
```diff
@@ -59,5 +61,15 @@ internal static bool TargetsDotNetFramework(this Compilation compilation)
...
         }
+
+        /// <summary>
+        /// Gets a value indicating whether the project of the compilation is a Web SDK project,
+        /// based on MSBuild property <see cref="MSBuildPropertyOptionNames.UsingMicrosoftNETSdkWeb"/>.
+        /// </summary>
+        internal static bool IsWebProject(this Compilation compilation, AnalyzerOptions options, CancellationToken cancellationToken)
+        {
+            var usingMicrosoftNETSdkWeb = options.GetMSBuildPropertyValue(MSBuildPropertyOptionNames.UsingMicrosoftNETSdkWeb, compilation, cancellationToken);
+            return usingMicrosoftNETSdkWeb != null && bool.TryParse(usingMicrosoftNETSdkWeb, out var result) && result;
```
Comment (Evangelink) [inline src/Utilities/Compiler/Extensions/CompilationExtensions.cs:72]: Do you need to potentially trim the string option before doing a `TryParse`? Also as you are then checking the fact this is true, isn't it better to replace the full line with `string.Equals(usingMicrosoftNETSdkWeb?.Trim(), "true", StringComparison.OrdinalIgnoreCase)`?

File: src/Utilities/Compiler/Extensions/CompilationExtensions.cs [hunk 7]
```diff
@@ -59,5 +61,15 @@ internal static bool TargetsDotNetFramework(this Compilation compilation)
...
             return false;
         }
+
+        /// <summary>
+        /// Gets a value indicating whether the project of the compilation is a Web SDK project,
+        /// based on MSBuild property <see cref="MSBuildPropertyOptionNames.UsingMicrosoftNETSdkWeb"/>.
+        /// </summary>
+        internal static bool IsWebProject(this Compilation compilation, AnalyzerOptions options, CancellationToken cancellationToken)
+        {
+            var usingMicrosoftNETSdkWeb = options.GetMSBuildPropertyValue(MSBuildPropertyOptionNames.UsingMicrosoftNETSdkWeb, compilation, cancellationToken);
```
Comment (Evangelink) [inline src/Utilities/Compiler/Extensions/CompilationExtensions.cs:71]: [cosmetic] the variable name reads to me as if it's a boolean while it's a string, maybe `usingMicrosoftNETSdkWebPropertyValue` is clearer (not sure because it's really long...).

File: src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs [hunk 8]
```diff
@@ -88,13 +89,23 @@ public bool TryGetOptionValue<T>(string optionName, OptionKind kind, DiagnosticD
...
-                TryGetGeneralOptionValue(optionKeyPrefix, out optionValue))
+
+            T optionValue;
+            if (rule != null)
+            {
+                if (TryGetSpecificOptionValue(rule.Id, optionKeyPrefix, out optionValue) ||
+                    TryGetSpecificOptionValue(rule.Category, optionKeyPrefix, out optionValue) ||
+                    TryGetAnySpecificOptionValue(rule.CustomTags, optionKeyPrefix, out optionValue))
+                {
+
```
Comment (Evangelink) [inline src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs:103]:
```suggestion
```

File: src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs [hunk 9]
```diff
@@ -88,13 +89,23 @@ public bool TryGetOptionValue<T>(string optionName, OptionKind kind, DiagnosticD
...
-        private (bool found, object? value) ComputeOptionValue<T>(string optionName, OptionKind kind, DiagnosticDescriptor rule, TryParseValue<T> tryParseValue)
+        private (bool found, object? value) ComputeOptionValue<T>(string optionName, OptionKind kind, DiagnosticDescriptor? rule, TryParseValue<T> tryParseValue)
         {
             var optionKeyPrefix = MapOptionKindToKeyPrefix(kind);
-            if (TryGetSpecificOptionValue(rule.Id, optionKeyPrefix, out var optionValue) ||
-                TryGetSpecificOptionValue(rule.Category, optionKeyPrefix, out optionValue) ||
-                TryGetAnySpecificOptionValue(rule.CustomTags, optionKeyPrefix, out optionValue) ||
-                TryGetGeneralOptionValue(optionKeyPrefix, out optionValue))
+
+            T optionValue;
```
Comment (Evangelink) [inline src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs:96]: Out of curiosity, is it to reduce allocation that you declare the variable before rather than doing `out var`?

File: src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs [hunk 10]
```diff
@@ -88,13 +89,23 @@ public bool TryGetOptionValue<T>(string optionName, OptionKind kind, DiagnosticD
...
+            if (rule != null)
+            {
+                if (TryGetSpecificOptionValue(rule.Id, optionKeyPrefix, out optionValue) ||
```
Comment (Evangelink) [inline src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs:99]: [suggestion] could be merged with outer if.

File: src/Utilities/Compiler/Extensions/CompilationExtensions.cs (hunk 7 above)
Comment (Evangelink) [inline src/Utilities/Compiler/Extensions/CompilationExtensions.cs:71]: Is this property valid only for aspnet core or also regular aspnet? If it's valid only for aspnet core, do we really want to get rid of the old exclusions? That would mean raising FPs for "old" projects.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 4 above)
Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1021]: Yes, users do not have to do anything.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 5 above)
Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:205]: I am not sure, but I made is as conservative as possible, given protected members in public types are public APIs.

**Comment by Evangelink** [comment]
Without forcing you to add too many tests, it might be nice to add a couple of tests for some of the cases mentioned here https://github.com/dotnet/roslyn-analyzers/issues/3835#issuecomment-657591877

File: src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs (hunk 9 above)
Comment (mavasani) [reply src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs:96]: No, the var is again needed in a separate if check below, hence it must be scoped to the whole method.

**Comment by mavasani** [comment]
> Without forcing you to add too many tests, it might be nice to add a couple of tests for some of the cases mentioned here

I am not sure if that provides any valuable test coverage addition. The analyzer itself is not detecting any special patterns, except for bailing out on externally visible types when a certain option is provided - basically if you set that option manually in .editorconfig, it will skip externally visible types for that project. It is not checking for any semantics around the symbols or compilation, so there will not be real value add.

File: src/Utilities/Compiler/Extensions/CompilationExtensions.cs (hunk 7 above)
Comment (mavasani) [reply src/Utilities/Compiler/Extensions/CompilationExtensions.cs:71]: It will be valid for all SDK based aspnet projects. @pranavkm Is there any MSBuild property that is set for regular aspnet projects that we can use?

**Comment by Evangelink** [comment]
It just provides a minimal safety-net in case we change something in the rule later on but I agree value is minimal here. It could be valuable to have some "integration" test though (but that's not in the scope of this PR).

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 5 above)
Comment (Evangelink) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:205]: It seems that `Application_Start` could be `protected` so it's mandatory anyways.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 1 above)
Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:311]: Hmm @pranavkm for advice. Can these web attributes be applied on non-public methods? Unless we are sure, I'd prefer to keep the attribute based exclusions.

File: src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs (hunk 10 above)
Comment (mavasani) [reply src/Utilities/Compiler/Options/AbstractCategorizedAnalyzerConfigOptions.cs:99]: That required adding parentheses around the second checks and was making the code clumsy :-)

**Comment by mavasani** [comment]
>  It could be valuable to have some "integration" test though (but that's not in the scope of this PR).

Yes, that would be valuable, and agree out of the scope of this PR.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 2 above)
Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1022]: Awaiting an object creation with initializer with an async method invocation seems too chatty to me :-). I prefer to keep object creation with initializer as its own statement.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 3 above)
Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1025]: Sure, will change.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs (hunk 2 above)
Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStaticTests.cs:1022]: Seems like other tests in this file follow the pattern you suggested. I will switch the pattern in new tests to make it consistent.

File: src/Utilities/Compiler/Extensions/CompilationExtensions.cs (hunk 7 above)
Comment (pranavkm) [reply src/Utilities/Compiler/Extensions/CompilationExtensions.cs]: > Is there any MSBuild property that is set for non-SDK based aspnet projects that we can use?

Not that I know of.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 1 above)
Comment (pranavkm) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:311]: The link is bugged (I can't see where it's meant to go), but in general MVC (5.0 and Core) will only discover public types and methods.

File: src/Utilities/Compiler/Extensions/CompilationExtensions.cs (hunk 7 above)
Comment (mavasani) [reply src/Utilities/Compiler/Extensions/CompilationExtensions.cs]: I looked around and the only way I could identify is by looking at `ProjectTypeGuids` property.

```csharp
public const string WebAppProjectGuidString = "349C5851-65DF-11DA-9384-00065B846F21";
public const string WebSiteProjectGuidString = "E24C65DC-7377-472B-9ABA-BC803B73C61A";
```

I'll can add these property value checks unless we find a better way.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 1 above)
Comment (Evangelink) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:311]: @pranavkm Here is the link on master: https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs#L270-L287

**Comment by mavasani** [comment]
@Evangelink I have added support for non-SDK projects and also added support for `api_surface` option for the analyzer. I have left the attribute checks as I am not sure if they are intended only for public API surface or not.

**Comment by mavasani** [comment]
@Evangelink would you mind reviewing the latest commit when you get time? Thanks!

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs (hunk 1 above)
Comment (pranavkm) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:311]: Those are required to be on public types or methods. Feel free to remove these exclusions.
