### PR TITLE
CA1068 permits multiple CancellationToken at end of parameter list

### LINKED ISSUE #1816: Multiple CancellationTokens as the last parameters of a function trigger CA1068
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Diagnostic ID

CA1068: Method Tgstation.Server.Host.Core.IJobManager.WaitForJobCompletion(Tgstation.Server.Host.Models.Job, Tgstation.Server.Host.Models.User, System.Threading.CancellationToken, System.Threading.CancellationToken)' should take CancellationToken as the last parameter

#### Repro steps

Function definition:
```c#
Task WaitForJobCompletion(Job job, User canceller, CancellationToken jobCancellationToken, CancellationToken cancellationToken);
```

#### Expected behavior

The warning should not appear since there is a `CancellationToken` as the last parameter and each token has a different meaning

#### Actual behavior

The warning appears

### PR DESCRIPTION
**Pull request by drewnoakes**
Fixes #1816.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs [hunk 1]
```diff
@@ -191,6 +191,22 @@ public static void M1(this CancellationToken p1, object p2)
             VerifyCSharp(test);
         }
 
+        [Fact, WorkItem(1816, "https://github.com/dotnet/roslyn-analyzers/issues/1816")]
+        public void NoDiagnosticWhenMultipleAtEndOfParameterList()
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs]: Can we add a unit test to ensure `public static void M1(CancellationToken token1, object p1, CancellationToken token2) { }` is flagged?

Comment (drewnoakes) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs]: Sure, done in 0f16ce222a2e5690538c29f38e009d3e8572fcef.
