### PR TITLE
Make ca1801 aware of methods that just throw NotImplementedException

### LINKED ISSUE #1357: CA1801 (unused parameter) fired for obsolete property setter with stub implementation
This rule files for http://source.roslyn.io/#Microsoft.CodeAnalysis/Compilation/CompilationOptions.cs,245

```
        /// <summary>
        /// A set of strings designating experimental compiler features that are to be enabled.
        /// </summary>
        [Obsolete]
        protected internal ImmutableArray<string> Features
        {
            get
            {
                throw new NotImplementedException();
            }
            protected set
            {
                throw new NotImplementedException();
            }
        }
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1801	Parameter value of method set_Features is never used. Remove the parameter or use it in the method body.	CodeAnalysis	c:\roslyn\src\Compilers\Core\Portable\Compilation\CompilationOptions.cs	245	Active
```

Should we avoid flagging this case?

### PR DESCRIPTION
**Pull request by 333fred**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/1220
Fixes #1357

This updates CA1801 to be aware of method bodies that are only `throw NotImplementedException()`, and makes sure that diagnostics aren't registered for them.

### CODE REVIEW

**Comment by 333fred** [comment]
@sharwell could you please update your review?

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs [hunk 1]
```diff
@@ -195,6 +195,47 @@ public void AnalyzeOperation(OperationAnalysisContext context)
...
+
+                    var methodBlock = (IBlockOperation)context.OperationBlocks[0];
+                    if (IsSingleStatementBody(methodBlock))
+                    {
+                        var innerOperation = methodBlock.Operations.First();
+
+                        // Because of https://github.com/dotnet/roslyn/issues/23152, there can be an expression-statement
+                        // wrapping expression-bodied throw operations. Compensate by unwrapping if necessary.
+                        if (innerOperation.Kind == OperationKind.ExpressionStatement &&
+                            innerOperation is IExpressionStatementOperation exprStatement)
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: First part of the condition seems redundant.

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs [hunk 2]
```diff
@@ -195,6 +195,47 @@ public void AnalyzeOperation(OperationAnalysisContext context)
...
+                        {
+                            innerOperation = exprStatement.Operation;
+                        }
+
+                        if (innerOperation.Kind == OperationKind.Throw &&
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: Do we need the kind checks?

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs (hunk 1 above)
Comment (333fred) [reply src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: The intent is that it's a quick bail-out without the overhead of a cast, though we are not consistent about this throughout this project. We should decide on a convention and stick with it.

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs [hunk 3]
```diff
@@ -195,6 +195,47 @@ public void AnalyzeOperation(OperationAnalysisContext context)
...
+                            innerOperation is IThrowOperation throwOperation &&
+                            throwOperation.Exception.Kind == OperationKind.ObjectCreation &&
+                            throwOperation.Exception is IObjectCreationOperation createdException)
+                        {
+                            var notImplementedType = WellKnownTypes.NotImplementedException(context.Compilation);
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: :bulb: This should include `NotSupportedException` as well.

Comment (333fred) [reply src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: Added.

**Comment by 333fred** [comment]
@mavasani could I get another review, updated implementation.

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs [hunk 4]
```diff
@@ -69,6 +69,10 @@ public override void Initialize(AnalysisContext context)
                     onSerializingAttribute,
                     obsoleteAttribute);
 
+                ImmutableHashSet<INamedTypeSymbol> exceptionsToSkip = ImmutableHashSet.Create(
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: :bulb: `ImmutableArray<T>` would be more efficient for this use case.
