### PR TITLE
Issue 4981: Add support for 'is not null'

### LINKED ISSUE #4981: CA2000 does not handle "is not null"
### Analyzer

**Diagnostic ID**: [CA2000](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000): `Dispose objects before losing scope`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.201](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

**Update: See repro below: https://github.com/dotnet/roslyn-analyzers/issues/4981#issuecomment-816461346**

CA2000 seems not to recognize `is not null` pattern but it recognize `!= null` in the following snippet:

```csharp
WebSocketClient? client = null; // `WebSocketClient` implements `IAsyncDisposable`

try
{
    client = new(uri, nameof(MyApiService));
    Result connectRes = await client.ConnectAsync(cancellationToken).ConfigureAwait(false);
    if (connectRes)
    {
        result = Result<IWebSocketClient>.Ok(client);
        client = null;
    }
    else result = connectRes;
}
finally
{
    if (client is not null) // <--- CHANGE THIS TO `if (client != null)` and the CA2000 warning is gone.
    {
        await client.DisposeAsync().ConfigureAwait(false);
    }
}
```

This is certainly not a shortest code one can come up but it is easy to understand I think.

### Steps To Reproduce

Please see the example above.

### Expected behavior

`if (client is not null)` does not lead to CA2000 being emitted.

### Actual behavior

`is not null` seems to be not supported but `!= null` is.

### PR DESCRIPTION
**Pull request by manfred-brands**
fixes #4981

### CODE REVIEW

**Comment by mavasani** [comment]
@sharwell Can you please review as this deals with lightup wrappers?

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 1]
```diff
@@ -1260,29 +1261,41 @@ internal bool TryInferConversion(IIsPatternOperation operation, out ConversionIn
...
+                if (operation is IIsPatternOperation isPatternOperation)
                 {
-                    if (constantPattern.Value.ConstantValue.HasValue)
+                    IPatternOperation patternOperation = isPatternOperation.Pattern;
+                    bool direct = true;
+
+                    if (INegatedPatternOperationWrapper.IsInstance(patternOperation))
+                    {
+                        INegatedPatternOperationWrapper negatedPattern = INegatedPatternOperationWrapper.FromOperation(patternOperation);
+                        patternOperation = negatedPattern.Pattern;
```
Comment (Youssef1313) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: Can `.Children` work here? In this case we won't really need to introduce an operation wrapper

Comment (manfred-brands) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: It seems that `isPatternOperation.Pattern.Children.First()` matches `negatedPattern.Patten`
But is that making assumptions or can we rely on this?

Comment (Youssef1313) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: Since the pattern has only one child, accessing `.Children` looks good and is more simple. @mavasani @sharwell Are you okay with `.Children` approach instead of operation wrapper? The only thing we'll need in Lightup layer is a simple member in `OperationKindEx` enum.

Comment (sharwell) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: Are we not yet at a point where we can increment the Roslyn reference version?

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 2]
```diff
@@ -1260,29 +1261,41 @@ internal bool TryInferConversion(IIsPatternOperation operation, out ConversionIn
...
+                        direct = false;
+                    }
+
+                    if (patternOperation is IConstantPatternOperation constantPattern)
```
Comment (sharwell) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1276]: else if?

Comment (sharwell) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1276]:
```suggestion
                    if (patternOperation is IConstantPatternOperation { Value.ConstantValue: var constantValue )
```

It's unclear if the return statement could be refactored to let this reduce all the way to:

```suggestion
                    if (patternOperation is IConstantPatternOperation { Value.ConstantValue: { HasValue: true, Value: null } )
```

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs (hunk 1 above)
Comment (Youssef1313) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: @sharwell If we can't upgrade, then https://github.com/dotnet/roslyn-analyzers/issues/5816 can help.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs (hunk 2 above)
Comment (manfred-brands) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1276]: No. If pattern is `NegatedPattern`, we set pattern to `NegatedPattern.Pattern`, otherwise we keep the original pattern.
We check if that pattern is `ConstantPattern`, so we either check `is null` or `is not null`.

Comment (manfred-brands) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs]: I did the minimal amount of changes, not refactored the code.
The latter seems to work, but removes the `return false` case when the pattern is `IConstantPattern` but without a value. Not sure when that even would occur.
Pushed up a commit with that change.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs (hunk 1 above)
Comment (mavasani) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: Given we ship CA analyzers as part of .NET SDK, we can safely bump the Roslyn reference version to the one required by the last shipped SDK. @jmarolf do we know what is the minimum compiler/Roslyn version required by .NET6 SDK?

Comment (Youssef1313) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: @mavasani This can break people who get the analyzers via NuGet instead of the SDK?

I'm not opposed to that, but noting that upgrading might not be 100% safe.

Comment (mavasani) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: @Youssef1313 I think we want to explicitly call out (somewhere) that all versions of NetAnalyzers NuGet are not guaranteed to work on all versions of VS/compiler (basically Roslyn). It is reasonable to have a minimum required version of VS/Compiler associated with NetAnalyzers NuGet, which should match the version required by the corresponding .NET SDK. @jmarolf to confirm if this is a reasonable stance to take.

Comment (Youssef1313) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: @mavasani I agree with that.

Comment (manfred-brands) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1272]: I must admit that I was surprised that the 6.0.0 version of the analyzer didn't demand 6.0 of the SDK or at least knew about all the new language features. The problem you have is that the cat is out of the bag, e.g. there might be people using the 6.0.0 of the analyzer with the 5.0 SDK. Changing it such that this doesn't work for the next version is a breaking change which would require a major version number increase to 7 which would confuse the heck out of developers.

**Comment by Youssef1313** [comment]
Ping @mavasani for review.

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@manfred-brands can you please resolve merge conflicts?
