### PR TITLE
Fix CA1000 (DoNotDeclareStaticMembersOnGenericTypes) for operator ove…

### LINKED ISSUE #1791: CA1000: Do not declare static members on generic types shown on operator overloading
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Diagnostic ID

[CA1000](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1000-do-not-declare-static-members-on-generic-types)

#### Repro steps

In Visual Studio 2017, CA 1000: Do not declare static members on generic types shown on operator overloadings.

This happened only if the class is public or protected 

Sample Codes

```csharp
public abstract class TestObject<T2> : IEquatable<TestObject<T2>>, IComparable<TestObject<T2>>
        where T2 : TestObject<T2>, new()
    {
        public static bool operator ==(TestObject<T2> first, TestObject<T2> second) => first.Equals(second);

        public static bool operator !=(TestObject<T2> first, TestObject<T2> second) => !(first == second);

        public static bool operator <(TestObject<T2> first, TestObject<T2> second) => first.CompareTo(second) < 0;

        public static bool operator >(TestObject<T2> first, TestObject<T2> second) => first.CompareTo(second) > 0;

        public static bool operator <=(TestObject<T2> first, TestObject<T2> second) => first.CompareTo(second) <= 0;

        public static bool operator >=(TestObject<T2> first, TestObject<T2> second) => first.CompareTo(second) >= 0;

        public int CompareTo(TestObject<T2> other)
        {
            return 0;
        }

        public bool Equals(TestObject<T2> other)
        {
            return true;
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj is null)
            {
                return false;
            }

            throw new NotImplementedException();
        }

        public override int GetHashCode()
        {
            throw new NotImplementedException();
        }
    }
```

2018-08-21 13_19_42-consoleapp1_consoleapp1

#### Expected behavior

CA1000 should not be considered in this case.

### PR DESCRIPTION
**Pull request by mavasani**
…rloads

Make the analyzer more conservative by only flagging `MethodKind.Ordinary`.
Fixes #1791

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypes.cs [hunk 1]
```diff
@@ -51,11 +51,7 @@ public override void Initialize(AnalysisContext analysisContext)
...
 
                     if (symbol is IMethodSymbol methodSymbol &&
-                        (methodSymbol.IsAccessorMethod() ||
-                        (methodSymbol.MethodKind == MethodKind.UserDefinedOperator &&
-                        (methodSymbol.Name == WellKnownMemberNames.EqualityOperatorName ||
-                        methodSymbol.Name == WellKnownMemberNames.InequalityOperatorName)) ||
-                        methodSymbol.MethodKind == MethodKind.Conversion))
+                        methodSymbol.MethodKind != MethodKind.Ordinary)
                     {
                         return;
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDeclareStaticMembersOnGenericTypes.cs]: :bulb: A comment might be helpful
