### PR TITLE
CA1710: Add support for IReadOnlyDictionary

### LINKED ISSUE #2955: CA1710 triggers on IReadOnlyDictionary<> to add "Collection"
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.6 (Latest)

#### Diagnostic ID

[CA1710](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca1710)

#### Repro steps

1. Create a class which implements IReadOnlyDictionary<TKey, TValue>.
2. Refresh analyzer warnings, if necessary, and examine them.

#### Expected behavior
CA1710 should either not trigger, or trigger asking for the name to end with "Dictionary", depending on the class name.

#### Actual behavior
CA1710 triggers asking to rename the class to end with "Collection".

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #2955

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs [hunk 1]
```diff
@@ -1,14 +1,14 @@
 // Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.
 
-using System.Collections.Immutable;
-using Microsoft.CodeAnalysis;
-using Microsoft.CodeAnalysis.Diagnostics;
-using Analyzer.Utilities;
-using System.Collections.Generic;
 using System;
+using System.Collections.Generic;
```
Comment (Evangelink) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs]: I can revert the using reorder if you prefer.

**Comment by mavasani** [comment]
Please file an issue on https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1710?view=vs-2019#rule-description to update the table.

**Comment by Evangelink** [comment]
@mavasani Could you rerun the ci job?
