### PR TITLE
Do not fire CA1822 (Mark members as static) for non-externally visibl…

### LINKED ISSUE #1511: CA1822 should not fire for methods used in delegate constructors
#### Analyzer VSIX

Microsoft Code Analysis, version 2.6.0.6241303

#### Analyzer

CA1822

#### Repro steps

Consider this code:

    public sealed class MyAnalyzer : DiagnosticAnalyzer
    {
        public override void Initialize(AnalysisContext context)
        {
            context.RegisterSyntaxNodeAction(AnalyzeForEachStatement,
                ImmutableArray.Create(SyntaxKind.ForEachStatement));
        }

        private void AnalyzeForEachStatement(SyntaxNodeAnalysisContext context)
        {
        }
    }

#### Expected behavior

No CA1822 is reported.

#### Actual behavior

CA1822 is reported. The messages says:

> Member AnalyzeForEachStatement does not access instance data and can be marked as static (Shared in VisualBasic)
> Members that do not access instance data or call instance methods can be marked as static (Shared in Visual Basic). After you mark the methods as static, the compiler will emit nonvirtual call sites to these members. This can give you a measurable performance gain for performance-sensitive code.

This is simply not true. The compiler will not emit any call, because there are no call sites. More importantly, making the method static will significantly reduce the performance of the call. For more information and a benchmark, see [U2U1003](https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1003.md).

### PR DESCRIPTION
**Pull request by mavasani**
…e methods that are not target of an invocation

This prevents us from incorrectly flagging methods that are only invoked via delegate invocations and also reduces noise by not flagging non-public dead code.
Fixes #1511

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs [hunk 1]
```diff
@@ -85,10 +93,37 @@ public override void Initialize(AnalysisContext analysisContext)
...
+                                internalCandidates.Add(methodSymbol);
+                            }
                         }
                     });
                 });
+
+                compilationContext.RegisterOperationAction(operationContext =>
+                {
+                    var invocation = (IInvocationOperation)operationContext.Operation;
+                    if (!invocation.TargetMethod.IsExternallyVisible())
```
Comment (KrisVandermotten) [inline src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: From a performance point of view, it is probably a good idea to make sure the invokedInternalMethods collection doesn't become too large, and checking external visibility is good. However, lots of methods are going to be added that are never going to be in internalCandidates. Calling ShouldAnalyze is probably overkill (as that is a rather expensive method itself), but checking that the method is not static already, not abstract, virtual or override would probably not be a bad idea.

**Comment by KrisVandermotten** [comment]
From a performance point of view, it is probably a good idea to make sure the invokedInternalMethods collection doesn't become too large, and checking external visibility is good. However, lots of methods are going to be added that are never going to be in internalCandidates. Calling ShouldAnalyze is probably overkill (as that is a rather expensive method itself), but checking that the method is not static already, not abstract, virtual or override would probably not be a bad idea.
