### PR TITLE
Use ExportCodeFixProviderAttribute to trigger RS1016

### LINKED ISSUE #5818: RS1016 is raised on abstract class instead of on inheritors
### Analyzer

**Diagnostic ID**: [RS1016](https://github.com/dotnet/roslyn-analyzers/blob/ffd024eb265e97e639a2879d869cf82b5b958992/src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs): `Code fix providers should provide FixAll support`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers/3.3.3)

**Version**: 3.3.3

### Describe the bug

When you define an abstract class that inherits from `CodeFixProvider` and _do not_ override the `GetfixAllProvider()` method, RS1016 is raised on the abstract class instead of inheritors.

### Steps To Reproduce

Compile this code:

```csharp
using System.Collections.Immutable;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;

namespace Repro;

public abstract class CodeFixProviderBase : CodeFixProvider
{
    // Contains common helper methods for inheritors.
}

public class MyAnalyzer : CodeFixProviderBase
{
    public override ImmutableArray<string> FixableDiagnosticIds => ImmutableArray.Create("FOO001");

    public override Task RegisterCodeFixesAsync(CodeFixContext context)
    {
        context.RegisterCodeFix(
            CodeAction.Create("Foo",(cancellation) => { return Task.FromResult(context.Document); }),
            context.Diagnostics[0]
        );

        return Task.CompletedTask;
    }
}
```

### Expected behavior

RS1016 is produced on the `MyAnalyzer` class.

### Actual behavior

RS1016 is produced on the `CodeFixProviderBase` class.

## Additional context

Even when the inheriting class overrides `GetFixAllProvider`, the RS1016 diagnostic is still reported on the base class, even though there's no need for it to provide a "fix all" provider. For example, this still produces RS1016:

```csharp
public abstract class CodeFixProviderBase : CodeFixProvider
                   // ~~~~~~~~~~~~~~~~~~~ RS1016
{
    // Contains common helper methods for inheritors.
}

public class MyAnalyzer : CodeFixProviderBase
{
    public override FixAllProvider GetFixAllProvider() => WellKnownFixAllProviders.BatchFixer;

    // Rest of the code fix provider implementation...
}
```

This can be worked around by overriding `GetFixAllProvider()` in `CodeFixProviderBase` and marking it as abstract. This forces inheritors to override it. but I feel that it would be better for the diagnostic to be recorded on the inheritors instead of the base class.

### PR DESCRIPTION
**Pull request by reduckted**
Fixes #5818

I've used the suggestion from @Youssef1313 to use the `ExportCodeFixProvider` attribute to decide whether to report RS1016 instead of looking at the base type of the code fix provider.

This change means that RS1016 will now _only_ report a diagnostic on a code fix provider that is exported.

I have also fixed up some of the VB.NET tests:
* The test `VisualBasic_VerifyFix_NonSealedTypeAsync` was skipped because of dotnet/roslyn#23410. That bug was fixed quite a while ago, so I've stopped skipping it and fixed the code so that it passes.
* Most of the other VB.NET tests in `FixerWithFixAllAnalyzerTests.Fixer.cs` weren't actually testing anything. The original source code did not produce RS1016, and the "fixed" code was the same as the original code.

### CODE REVIEW

File: src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs [hunk 1]
```diff
@@ -29,6 +29,7 @@ public sealed class FixerWithFixAllAnalyzer : DiagnosticAnalyzer
         private const string EquivalenceKeyPropertyName = "EquivalenceKey";
         private const string EquivalenceKeyParameterName = "equivalenceKey";
         internal const string CodeFixProviderMetadataName = "Microsoft.CodeAnalysis.CodeFixes.CodeFixProvider";
+        private const string ExportCodeFixProviderAttributeMetadataName = "Microsoft.CodeAnalysis.CodeFixes.ExportCodeFixProviderAttribute";
```
Comment (sharwell) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs:32]: Do we have access to WellKnownTypeNames from this location?

Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs:32]: Correct, this definition should move to https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/WellKnownTypeNames.cs

Comment (reduckted) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs:32]: Just out of interest, what's the criteria for defining a type in `WellKnownTypeNames`? Does it have to be used in multiple places, or should all type names be defined there? Should `CodeFixProvider` be defined there as well?

Comment (Youssef1313) [reply src/Microsoft.CodeAnalysis.Analyzers/Core/FixAnalyzers/FixerWithFixAllAnalyzer.cs:32]: All strings representing fully qualified name to some type should be defined there I think. So, `CodeFixProvider` should also be there, I think.

**Review by mavasani — APPROVED** [review]
