### PR TITLE
Enable rule CA1305 and fix all violations

### LINKED ISSUE #965: Fix 300+ violations of CA1305 in Analyzers.sln and remove the suppression for this rule
I am going to disable CA1305 for the entire solution in https://github.com/dotnet/roslyn-analyzers/blob/master/build/Rulesets/Analyzers.ruleset

We should remove this suppression once we have fixed all violations of CA1305 in Analyzers.sln

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #965

### CODE REVIEW

**Comment by Evangelink** [comment]
build and tests are ok locally.

**Comment by Evangelink** [comment]
@mavasani All good. It seems that the error was linked to the fact that the branch wasn't rebased on latest master.

File: src/Microsoft.CodeQuality.Analyzers/Core/GlobalSuppressions.cs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+﻿// This file is used by Code Analysis to maintain SuppressMessage
+// attributes that are applied to this project.
+// Project-level suppressions either have no target or are given
+// a specific target and scoped to a namespace, type, member, etc.
+
+// TODO: Remove this global suppression file when the analyzer is updated to stop reporting on char.ToString() without culture
+// See https://github.com/dotnet/roslyn-analyzers/pull/2938
+[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<Pending>", Scope = "member", Target = "~M:Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.DefineAccessorsForAttributeArgumentsFixer.AddAccessor(Microsoft.CodeAnalysis.Document,Microsoft.CodeAnalysis.SyntaxNode,System.Threading.CancellationToken)~System.Threading.Tasks.Task{Microsoft.CodeAnalysis.Document}")]
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/GlobalSuppressions.cs]: 💡 It would be better to move this suppression to the specific member that needs it

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 2]
```diff
@@ -112,15 +113,15 @@ public string GetTime()
         public void CSharp_CA1721_PropertyNamesMatchGetMethodNames_Exposed_Diagnostics(string propertyAccessibility, string methodAccessibility)
         {
             VerifyCSharp(
-                string.Format(CSharpTestTemplate, propertyAccessibility, methodAccessibility),
+                string.Format(CultureInfo.CurrentCulture, CSharpTestTemplate, propertyAccessibility, methodAccessibility),
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]: 📝 This should be `InvariantCulture`

```suggestion
                string.Format(CultureInfo.InvariantCulture, CSharpTestTemplate, propertyAccessibility, methodAccessibility),
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 3]
```diff
@@ -112,15 +113,15 @@ public string GetTime()
...
                 GetCA1721CSharpResultAt(
                     line: 6,
                     column: $"    {propertyAccessibility} DateTime ".Length + 1,
                     identifierName: "Date",
                     otherIdentifierName: "GetDate"));
 
             VerifyCSharp(
-                string.Format(CSharpNotExternallyVisibleTestTemplate, propertyAccessibility, methodAccessibility));
+                string.Format(CultureInfo.CurrentCulture, CSharpNotExternallyVisibleTestTemplate, propertyAccessibility, methodAccessibility));
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]: 📝 This should be `InvariantCulture`

```suggestion
                string.Format(CultureInfo.InvariantCulture, CSharpNotExternallyVisibleTestTemplate, propertyAccessibility, methodAccessibility));
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 4]
```diff
@@ -131,7 +132,7 @@ public void CSharp_CA1721_PropertyNamesMatchGetMethodNames_Exposed_Diagnostics(s
         [InlineData("", "")]
         public void CSharp_CA1721_PropertyNamesMatchGetMethodNames_Unexposed_NoDiagnostics(string propertyAccessibility, string methodAccessibility)
         {
-            VerifyCSharp(string.Format(CSharpTestTemplate, propertyAccessibility, methodAccessibility));
+            VerifyCSharp(string.Format(CultureInfo.CurrentCulture, CSharpTestTemplate, propertyAccessibility, methodAccessibility));
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
            VerifyCSharp(string.Format(CultureInfo.InvariantCulture, CSharpTestTemplate, propertyAccessibility, methodAccessibility));
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 5]
```diff
@@ -155,7 +156,7 @@ public void CSharp_CA1721_PropertyNamesMatchGetMethodNames_Unexposed_NoDiagnosti
         [InlineData("", "protected internal")]
         public void CSharp_CA1721_PropertyNamesMatchGetMethodNames_MixedExposure_NoDiagnostics(string propertyAccessibility, string methodAccessibility)
         {
-            VerifyCSharp(string.Format(CSharpTestTemplate, propertyAccessibility, methodAccessibility));
+            VerifyCSharp(string.Format(CultureInfo.CurrentCulture, CSharpTestTemplate, propertyAccessibility, methodAccessibility));
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
            VerifyCSharp(string.Format(CultureInfo.InvariantCulture, CSharpTestTemplate, propertyAccessibility, methodAccessibility));
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 6]
```diff
@@ -238,15 +239,15 @@ End Function
         public void Basic_CA1721_PropertyNamesMatchGetMethodNames_Exposed_Diagnostics(string propertyAccessibility, string methodAccessibility)
         {
             VerifyBasic(
-                string.Format(BasicTestTemplate, propertyAccessibility, methodAccessibility),
+                string.Format(CultureInfo.CurrentCulture, BasicTestTemplate, propertyAccessibility, methodAccessibility),
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
                string.Format(CultureInfo.InvariantCulture, BasicTestTemplate, propertyAccessibility, methodAccessibility),
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 7]
```diff
@@ -238,15 +239,15 @@ End Function
...
                 GetCA1721BasicResultAt(
                     line: 5,
                     column: $"    {propertyAccessibility} ReadOnly Property ".Length + 1,
                     identifierName: "Date",
                     otherIdentifierName: "GetDate"));
 
             VerifyBasic(
-                string.Format(BasicNotExternallyVisibleTestTemplate, propertyAccessibility, methodAccessibility));
+                string.Format(CultureInfo.CurrentCulture, BasicNotExternallyVisibleTestTemplate, propertyAccessibility, methodAccessibility));
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
                string.Format(CultureInfo.InvariantCulture, BasicNotExternallyVisibleTestTemplate, propertyAccessibility, methodAccessibility));
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 8]
```diff
@@ -256,7 +257,7 @@ public void Basic_CA1721_PropertyNamesMatchGetMethodNames_Exposed_Diagnostics(st
         [InlineData("Friend", "Friend")]
         public void Basic_CA1721_PropertyNamesMatchGetMethodNames_Unexposed_NoDiagnostics(string propertyAccessibility, string methodAccessibility)
         {
-            VerifyBasic(string.Format(BasicTestTemplate, propertyAccessibility, methodAccessibility));
+            VerifyBasic(string.Format(CultureInfo.CurrentCulture, BasicTestTemplate, propertyAccessibility, methodAccessibility));
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
            VerifyBasic(string.Format(CultureInfo.InvariantCulture, BasicTestTemplate, propertyAccessibility, methodAccessibility));
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 9]
```diff
@@ -600,14 +601,14 @@ End Class
...
-            string message = string.Format(MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
+            string message = string.Format(CultureInfo.CurrentCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
             return GetCSharpResultAt(line, column, PropertyNamesShouldNotMatchGetMethodsAnalyzer.RuleId, message);
         }
 
         private static DiagnosticResult GetCA1721BasicResultAt(int line, int column, string identifierName, string otherIdentifierName)
         {
             // Add a public read-only property accessor for positional argument '{0}' of attribute '{1}'.
-            string message = string.Format(MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
+            string message = string.Format(CultureInfo.CurrentCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
            string message = string.Format(CultureInfo.InvariantCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 10]
```diff
@@ -600,14 +601,14 @@ End Class
         private static DiagnosticResult GetCA1721CSharpResultAt(int line, int column, string identifierName, string otherIdentifierName)
         {
             // Add a public read-only property accessor for positional argument '{0}' of attribute '{1}'.
-            string message = string.Format(MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
+            string message = string.Format(CultureInfo.CurrentCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
            string message = string.Format(CultureInfo.InvariantCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 11]
```diff
@@ -274,7 +275,7 @@ public void Basic_CA1721_PropertyNamesMatchGetMethodNames_Unexposed_NoDiagnostic
         [InlineData("Friend", "Protected Friend")]
         public void Basic_CA1721_PropertyNamesMatchGetMethodNames_MixedExposure_NoDiagnostics(string propertyAccessibility, string methodAccessibility)
         {
-            VerifyBasic(string.Format(BasicTestTemplate, propertyAccessibility, methodAccessibility));
+            VerifyBasic(string.Format(CultureInfo.CurrentCulture, BasicTestTemplate, propertyAccessibility, methodAccessibility));
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]:
```suggestion
            VerifyBasic(string.Format(CultureInfo.InvariantCulture, BasicTestTemplate, propertyAccessibility, methodAccessibility));
```

File: src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs [hunk 12]
```diff
@@ -269,7 +270,7 @@ public override async Task<CodeAction> GetFixAsync(FixAllContext fixAllContext)
                         {
                             ImmutableArray<Diagnostic> diagnostics = await fixAllContext.GetDocumentDiagnosticsAsync(fixAllContext.Document).ConfigureAwait(false);
                             diagnosticsToFix.Add(new KeyValuePair<Project, ImmutableArray<Diagnostic>>(fixAllContext.Project, diagnostics));
-                            title = string.Format(titleFormat, "document", fixAllContext.Document.Name);
+                            title = string.Format(CultureInfo.InvariantCulture, titleFormat, "document", fixAllContext.Document.Name);
```
Comment (sharwell) [inline src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs]: 📝 A bug should be filed to fix this method. It's similar to dotnet/roslyn#39411.

File: src/Utilities/Compiler/WordParser.cs [hunk 13]
```diff
@@ -98,7 +99,7 @@ public WordParser(string text, WordParserOptions options, char prefix)
         {
             if (options < WordParserOptions.None || options > (WordParserOptions.IgnoreMnemonicsIndicators | WordParserOptions.SplitCompoundWords))
             {
-                throw new ArgumentException($"'{nameof(options)}' ({((int)options).ToString()}) is invalid for Enum type'{typeof(WordParserOptions).Name}'");
+                throw new ArgumentException($"'{nameof(options)}' ({((int)options).ToString(CultureInfo.InvariantCulture)}) is invalid for Enum type'{typeof(WordParserOptions).Name}'");
```
Comment (sharwell) [inline src/Utilities/Compiler/WordParser.cs]: 😕 This seems unnecessarily complex

```suggestion
                throw new ArgumentException($"'{(int)options}' is invalid for enum type '{typeof(WordParserOptions).Name}'", nameof(options));
```

File: src/Microsoft.CodeQuality.Analyzers/Core/GlobalSuppressions.cs (hunk 1 above)
Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/Core/GlobalSuppressions.cs]: I decided to go with the global suppression to avoid looking for all instances when the PR #2938 will be merged. It is done now so anyway I will be able to get rid of this suppression.

File: src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs (hunk 12 above)
Comment (Evangelink) [reply src/PublicApiAnalyzers/Core/CodeFixes/DeclarePublicApiFix.cs]: https://github.com/dotnet/roslyn-analyzers/issues/2976

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 14]
```diff
@@ -600,17 +601,17 @@ End Class
         private static DiagnosticResult GetCA1721CSharpResultAt(int line, int column, string identifierName, string otherIdentifierName)
         {
             // Add a public read-only property accessor for positional argument '{0}' of attribute '{1}'.
-            string message = string.Format(MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
+            string message = string.Format(CultureInfo.InvariantCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]: This one was an incorrect suggestion from my previous review (was correct in the original one).

```suggestion
            string message = string.Format(CultureInfo.CurrentCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 15]
```diff
@@ -600,17 +601,17 @@ End Class
...
             return GetCSharpResultAt(line, column, PropertyNamesShouldNotMatchGetMethodsAnalyzer.RuleId, message);
         }
 
         private static DiagnosticResult GetCA1721BasicResultAt(int line, int column, string identifierName, string otherIdentifierName)
         {
             // Add a public read-only property accessor for positional argument '{0}' of attribute '{1}'.
-            string message = string.Format(MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
+            string message = string.Format(CultureInfo.InvariantCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]: This one was an incorrect suggestion from my previous review (was correct in the original one).

```suggestion
            string message = string.Format(CultureInfo.CurrentCulture, MicrosoftCodeQualityAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage, identifierName, otherIdentifierName);
```

**Comment by Evangelink** [comment]
It looks like the version of the analyzer used by the code isn't the latest code version, @sharwell could you confirm? If so, shall I revert the last commit or shall we do something to increase the version used? 

The build failure is linked to `char.ToString()` not having a culture, which was a bug fixed in some recent PR.

**Comment by sharwell** [comment]
@mavasani may be able to update the version number and trigger a rebuild of this pull request. If this is successful, you would not need to rebase your pull request as the build always runs on the merged result of the code in the pull request and the latest master branch commit.

**Comment by mavasani** [comment]
Created https://github.com/dotnet/roslyn-analyzers/pull/2989 - I haven't tested it locally, but in case it fails due to additional violations in our repo, we can work towards fixing/suppressing them and unblock this PR.

**Comment by Bouke** [comment]
Any ideas on when might this PR might make it into a release?
