### PR TITLE
Enhance GenerateDocumentationAndConfigFiles tool to generate vNext globalconfig files

### LINKED ISSUE #6247: Enhance GenerateDocumentationAndConfigFiles tool to generate vNext globalconfig files
As a side note, I am going to enhance the tooling so such a regression does not happen in future. Our generated globalconfig files that we ship in the package should most likely include a `vNext` set of globalconfig files so that when the analysis level is set to `latest` or explicitly to `vNext`, we still find a proper mapped globalconfig file.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/issues/6245#issuecomment-1301818551_

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6247

Our generated globalconfig files that we ship in the analyzer NuGet packages and .NET SDK should likely include a vNext set of globalconfig files so that when the analysis level is set to latest or explicitly to vNext for upcoming .NET Release, we still find a proper mapped globalconfig file. This will avoid regressions such as #6245 in future.

Verified that locally built Microsoft.CodeAnalysis.NetAnalyzers package with this change includes globalconfig files specific to 8.0 release version.

### CODE REVIEW

**Comment by mavasani** [comment]
@Evangelink @Youssef1313 can you please review? Thanks!

File: src/Tools/GenerateDocumentationAndConfigFiles/Program.cs [hunk 1]
```diff
@@ -705,7 +706,8 @@ async Task<bool> createGlobalConfigFilesAsync()
 
                     var assemblyName = Path.GetFileNameWithoutExtension(assembly);
                     var shippedFile = Path.Combine(assemblyDir, "AnalyzerReleases", assemblyName, ReleaseTrackingHelper.ShippedFileName);
-                    if (File.Exists(shippedFile))
+                    var unshippedFile = Path.Combine(assemblyDir, "AnalyzerReleases", assemblyName, ReleaseTrackingHelper.UnshippedFileName);
+                    if (File.Exists(shippedFile) && File.Exists(unshippedFile))
```
Comment (Youssef1313) [inline src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:710]: Should we assert that either both exists, or both don't (ie, assert that not only one of them is found)?

File: src/Tools/GenerateDocumentationAndConfigFiles/Program.cs [hunk 2]
```diff
@@ -744,33 +756,49 @@ async Task<bool> createGlobalConfigFilesAsync()
 
                 if (versionsBuilder.Count > 0)
                 {
-                    var shippedFilesData = shippedFilesDataBuilder.ToImmutable();
+                    var releaseTrackingData = shippedFilesDataBuilder.Concat(unshippedFilesDataBuilder).ToImmutableArray();
```
Comment (Youssef1313) [inline src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:759]: Can we use a single builder instead?

**Review by Youssef1313 — APPROVED** [review]
LGTM

File: src/Tools/GenerateDocumentationAndConfigFiles/Program.cs [hunk 3]
```diff
@@ -717,14 +729,24 @@ async Task<bool> createGlobalConfigFilesAsync()
...
-                            shippedFilesDataBuilder.Add(releaseTrackingData);
+                            releaseTrackingFilesDataBuilder.Add(releaseTrackingData);
                             versionsBuilder.AddRange(releaseTrackingData.Versions);
+
+                            // Read unshipped file
+                            using var fileStreamUnshipped = File.OpenRead(unshippedFile);
+                            var sourceTextUnshipped = SourceText.From(fileStreamUnshipped);
+                            var releaseTrackingDataUnshipped = ReleaseTrackingHelper.ReadReleaseTrackingData(unshippedFile, sourceTextUnshipped,
+                                onDuplicateEntryInRelease: (_1, _2, _3, _4, line) => throw new Exception($"Duplicate entry in {unshippedFile} at {line.LineNumber}: '{line}'"),
+                                onInvalidEntry: (line, _2, _3, _4) => throw new Exception($"Invalid entry in {unshippedFile} at {line.LineNumber}: '{line}'"),
```
Comment (Evangelink) [inline src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:747]: I usually prefer to avoid throwing `Exception`. You could maybe use `InvalidOperationException`:

> method call is invalid for the object's current state

Comment (Evangelink) [reply src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:747]: I see that it's also used (not changed here) a few lines above so I'd recommend updating both places if you go for the change.

File: src/Tools/GenerateDocumentationAndConfigFiles/Program.cs [hunk 4]
```diff
@@ -1257,14 +1295,16 @@ bool AddRule(DiagnosticDescriptor rule, string? category)
...
                         }
 
-                        if (shippedReleaseData != null)
+                        if (releaseTrackingDataAndVersion != null)
                         {
                             isEnabledByDefault = isEnabledRuleForNonDefaultAnalysisMode;
-                            var maxVersion = shippedReleaseData.Value.version;
+                            var maxVersion = releaseTrackingDataAndVersion.Value.isShippedVersion ?
+                                releaseTrackingDataAndVersion.Value.version :
+                                ReleaseTrackingHelper.UnshippedVersion;
```
Comment (Evangelink) [inline src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:1303]: Cosmetic preference but feel free to keep it as-is:

```suggestion
                            var maxVersion = releaseTrackingDataAndVersion.Value.isShippedVersion
                                ? releaseTrackingDataAndVersion.Value.version
                                : ReleaseTrackingHelper.UnshippedVersion;
```

**Review by Evangelink — APPROVED** [review]
LGTM - few nitpicks you can ignore if you want.

File: src/Tools/GenerateDocumentationAndConfigFiles/Program.cs (hunk 4 above)
Comment (mavasani) [reply src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:1303]: Yeah, it seems the code style for multiline ternary expressions has many divided preferences. We should really have a code style rule that can be enforced on build to ensure consistency. @CyrusNajmabadi mentioned he plans to author an IDE code style analyzer for it. I'll wait for such an enforcement before changing code styles.

**Review by Youssef1313 — COMMENTED** [review]
@mavasani Took a look again at this, I'm not sure how this prevents the issue in the future.

The meaning of `latest` in analysis level is hardcoded to a specific version on dotnet/sdk

https://github.com/dotnet/sdk/blob/39fcce04a117339a8087060201b1f7797b6167e8/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L49

https://github.com/dotnet/sdk/blob/39fcce04a117339a8087060201b1f7797b6167e8/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.Analyzers.targets#L25

So the new globalconfig that contains unshipped will not be used.

**Comment by Youssef1313** [comment]
This is also currently confusing. I think `latest-8` will enable more rules than `latest-7`?

Please correct me if I'm misunderstanding something.

**Comment by mavasani** [comment]
> This is also currently confusing. I think `8` will enable more rules than `latest` (because latest is hard-coded to `7` in .NET 7 SDK)?
> 
> Please correct me if I'm misunderstanding something.

@Youssef1313 This change basically gives us a bit of leeway when the unshipped rules get moved to the AnalyzerReases.Shipped.txt file. `latest` setting is still meant to be associated with latest _shipped_ rules, so it is working as expected. This change ensures that say once we create a new .NET 8 SDK branch and ship a preview release of the SDK, our tooling can find the matching globalconfig to map to the `AnalysisLevel` setting, even if we haven't moved our unshipped rules to AnalyzerReases.Shipped.txt because .NET 8 SDK wouldn't have shipped by then.
