### PR TITLE
Fix CA1063 when implementing the dispose pattern for a derived class

### LINKED ISSUE #1950: CA1063 when implementing the dispose pattern for a derived class
#### Analyzer package

https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers

#### Package Version

v2.6.2

#### Diagnostic ID

[CA1063](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1063-implement-idisposable-correctly)

#### Repro steps

1. Follow the [Implementing the dispose pattern for a derived class](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-derived-class) guide and override the Object.Finalize method.

     
        using System;

       class BaseClass : IDisposable
        {
        // Flag: Has Dispose already been called?
        bool disposed = false;
   
        // Public implementation of Dispose pattern callable by consumers.
        public void Dispose()
        { 
           Dispose(true);
           GC.SuppressFinalize(this);           
         }
   
        // Protected implementation of Dispose pattern.
        protected virtual void Dispose(bool disposing)
        {
           if (disposed)
              return; 
      
           if (disposing) {
              // Free any other managed objects here.
             //
           }
      
           // Free any unmanaged objects here.
           //
           disposed = true;
        }

           ~BaseClass()
          {
              Dispose(false);
           }
        }

              class DerivedClass : BaseClass
           {
            // Flag: Has Dispose already been called?
            bool disposed = false;
   
          // Protected implementation of Dispose pattern.
          protected override void Dispose(bool disposing)
          {
             if (disposed)
                return; 
      
             if (disposing) {
                // Free any other managed objects here.
                //
             }
      
           // Free any unmanaged objects here.
           //
           disposed = true;
      
               // Call the base class implementation.
               base.Dispose(disposing);
            }

             ~DerivedClass()
             {
               Dispose(false);
              }
            }

#### Expected behavior
No warnings show up.

#### Actual behavior
A CA1063 warning shows up. Either the analyzer is buggy or the documentation.

### PR DESCRIPTION
**Pull request by mavasani**
Relax the implementation of this rule to allow for derived types to implement the destructor/finalizer, but still check that the finalizer implementation invokes Dispose(false) and returns if any of its base type has a Dispose(bool) implementation.

Fixes #1950

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @duracellko as well.

**Comment by duracellko** [comment]
Code in PR looks good. However, I opened question in #1950, if this behavior is correct.

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs [hunk 1]
```diff
@@ -591,7 +630,98 @@ public class B : A
     }
 }|]
 ",
-            GetCA1063CSharpFinalizeOverrideResultAt(29, 14, "C"));
+            GetCA1063CSharpFinalizeImplementationResultAt(31, 6, "C", "Finalize"));
+        }
+
+        [Fact, WorkItem(1950, "https://github.com/dotnet/roslyn-analyzers/issues/1950")]
```
Comment (duracellko) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs]: Probably following test should be added to make sure, that the analyzer is relaxed and does not return warning, when there is no destructor. Just like in previous version.

```csharp
        [Fact, WorkItem(1950, "https://github.com/dotnet/roslyn-analyzers/issues/1950")]
        public void CSharp_CA1063_FinalizeOverride_NoDiagnostic_FinalizeNotOverriden()
        {
            VerifyCSharp(@"
using System;

public class B : IDisposable
{
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    ~B()
    {
        Dispose(false);
    }

    protected virtual void Dispose(bool disposing)
    {
    }
}

[|public class C : B
{
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
    }
}|]
");
        }
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs [hunk 2]
```diff
@@ -519,7 +519,46 @@ public override void Dispose()
 
         #region CSharp FinalizeOverride Unit Tests
 
-        [Fact]
+        [Fact, WorkItem(1950, "https://github.com/dotnet/roslyn-analyzers/issues/1950")]
+        public void CSharp_CA1063_FinalizeOverride_Diagnostic_SimpleFinalizeOverride_OverridesDisposeBool()
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/ImplementIDisposableCorrectlyTests.cs]: ❗️ This test is not correct. One of the following alterations must be made to the test input before the test can be considered correct:

1. Remove the finalizer from `B`
2. Remove the finalizer from `C`

Failure to address this will result in *both* finalizers getting called, which is not desirable.
