### PR TITLE
Fix NRE in BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer

### LINKED ISSUE #6778: .ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer throws NRE in Roslyn.sln
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	AD0001	Analyzer 'Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: Roslyn.Compilers.VisualBasic.IOperation.UnitTests
ISymbol: ExpectedSymbolVerifier (NamedType)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer.HasEqualityOperator(INamedTypeSymbol type)
   at Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines.BasicOverrideEqualsOnOverloadingOperatorEqualsAnalyzer._Closure$__._Lambda$__7-0(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
'.	Roslyn.Compilers.VisualBasic.IOperation.UnitTests (net472)	D:\R3\src\Compilers\VisualBasic\Test\IOperation\Roslyn.Compilers.VisualBasic.IOperation.UnitTests.vbproj	1	
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6778

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313

File: src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb [hunk 1]
```diff
@@ -63,8 +63,9 @@ Namespace Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines
         Private Shared Function HasEqualityOperator(type As INamedTypeSymbol) As Boolean
             For Each member In type.GetMembers()
                 Dim method = TryCast(member, IMethodSymbol)
-                If method?.MethodKind = MethodKind.UserDefinedOperator AndAlso
-                    CaseInsensitiveComparison.Equals(method.Name, WellKnownMemberNames.EqualityOperatorName) Then
+                If method IsNot Nothing AndAlso
+                   method.MethodKind = MethodKind.UserDefinedOperator AndAlso
+                   CaseInsensitiveComparison.Equals(method.Name, WellKnownMemberNames.EqualityOperatorName) Then
```
Comment (Youssef1313) [inline src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb:68]: I'm not following. If `method` is null, shouldn't `method?.MethodKind = MethodKind.UserDefinedOperator` evaluate to false and the second `AndAlso` operand is not evaluated?

To me `method?.MethodKind = MethodKind.UserDefinedOperator` is equivalent to `method IsNot Nothing AndAlso method.MethodKind = MethodKind.UserDefinedOperator`, but I must be missing something.

Comment (Youssef1313) [inline src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb:68]: Do we actually need case insensitive comparison? I know VB is case insensitive, but in this case the compiler should always emit `op_Equality` in the correct casing, and symbol will have its `Name` with the correct casing as well. I was wondering if this can be simplified by doing `type.GetMembers(WellKnownMemberNames.EqualityOperatorName)` and eliminate the `Name` check completely

Comment (mavasani) [reply src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb]: Good point - I have simplified the check

Comment (mavasani) [reply src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb]: Well, I thought the same, but apparently not. Below executable throws an NRE when executed with no command line arguments:

```vb
Imports System

Module Program
    Sub Main(args As String())
        Console.WriteLine("Hello World!")

        Dim c As C = Nothing
        If (args.Length <> 0) Then
            c = New C
            c.FieldA = A.F1
        End If

        If c?.FieldA = A.F1 AndAlso Equals(c.ToString(), "ConsoleApp54.C") Then
            Console.WriteLine("True")
        Else
            Console.WriteLine("False")
        End If
    End Sub
End Module

Class C
    Public FieldA As A
End Class

Public Enum A
    F1
    F2
End Enum
```

_VB never ceases to surprise!_

**Review by Youssef1313 — APPROVED** [review]
LGTM

File: src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb (hunk 1 above)
Comment (Youssef1313) [reply src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb]: That's very nice to know!
