### PR TITLE
Fix bunch of CA1062 (ValidateArgmentsOfPublicMethods) false positives

### LINKED ISSUE #2369: CA1062 false positive when String.IsNullOrEmpty is used for null check
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.2

#### Diagnostic ID

[CA1062: Validate arguments of public methods](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods)

#### Repro steps
1. Enable CA1062
2. Analyze the following code:

```csharp
public static void A(string input)
{
    if (string.IsNullOrEmpty(input))
    {
        throw new ArgumentException("Invalid input", nameof(input));
    }

    B(input); // This line causes a CA1062 violation, even though "input" is null-checked above.
}

private static void B(string input)
{
    var x = input.Length;
}
```

#### Expected behavior
No warning, since `input` is already checked for `null` via `string.IsNullOrEmpty()`.

#### Actual behavior
CA1062 is reported against `B(input)`.

### LINKED ISSUE #2504: CA1062 false positive when a generic null checker method is used
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.0, v2.9.1, v2.9.2

#### Diagnostic ID

[CA1062: Validate arguments of public methods](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods)

#### Repro steps

1. Enable CA1602
2. Analyze the following code (which is slightly modified from an example on the Diagnostic ID page):
```
public class Person
    {
        public string Name { get; private set; }
        public int Age { get; private set; }

        public Person(string name, int age)
        {
            Name = name;
            Age = age;
        }

        // Copy constructor
        public Person(Person other)
        {
            PassThroughNonNull(other);
            Name = other.Name;
            Age = other.Age;
        }

        /*
        // Null check method
        private static Person PassThroughNonNull(Person person)
        {
            if (person == null)
            {
                throw new ArgumentNullException("person");
            }

            return person;
        }
        */

        // Generic null check method
        private static T PassThroughNonNull<T>(T person)
        {
            if (person == null)
            {
                throw new ArgumentNullException("person");
            }

            return person;
        }
 }
```

#### Expected behaviour

No warning, since `other` is checked for `null` by the generic `PassThroughNull` method.

#### Actual behaviour

CA1062 is reported against `Name = other.Name;`

#### Further details

There are two significant changes above from the example code on the Diagnostic ID page. The pass through null check is being applied in the body of the constructor, rather than on parameters in a chained call to another constructor; and the pass through null check has been modified to accept a generic input rather than being a specific implementation for the Person class. We use such a generic null check widely throughout our codebase, and it satisfied pre-Roslyn versions of Code Analysis, so this failure is a serious one for us.

The null check from the Microsoft example (passes CA1062, but is too type-specific) has been left commented out in the example for convenience of comparison. The generic null check we've replaced it with seems to satisfy CA1062 when used in a chained call to another constructor but not when used in a method body such as the constructor in the example above.

### LINKED ISSUE #2525: CA1062 firing when the validation is in another method even with ValidatedNotNull attribute
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v2.9.3 (Latest)

#### Diagnostic ID

[CA1062](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019)

#### Repro steps
I have a public method where I validate the parameter in another method, In the old FXCop If you added an ValidatedNotNull attribute to your method the warning will not fire.
Upgrading to 2.9.3 fires the warning

Validation method
```
public static T ThrowIfNull<T>([ValidatedNotNull]this T value, string name)
{
    if (EqualityComparer<T>.Default.Equals(value, default))
    {
        throw new ArgumentNullException(name);
    }
    
    return value;
}
```

Method
```
public static object GetValueOrNull(this IDataRecord dataRecord, int index)
{
    dataRecord.ThrowIfNull(nameof(dataRecord));
    return !dataRecord.IsDBNull(index) ? dataRecord.GetValue(index) : null;  // warning fires here
}
```

#### Expected behavior
No error

#### Actual behavior
CA1062 warning

### LINKED ISSUE #2528: CA1062 false positive in case of ParamArray (VB.net)
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.3

#### Diagnostic ID

[CA1062](https://docs.microsoft.com/de-de/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019)

#### Repro steps

1. Copy the following example into a new VB project:

```
Public Class TestClass

  Public Sub Test(ParamArray ByVal values As String())

    Debug.Print(values.Length.ToString(System.Globalization.CultureInfo.InvariantCulture))

  End Sub

End Class
```

2. Install nuget package Microsoft.CodeAnalysis.FxCopAnalyzer

#### Expected behavior
CA1062 should not fire. [Microsoft](https://docs.microsoft.com/de-de/dotnet/visual-basic/programming-guide/language-features/procedures/parameter-arrays) states: 

> When you call a procedure that defines a parameter array, you can supply the argument in any one of the following ways: Nothing — that is, you can omit the ParamArray argument. In this case, an empty array is passed to the procedure. You can also pass the Nothing keyword, with the same effect.

#### Actual behavior
There is a compiler warning for `values` in `values.Length`.

### LINKED ISSUE #2582: CA1062 False Positive when null coalescing operator used with String.Empty
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.3

#### Diagnostic ID

[CA1062: Validate arguments of public methods](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods)

#### Repro steps

1. Enable CA1062
2. Analyze the following code:

```csharp
public class Class1
{
    public Class1(int num) { }

    public Class1(string name)
        : this((name ?? string.Empty).Length) // CA1062 here!
    {
    }
}
```

#### Expected behavior
No warning, since `string.Empty` is never `null`. This warning was NOT reported using the legacy/binary FxCop.

#### Actual behavior
CA1062 warning

### PR DESCRIPTION
**Pull request by mavasani**
I recommend reviewing commit by commit - each commit has very minor product fixes

1. https://github.com/dotnet/roslyn-analyzers/commit/38dc20a0a5570e19c37dd5d81647feeab1bdabfd: Handle argument null check methods in the PredicateAnalysis done with in core dataflow operation visitor. Fixes #2369
2. https://github.com/dotnet/roslyn-analyzers/commit/1ebfb476a05e4912c86f55c1daac026987b1b649: Special case few more field/property/methods that return non-null instances. Fixes #2582
   1. static readonly members named "Empty"
   2. static factory methods whose name starts with "Create"
3. https://github.com/dotnet/roslyn-analyzers/commit/c5dd3e42f2ede6888f15b88c310b091a57cd35b6: Ensure param arrays are always assumed to be non-null. Fixes #2528
4. https://github.com/dotnet/roslyn-analyzers/commit/0fe87eafe53f0a26cd3459ba7a326ff36d66b321: Mark arguments passed to parameters with ValidatedNotNullAttribute as validated. Fixes #2525
5. https://github.com/dotnet/roslyn-analyzers/commit/e03910f2751734e19992d2c107634813b8f3b009: Make sure we track points to values for type parameters with no value type constraint. Fixes #2504

### CODE REVIEW

File: src/Utilities/Compiler/Extensions/ISymbolExtensions.cs [hunk 1]
```diff
@@ -536,6 +536,21 @@ public static bool IsImplementationOfAnyExplicitInterfaceMember(this ISymbol sym
         }
 
         public static ITypeSymbol GetMemerOrLocalOrParameterType(this ISymbol symbol)
```
Comment (dotpaul) [inline src/Utilities/Compiler/Extensions/ISymbolExtensions.cs]: >Memer [](start = 37, length = 5)

spelling

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs [hunk 2]
```diff
@@ -951,12 +998,28 @@ private PointsToAbstractValue GetValueBasedOnInstanceOrReferenceValue(IOperation
             public override PointsToAbstractValue VisitFieldReference(IFieldReferenceOperation operation, object argument)
             {
                 var value = base.VisitFieldReference(operation, argument);
+
+                // "class SomeType { static readonly SomeType Empty; }"
+                if (IsSpecialEmptyMember(operation.Field) &&
+                    value.NullState != NullAbstractValue.Null)
```
Comment (dotpaul) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs]: >value.NullState != NullAbstractValue.Null [](start = 20, length = 41)

Why check for != Null, instead of != NotNull?

Null => definitely null?

File: src/Utilities/Compiler/Extensions/ISymbolExtensions.cs (hunk 1 above)
Comment (mavasani) [reply src/Utilities/Compiler/Extensions/ISymbolExtensions.cs]: Thanks, I am going to fix a few more false positives in next PR, will rename the method.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs (hunk 2 above)
Comment (mavasani) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs]: Just protecting against the case where the readonly member is assigned null, though not very likely. I don't think it will matter right now as we don't analyze readonly fields or properties.
