### PR TITLE
CA3075 don't pessimistically assume insecure XmlReaderSettings if unknown

### LINKED ISSUE #2105: CA3075 false positives for XmlReaderSettings
#### Analyzer package

[Microsoft.NetFramework.Analyzers](https://www.nuget.org/packages/Microsoft.NetFramework.Analyzers)

#### Package Version

v2.6.3

#### Diagnostic ID

[CA3075](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3075-insecure-dtd-processing)

#### Repro steps

```
using System.IO;
using System.Xml;

namespace ConsoleApp8
{
    class Program
    {
        private static readonly XmlReaderSettings s_xmlReaderSettings = new XmlReaderSettings()
        {
            DtdProcessing = DtdProcessing.Prohibit,
            XmlResolver = null
        };

        static void Main(string[] args)
        {
            var settings = new XmlReaderSettings()
            {
                DtdProcessing = DtdProcessing.Prohibit,
                XmlResolver = null
            };
            using (var reader = new StringReader(@"<xml></xml>"))
            using (var xmlReader = XmlReader.Create(reader, settings))                   // no warning given
            {
            }


            using (var reader = new StringReader(@"<xml></xml>"))
            using (var xmlReader = XmlReader.Create(reader, s_xmlReaderSettings))        // false positive warning
            {
            }

            using (var reader = new StringReader(@"<xml></xml>"))
            using (var xmlReader = XmlReader.Create(reader, new XmlReaderSettings()      // false positive warning
            {
                DtdProcessing = DtdProcessing.Prohibit,
                XmlResolver = null
            }))
            {
            }
        }
        
        private readonly XmlReaderSettings _xmlReaderSettingsInstance = new XmlReaderSettings()
        {
            DtdProcessing = DtdProcessing.Prohibit,
            XmlResolver = null
        };

        void Instance()
        {
            using (var reader = new StringReader(@"<xml></xml>"))
            using (var xmlReader = XmlReader.Create(reader, _xmlReaderSettingsInstance)) // false positive warning
            {
            }
        }
    }
}
```

#### Expected behavior

No warnings.

#### Actual behavior

Inconsistent warnings on the final three examples in the above. Somewhat annoyingly, the last example gets a false positive, and it is the example used as the solution in the documentation.

### PR DESCRIPTION
**Pull request by dotpaul**
Fixes #2105.  With the analyzer only looking at one code block at a time, XmlReaderSetting instances from member fields and input parameters are in an unknown state.  Instead of assuming insecure, we should not generate diagnostics on unknowns.

### CODE REVIEW

File: src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs [hunk 1]
```diff
@@ -284,19 +284,10 @@ private void AnalyzeMethodOverloads(OperationAnalysisContext context, IMethodSym
...
-                                RuleDoNotUseInsecureDtdProcessing,
-                                expressionSyntax.GetLocation(),
-                                SecurityDiagnosticHelpers.GetLocalizableResourceString(
-                                    nameof(MicrosoftNetFrameworkAnalyzersResources.XmlReaderCreateInsecureInputMessage)
-                                )
-                            );
-                            context.ReportDiagnostic(diag);
-                        }
-                        else if (!env.IsDtdProcessingDisabled && !(env.IsSecureResolver && env.IsMaxCharactersFromEntitiesLimited))
+                        // If we have no XmlReaderSettingsEnvironment, then we don't know.
```
Comment (mavasani) [inline src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs]: Just curious: what does legacy FxCop do for this case?

Comment (dotpaul) [reply src/Microsoft.NetFramework.Analyzers/Core/DoNotUseInsecureDtdProcessing.cs]: Haven't looked too deeply, but it doesn't generate a warning on the unit test I added.

**Comment by dotpaul** [comment]
FYI @timhermann @matt-desai @LingxiaChen @DSIE63
