### PR TITLE
CA1031 should not report diagnostic if catch block throws

### LINKED ISSUE #2278: CA1031: False positive when wrapping exception
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Package Version

2.9.1

#### Diagnostic ID

CA1031

#### Repro steps

It incorrectly warns about catching System.Exception. As you can see in this example, the caught exception is wrapped and rethrown. 

While not explicitly called out in the documentation, this matches the spirit of the rule which is to not swallow general exceptions.

                    try
                    {
                        value = Convert.ChangeType(value, targetType, CultureInfo.InvariantCulture);
                    }
                    catch (Exception ex)
                    {
                        throw new MappingException($"Cannot map value of type {value.GetType().FullName} to property {property.Name} of type {targetType.Name}.", ex);
                    }

### PR DESCRIPTION
**Pull request by m-akinc**
Fixes #2278

This changes the behavior to be more lenient, avoiding a diagnostic if the catch block contains any throw statement. Previously, we required a rethrow.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs [hunk 1]
```diff
@@ -328,6 +326,100 @@ End Namespace
...
+                {
+                    public static void TestMethod()
+                    {
+                        try 
+                        {
+                            FileStream fileStream = new FileStream(""name"", FileMode.Create);
+                        }
+                        catch (Exception e)
+                        {
+                            throw e;
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs]: ❓ Why `throw e` instead of `throw`?

Comment (m-akinc) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs]: This is an additional test case. The other case is already covered by `CSharp_Diagnostic_GeneralCatchWithRethrowFromSpecificCatch`.

While it might not make much sense to `throw e`, it's still worth ensuring that a diagnostic is not emitted for it.

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs]: @sharwell any further concerns?

Comment (sharwell) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/DoNotCatchGeneralExceptionTypesTests.cs]: Nope that answers my question thanks!
