### PR TITLE
Do not report on awaitable-awaiter patterns

### LINKED ISSUE #4623: CA1822 / CA1024 False-positive for awaitable pattern
### Analyzer

- **Diagnostic ID**: [CA1822](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822)
- **Diagnostic ID**: [CA1024](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1024)

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 5.0.1 (Latest)

### Steps To Reproduce

````charp
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

namespace Dummy
{
    public class Repro
    {
        public static async Task ReproAsync()
        {
            await new DummyAwaitable();
        }
    }

    public readonly struct DummyAwaitable : INotifyCompletion
    {
        // CA1024 Use properties where appropriate
        public DummyAwaitable GetAwaiter()
        {
            return this;
        }

        // CA1822 Member 'GetResult' does not access instance data and can be marked as static
        public void GetResult()
        {
        }

        // CA1822 Member 'IsCompleted' does not access instance data and can be marked as static
        public bool IsCompleted => false;

        public void OnCompleted(Action continuation) => throw null;
    }
}
````

### Expected behavior

No diagnostic

### Actual behavior

It reports diagnostics. If you apply the fix, the code doesn't compile.

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #4623

There is a first commit meant to ensure all code related to skipping the analysis is contained in the `ShouldAnalyze` method instead of being in multiple place. I suggest to review it first.

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs [hunk 1]
```diff
@@ -208,15 +201,31 @@ void OnSymbolEnd(SymbolAnalysisContext symbolEndContext)
...
+            // Don't report methods which have a single throw statement
+            // with NotImplementedException or NotSupportedException
+            if (blockStartContext.IsMethodNotImplementedOrSupported())
             {
                 return false;
             }
 
-            // CA1000 says one shouldn't declare static members on generic types. So don't flag such cases.
-            if (methodSymbol.ContainingType.IsGenericType && methodSymbol.IsExternallyVisible())
+            if (methodSymbol.IsExternallyVisible())
```
Comment (Evangelink) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/MarkMembersAsStatic.cs:210]: Avoid doing this check twice.

**Review by mavasani — APPROVED** [review]
