### PR TITLE
Track all disposable types in PointsToAnalysis

### LINKED ISSUE #6512: CA2000 reported on every using statement with IAsyncDisposable
### Analyzer

**Diagnostic ID**: [CA2000](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000): `Dispose objects before losing scope`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 7.0.0 (Latest Stable)

(The bug also exists in all versions of the analyzer built-in into the SDK in 5.0, 6.0 and 7.0)

### Describe the bug

Whenever one uses a using statement with an `IAsyncDisposable` the analyzer falsely reports CA2000.

### Steps To Reproduce

OPTIONAL: If you want, create a custom implementation of `IAsyncDisposable`. For this example I'll use `FileStream` to show that the bug affects even the most common built-in types.

1. Create an async method that contains a async using statement (like shown belown)
2. See error

```
public async Task DoSomethingAsync()
{
    await using var stream = new FileStream("C:\somefile.txt", FileMode.OpenOrCreate).ConfigureAwait(false); // this already shows the false issue
}
```

### Expected behavior

`await using var stream = new FileStream("C:\somefile.txt", FileMode.OpenOrCreate).ConfigureAwait(false);` will not report CA2000. Maybe if not used with a `using` it should report an issue, but that should be a newly created one, not CA2000, because CA2000 explicitly states one should call `System.IDisposable.Dispose` which is not correct for `IAsyncDisposable`.

### Actual behavior

`await using var stream = new FileStream("C:\somefile.txt", FileMode.OpenOrCreate).ConfigureAwait(false);` reports CA2000. `IAsyncDisposable` in general reports this, no matter if used in a `using` or not. The only way to suppress the issue is to initialize a variable and after that start a try-finally-block where the variable is disposed in the `finally` part, which is exactly what the `using` is for in C#.

## Additional context

This bug was already reported in issue #3042 but no one bothered to re-open it even though it was **not** fixed - so what other way to call attention to this bug than creating a new issue? 🤷‍♂️

### LINKED ISSUE #6765: CA2000 Should recognize a pattern for IAsyncDisposable
**Brief description:**
There's a pattern with regards to `IAsyncDisposable` when one wants to call `ConfigureAwait(false)` which has been recommended in [official guidance](https://devblogs.microsoft.com/dotnet/configureawait-faq/#can-i-use-configureawait-when-await-using-an-iasyncdisposable) but CA2000 does not respect:
``` csharp
var c = new MyAsyncDisposableClass(); // CA2000: Dispose objects before losing scope
await using (c.ConfigureAwait(false))
{
    ...
}
```

**Languages applicable:**

I am unfamiliar with any language besides C#, maybe this applies to VB or F#.

**Code example that the analyzer should report:**

``` csharp
var c = new MyAsyncDisposableClass();
await using (c.ConfigureAwait(false))
{
    ...
}
```

**Additional information:**

Wars have been fought over language-level support for `ConfigureAwait`. As it stands, this is what we have for this scenario.

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

### PR DESCRIPTION
**Pull request by mavasani**
We used to only track reference types and strings in PointsToAnalysis, which in turns leads to `ConfiguredAsyncDisposable` struct type returned from `TaskAsyncEnumerableExtensions.ConfigureAwait(this IAsyncDisposable, bool)` not being tracked, and hence the `await using` statement doesn't mark the original disposable object as being disposed.

Fixes #6765
Fixes #6512

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs [hunk 1]
```diff
@@ -49,6 +59,8 @@ private PointsToAnalysisData(PointsToAnalysisData data1, PointsToAnalysisData da
             data1.AssertValidPointsToAnalysisData();
             data2.AssertValidPointsToAnalysisData();
             AssertValidPointsToAnalysisData();
```
Comment (Youssef1313) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysisData.cs:61]: This assert uses `_isDisposable` I think, but we set `_isDisposable` after the assert is done. Should it be moved earlier? Are we missing a test case where the assert should fail with the current code? or does assigning before the assert not matter at all?

**Review by Youssef1313 — APPROVED** [review]

**Comment by mavasani** [comment]
Thank you as always @Youssef1313
