### PR TITLE
Fix CA1063 and CA1821 to handle expression bodied finalizers

### LINKED ISSUE #1788: CA1063 and CA1821 produce false positives with expression bodies
#### Analyzer package
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.6.1

#### Diagnostic ID

[CA1063](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1063-implement-idisposable-correctly)
[CA1821](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1821-remove-empty-finalizers)

#### Repro steps

This triggers a warning
```csharp
public class SomeTestClass : IDisposable
{
    private readonly Stream resource = new MemoryStream(1024);

    public void Dispose()
    {
        this.Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool dispose)
    {
        if (dispose)
        {
            this.resource.Dispose();
        }
    }

    ~SomeTestClass() => this.Dispose(false);
}
```
This does not trigger a warning
```csharp
public class SomeTestClass : IDisposable
{
    private readonly Stream resource = new MemoryStream(1024);

    public void Dispose()
    {
        this.Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool dispose)
    {
        if (dispose)
        {
            this.resource.Dispose();
        }
    }

    ~SomeTestClass()
    {
        this.Dispose(false);
    }
}
```

#### Expected behavior
Analyzers works with expression bodies

#### Actual behavior
Analyzers does not work with expression bodies

### LINKED ISSUE #1804: RemoveEmptyFinalizers (CA1821) does not handle expression bodied finalizers
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

Example: v1.1.0 and v2.6.1

#### Diagnostic ID

Example: [CA1821](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1821-remove-empty-finalizers?view=vs-2017)

#### Repro steps

Source code:
```
    public class Class1 { }

    public class Class2
    {
        private Class1 _field;
        ~Class2() => _field = null;
    }
```

#### Expected behavior
No CA1821

#### Actual behavior
CA1821 is reported

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #1788 
Fixes #1804

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs [hunk 1]
```diff
@@ -13,39 +14,79 @@ internal class CSharpRemoveEmptyFinalizersAnalyzer : AbstractRemoveEmptyFinalize
     {
         protected override bool IsEmptyFinalizer(SyntaxNode methodBody, CodeBlockAnalysisContext analysisContext)
         {
-            var destructorDeclaration = (DestructorDeclarationSyntax)methodBody;
+            // TODO: Switch the analyzer to be IOperation based to avoid handling different syntactic constructs.
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs]: 💡 Should move this to be an issue instead of a comment

File: src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs [hunk 2]
```diff
@@ -13,39 +14,79 @@ internal class CSharpRemoveEmptyFinalizersAnalyzer : AbstractRemoveEmptyFinalize
...
 
-            if ((destructorDeclaration?.Body?.Statements.Count ?? 0) == 0)
+            var destructorDeclaration = (DestructorDeclarationSyntax)methodBody;
+            if (destructorDeclaration.Body != null)
             {
-                return true;
+                // Bail out for error case where both expression and block body are non-null.
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs]: ❔ Would this violate an invariant of the data model? i.e. can we replace this check with a simple `Debug.Assert` call?

File: src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs]: Filed https://github.com/dotnet/roslyn-analyzers/issues/1964 and remove the comment.

File: src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/CSharp/QualityGuidelines/CSharpRemoveEmptyFinalizersAnalyzer.cs]: This is actually a valid possibility for error cases - in fact our IOperation tree also exposes 2 operation blocks for this case and we have IOperation unit tests to verify there are 2 operation blocks. Added unit test `CA1821CSharpRemoveEmptyFinalizers_ErrorCodeWithBothBlockAndExpressionBody`
