### PR TITLE
No longer raises CA1065 for exceptions derived from whitelisted exceptions

### LINKED ISSUE #1537: CA1065 Triggers on ArgumentOutOfRange inside indexer, but shouldn't
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/2.6.0)

#### Analyzer

DoNotRaiseExceptionsInUnexpectedLocationsAnalyzer

#### Repro steps

```csharp
public PositiveNumbers this[int index]
{
    get
    {
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(index));
        }
        return index;
    }
}
```

#### Expected behavior

CA1065 is not raised, as per [Property design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property) and ["Framework Design Guidelines"](https://stackoverflow.com/a/1488498/879243)

#### Actual behavior

CA1065 is raised.

#### Notes

The design of this analyzer accommodates for excluding certain exceptions. We're excluding `ArgumentException`, but not its descendant type `ArgumentOutOfRangeException` nor `ArgumentNullException`

```csharp
                new MethodCategory(IsIndexerGetter, true,
                    PropertyGetterRule,
                    WellKnownTypes.InvalidOperationException(compilation), WellKnownTypes.NotSupportedException(compilation),
                    WellKnownTypes.ArgumentException(compilation), WellKnownTypes.KeyNotFoundException(compilation)),
```

### PR DESCRIPTION
**Pull request by AmadeusW**
Fixes #1537 

As outlined in [Property design guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property) and ["Framework Design Guidelines"](https://stackoverflow.com/a/1488498/879243), it's ok to throw exceptions from the indexer properties.

This PR fixes this and other shortcomings of CA1065 by allowing exceptions that derive from the whitelisted exceptions.

With this PR, this analyzer won't raise alarm about throwing `ArgumentOutOfRangeException`, `ArgumentNullException` and `MyCustomArgumentException : ArgumentException` in indexers, as well as throwing exceptions derived from whitelisted exceptions in other situations.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs [hunk 1]
```diff
@@ -102,7 +102,7 @@ public override void Initialize(AnalysisContext analysisContext)
                         if (thrownExceptionType != null && thrownExceptionType.DerivesFrom(exceptionType))
                         {
                             // If no exceptions are allowed or if the thrown exceptions is not an allowed one..
-                            if (methodCategory.AllowedExceptions.IsEmpty || !methodCategory.AllowedExceptions.Contains(thrownExceptionType))
+                            if (methodCategory.AllowedExceptions.IsEmpty || !methodCategory.AllowedExceptions.Any(n => thrownExceptionType.DerivesFrom(n)))
```
Comment (333fred) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs]: For proper Fxcop compat, we'll need to use IsAssignableTo rather than DerivesFrom. IsAssignableTo is currently contained solely in https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DefineAccessorsForAttributeArguments.cs#L95, could you please pull out the protected implementation into AnalyzerUtilities (an extension on ITypeSymbol should work). FxCop version: http://index/?query=DoNotRaise&rightProject=DesignRules&file=DoNotRaiseExceptionsInUnexpectedLocations.cs&line=116.

Comment (AmadeusW) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotRaiseExceptionsInUnexpectedLocations.cs]: Done. ITypeSymbolExtensions now uses CSharp and VB namespaces, however, in my opinion that's better than repeating the code.

File: src/Utilities/Extensions/ITypeSymbolExtensions.cs [hunk 2]
```diff
@@ -103,6 +105,14 @@ public static bool DerivesFrom(this ITypeSymbol symbol, ITypeSymbol candidateBas
             return false;
         }
 
+        public static bool IsAssignableTo(this ITypeSymbol fromSymbol, ITypeSymbol toSymbol, Compilation compilation)
+        {
+            return fromSymbol != null
+                && toSymbol != null
+                && ((compilation is CSharpCompilation && ((CSharpCompilation)compilation).ClassifyConversion(fromSymbol, toSymbol).IsImplicit)
```
Comment (mavasani) [inline src/Utilities/Extensions/ITypeSymbolExtensions.cs]: Please don't add types from language specific code analysis assemblies into the core utilities. This will cause a C# analyzer to unnecessarily load VB CodeAnalysis assembly and vice versa. This is the primary reason for the current implementation being cloned in both language specific analyzers.

We can make a change similar to the one you are proposing once Roslyn exposes conversion information at the language agnostic layer.

Comment (AmadeusW) [reply src/Utilities/Extensions/ITypeSymbolExtensions.cs]: Makes sense. How would I go about 333fred's request to move IsAssignableTo into an extension? Should I instead duplicate IsAssignableTo code and move it into the DoNotRaiseExceptionInUnexpectedLocations?

Comment (mavasani) [reply src/Utilities/Extensions/ITypeSymbolExtensions.cs]: You can either keep the current strategy of cloning the code into each analyzer OR create two new shared projects CSharpAnalyzerUtilities and BasicAnalyzerUtilities and put language specific helpers there.

**Comment by mavasani** [comment]
Ping @AmadeusW - please let us know if you would be able to address the feedback and resolve merge conflicts.

**Comment by AmadeusW** [comment]
I think this will be fine now.
