### PR TITLE
Fixes for CA2227: Collection properties should be read only

### LINKED ISSUE #1900: CA2227:CollectionPropertiesShouldBeReadOnly is raised on immutable collection properties
## Analyzer package
[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

## Package Version

v2.6.2

## Diagnostic ID

[CA2227:CollectionPropertiesShouldBeReadOnly](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only)

## Repro steps
Create a new project with the following:

### Sample.cs
```csharp
using System.Collections.Immutable;

public sealed class Sample
{
    public string Name { get; set; }

    // Line in question:
    public ImmutableArray<byte> ImmutableData { get; set; }
}
```

### ConsoleApp0.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <LangVersion>7.2</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.6.2" />
  </ItemGroup>

</Project>
```

## Expected behavior
I feel like members with types from `System.Collections.Immutable`, such as the one on the "line in question", should not raise `CA2227:CollectionPropertiesShouldBeReadOnly`.

I agree with raising it for `System.Collections.ObjectModel.ReadOnlyCollection<T>`, but the contract of `System.Collections.Immutable` types is a promise that once you have an instance of an immutable collection, **nobody** should be able to edit its contents.

## Actual behavior
The "line in question" raises `CA2227:CollectionPropertiesShouldBeReadOnly`.

### PR DESCRIPTION
**Pull request by mavasani**
1. Ensure that we fire for types implementing `ICollection<T>`. Currently implementation only checked for the non-generic `ICollection`.
2. Ensure that we don't fire for immutable collection types - the rule is only intended for properties of non-immutable types.

Fixes #1900

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs [hunk 1]
```diff
@@ -80,8 +90,29 @@ public static void AnalyzeSymbol(SymbolAnalysisContext context, INamedTypeSymbol
...
+            if (!Inherits(property.Type, iCollectionType) && !Inherits(property.Type, genericICollectionType))
+            {
+                return;
+            }
+            
+            // exclude Immutable collections
+            // see https://github.com/dotnet/roslyn-analyzers/issues/1900 for details
+            if (property.Type.IsSealed &&
+                property.Type.Name.StartsWith("Immutable", StringComparison.Ordinal) &&
+                property.Type.ContainingNamespace?.ToDisplayString() == "System.Collections.Immutable")
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs]: ❗️ I'm not especially happy with this implementation.

1. It fails to account for a property of type `IImmutableList<T>`, which seems to fit directly in the intended scenarios
2. It fails to account for the immutable collections in [tunnelvisionlabs/dotnet-trees](https://github.com/tunnelvisionlabs/dotnet-trees), which indirectly fits the intended scenarios

It seems both cases could be handled by excluding properties whose static type implements an immutable collection interface.

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs [hunk 2]
```diff
@@ -101,7 +132,8 @@ public static void AnalyzeSymbol(SymbolAnalysisContext context, INamedTypeSymbol
 
         private static bool Inherits(ITypeSymbol symbol, ITypeSymbol baseType)
         {
-            return symbol == null ? false : symbol.Inherits(baseType);
+            Debug.Assert(baseType.Equals(baseType.OriginalDefinition));
+            return symbol == null ? false : symbol.OriginalDefinition.Inherits(baseType);
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs]: 💡

```suggestion
            return symbol?.OriginalDefinition.Inherits(baseType) ?? false;
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs [hunk 3]
```diff
@@ -194,6 +207,48 @@ class A
...
+
+public class A
+{
+    public string Name { get; set; }
+}
+");
+        }
+
+        [Fact, WorkItem(1900, "https://github.com/dotnet/roslyn-analyzers/issues/1900")]
+        public void CSharp_CA2227_ReadOnlyCollection()
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs]: ❗️ Should add tests for [`ReadOnlyCollection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.readonlycollection-1?view=netframework-4.7.2) and [`ReadOnlyDictionary<TKey, TValue>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.readonlydictionary-2?view=netframework-4.7.2) regardless of how we choose to handle them.

Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs]: 💡 This test name is misleading since it checks for `IReadOnlyCollection<T>` and not `ReadOnlyCollection<T>`.

```suggestion
        public void CSharp_CA2227_IReadOnlyCollection()
```

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs [hunk 4]
```diff
@@ -183,7 +196,7 @@ public void CSharp_CA2227_Indexer()
             VerifyCSharp(@"
 using System;
 
-class A
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnlyTests.cs]: 😨 Scary this can happen so easily. I don't have a good way to avoid it either.

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs (hunk 1 above)
Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs]: Ah good points - I was being lazy to enumerate all the immutable interfaces. I will specifically add checks for the interfaces listed [here](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable?view=netcore-2.2#interfaces) instead of this heuristic.

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CollectionPropertiesShouldBeReadOnly.cs]: Fixed in https://github.com/dotnet/roslyn-analyzers/pull/1957/commits/84ba7cd41b7688c86e5b9e569990187b39aa5615

**Comment by mavasani** [comment]
@sharwell Addressed feedback, thanks.
