### PR TITLE
Enable RS0046 and fix related issues

### LINKED ISSUE #3891: Enable RS0046 diagnostic on the repo
I'd do this one separately, since it's a noisy change.

_Originally posted by @sharwell in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQ1ODgxNTMwOA==/comments/review_comment_

Following PR #3888 the diagnostic `RS0046` shall be enabled.

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #3891

### CODE REVIEW

File: src/Utilities/Compiler/HashUtilities.cs [hunk 1]
```diff
@@ -9,7 +9,7 @@ namespace Analyzer.Utilities
 {
     internal static class HashUtilities
     {
-        internal static int GetHashCodeOrDefault(this object? objectOpt) => objectOpt?.GetHashCode() ?? 0;
+        internal static int GetHashCodeOrDefault(this object? @object) => @object?.GetHashCode() ?? 0;
```
Comment (sharwell) [inline src/Utilities/Compiler/HashUtilities.cs:12]: For similarity with `EqualityComparer<T>.GetHashCode(T)`

```suggestion
        internal static int GetHashCodeOrDefault(this object? obj) => obj?.GetHashCode() ?? 0;
```

**Comment by Evangelink** [comment]
@sharwell Could you merge when you have some time? Thx
