### PR TITLE
Fix NRE in RethrowToPreserveStackDetailsAnalyzer

### LINKED ISSUE #2167: NullReferenceException in CSharpRethrowToPreserveStackDetailsAnalyzer
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
and
[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v2.6.3, v2.6.4-dev, and [v2.9.0-beta1-63118-01](https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeQuality.Analyzers)

#### Diagnostic ID

CSharpRethrowToPreserveStackDetailsAnalyzer

#### Repro steps

Reproduced using VS 15.9.4 and VS 16.0.0 Preview 4.

1. New c# project
1. Add Microsoft.CodeAnalysis.FxCopAnalyzers package (or Microsoft.CodeQuality.Analyzers if using .net core)
1. Run the analyzer against the following code:

```
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        private void CSharpRethrowToPreserveStackDetailsAnalyzer_Fail(Exception exception)
        {
            try
            {
            }
            catch
            {
                var finalException = new InvalidOperationException("barf", exception);
                throw finalException;
            }
        }
    }
}
```

#### Expected behavior
Analyzer runs properly

#### Actual behavior

> Warning  AD0001  Analyzer 'Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines.CSharpRethrowToPreserveStackDetailsAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.   ClassLibrary1  1   Active   Analyzer 'Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines.CSharpRethrowToPreserveStackDetailsAnalyzer' threw the following exception:
> 'Exception occurred with following context:
> Compilation: ClassLibrary1
> SyntaxTree: C:\Users\robs\Documents\Visual Studio\Projects\ClassLibrary1\Class1.cs
> SyntaxNode: throw finalException; [ThrowStatementSyntax]@[1521..1542) (45,16)-(45,37)
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.CodeQuality.CSharp.Analyzers.QualityGuidelines.CSharpRethrowToPreserveStackDetailsAnalyzer.AnalyzeNode(SyntaxNodeAnalysisContext context)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44\`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple\`2 data)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action\`1 analyze, TArg argument, Nullable\`1 info)
> \-----
> '.

### PR DESCRIPTION
**Pull request by genlu**
Fix #2167

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs [hunk 1]
```diff
@@ -356,6 +356,44 @@ End Class
...
+using System;
+
+class Program
+{
+    void CatchAndRethrow(Exception exception)
+    {
+        try
+        {            
+        }
+        catch
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs]: ❔ Do we already have a test for `catch (Exception)`? If not, it might be good to add one at the same time.

Comment (genlu) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/RethrowToPreserveStackDetailsTests.cs]: Added
