### PR TITLE
Fixes #948

### LINKED ISSUE #948: CollectionPropertiesShouldBeReadOnly (CA2227) reports on DataMembers
#### Analyzer package
Microsoft.ApiDesignGuidelines.Analyzers

#### Analyzer
CA2227: CollectionPropertiesShouldBeReadOnly

#### Repro steps
CA2227 is reported on the `Gates` property in the next class.

```csharp
    [DataContract(Namespace = "", Name = "NetworkConfiguration")]
    public sealed class NetworkConfigurationXml
    {
        [DataMember]
        public Collection<GateSettingsXml> Gates { get; set; }
    }
```

#### Expected behavior
In this case, the serialization framework requires a public setter. It would be nice to special-case methods that are decorated with `DataMemberAttribute` or similar serialization annotations.

#### Actual behavior
CA2227 is reported on methods that are decorated with `DataMemberAttribute`.

### PR DESCRIPTION
**Pull request by bkoelman**

### CODE REVIEW

**Comment by mavasani** [comment]
:+1: Thanks for the contribution!

File: src/Test/Utilities/DiagnosticAnalyzerTestBase.cs [hunk 1]
```diff
@@ -31,6 +32,7 @@ public abstract class DiagnosticAnalyzerTestBase
         private static readonly MetadataReference s_immutableCollectionsReference = MetadataReference.CreateFromAssemblyInternal(typeof(ImmutableArray<int>).Assembly);
         private static readonly MetadataReference s_systemDiagnosticsDebugReference = MetadataReference.CreateFromAssemblyInternal(typeof(System.Diagnostics.Debug).Assembly);
         private static readonly MetadataReference s_systemDataReference = MetadataReference.CreateFromAssemblyInternal(typeof(System.Data.DataSet).Assembly);
+        private static readonly MetadataReference s_SystemRuntimeSerializationReference = MetadataReference.CreateFromAssemblyInternal(typeof(DataMemberAttribute).Assembly);
```
Comment (srivatsn) [inline src/Test/Utilities/DiagnosticAnalyzerTestBase.cs]: Instead of adding a reference, the test could just define the attribute - since we are only checking by name that would succeed. It's nicer to keep the set of references in the test framework to a minimum.

Comment (bkoelman) [inline src/Test/Utilities/DiagnosticAnalyzerTestBase.cs]: Yes, I agree that's better. Added commit for that. Thanks.

**Comment by srivatsn** [comment]
👍
