### PR TITLE
Ignore GetType in CA1721 checks.

### LINKED ISSUE #1374: CA1721 (Property names should not match get methods) fires on every type that has a property named Type
#### Analyzer package

Microsoft.CodeQuality.Analyzers

#### Analyzer

PropertyNamesShouldNotMatchGetMethodsAnalyzer

#### Repro steps

```
class T { }
class C
{
    public T Type { get; }
}
```

#### Expected behavior
No CA1721. FxCop does not fire for this case.

#### Actual behavior
`warning CA1721: The property name 'Type' is confusing given the existence of method 'GetType'. Rename or remove one of these members.`

We should ignore `Object.GetType` in our analysis. Otherwise, this rule is just noise.

### PR DESCRIPTION
**Pull request by 333fred**
Fixes #1374.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs [hunk 1]
```diff
@@ -82,6 +82,13 @@ private static void AnalyzeSymbol(SymbolAnalysisContext context)
                 var exposedMembers = type.GetMembers(identifier).Where(member => ExposedAccessibilities.Contains(member.DeclaredAccessibility));
                 foreach (var member in exposedMembers)
                 {
+                    // Ignore Object.GetType, as it's commonly seen and Type is a commonly-used property name.
+                    if (member.ContainingType.SpecialType == SpecialType.System_Object &&
+                        member.Name == "GetType")
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: :bulb: `nameof` here would be referring to the correct method

Comment (333fred) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: Updated.
