### PR TITLE
Fix and unskip tests blocked by #881

### LINKED ISSUE #881: Allow unit tests to modify the Project created by the Verify methods
**Motivation**: I'm writing analyzer CA1812, AvoidUninstantiatedInternalClasses. The idea is if you have an internal class, and nobody in the assembly it lives in ever instantiates it, then it's useless, because nobody outside of the assembly can see it to instantiate it.

There are certain exceptions; for example, we don't report a diagnostic if the class contains the program entry point:

```
internal class Program
{
    private static void Main() {}
}
```

If this code occurs in a .exe, it is the program entry point, and we don't report it. But if it occurs in a .dll, it can't be the program entry point, and we do report it.

The problem is, you can't unit test this. The unit test infrastructure supplies a set of `static` `Verify` methods on the `DiagnosticAnalyzerTestBase` class. Ultimately, these methods create a `Project` with a default set of compilation options (specifically, `OutputKind.DynamicallyLinkedLibrary`), and there's no way to override this (because the methods are `static`).

To fix this, we'd either have to make all those methods instance methods and supply some overrides, or we'd have to plumb another, optional parameter down through the entire infrastructure, starting at the `Verify` methods. But that's not possible, given the current signature of the `Verify` methods, which is

```
protected void VerifyCSharp(string source, params DiagnosticResult[] expected)
```

Since the last parameter is a `params`, we can't add anything after it, and adding a parameter before it would break every test in the world.

### PR DESCRIPTION
**Pull request by 333fred**
Fixes #881.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs [hunk 1]
```diff
@@ -821,7 +821,7 @@ private void VerifyBasic(string source, string testProjectName, params Diagnosti
         private void Verify(string source, string language, DiagnosticAnalyzer analyzer, string testProjectName, DiagnosticResult[] expected)
         {
             var sources = new[] { source };
-            var diagnostics = GetSortedDiagnostics(sources.ToFileAndSource(), language, analyzer, addLanguageSpecificCodeAnalysisReference: true, projectName: testProjectName);
+            var diagnostics = GetSortedDiagnostics(sources.ToFileAndSource(), language, analyzer, null, addLanguageSpecificCodeAnalysisReference: true, projectName: testProjectName);
```
Comment (ivanbasov) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/IdentifiersShouldNotContainUnderscoresTests.cs]: >null [](start = 98, length = 4)

parameter name would be helpful here

File: src/Test.Utilities/DiagnosticAnalyzerTestBase.cs [hunk 2]
```diff
@@ -216,78 +216,98 @@ private static DiagnosticResultLocation[] ParseResultLocations(string defaultPat
 
         protected void VerifyCSharpUnsafeCode(string source, params DiagnosticResult[] expected)
         {
-            Verify(new[] { source }.ToFileAndSource(), LanguageNames.CSharp, GetCSharpDiagnosticAnalyzer(), DefaultTestValidationMode, true, expected);
+            Verify(new[] { source }.ToFileAndSource(), LanguageNames.CSharp, GetCSharpDiagnosticAnalyzer(), DefaultTestValidationMode, true, null, expected);
```
Comment (ivanbasov) [inline src/Test.Utilities/DiagnosticAnalyzerTestBase.cs]: >null [](start = 141, length = 4)

there same as above and below: parameter name will be helpful for null/true/false
