### PR TITLE
Do not fire CA1608 if the CancellationToken is the first parameter of an extension method

### LINKED ISSUE #1491: CA1068 shouldn't fire on extensions methods of CancellationToken
#### Analyzer

CA1068 

#### Repro steps

1. See: https://github.com/dotnet/project-system/pull/3060/files/cf65d664b047803252fba07115fcd6244db30531#diff-ecae52b00e17f99d88602b6fbfe7cb74R35

``` C#

internal static CancellationTokenRegistration Register(this CancellationToken token, string foobar)
{
}

```

#### Expected behavior

Not to fire

#### Actual behavior

Fires

### PR DESCRIPTION
**Pull request by jamesqo**
Fixes #1491

/cc @333fred, @mavasani

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs [hunk 1]
```diff
@@ -218,6 +218,28 @@ class T : I
...
         }
 
+        [Fact, WorkItem(1491, "https://github.com/dotnet/roslyn-analyzers/issues/1491")]
+        public void NoDiagnosticOnCancellationTokenExtensionMethod()
+        {
+            var test = @"
+using System.Threading;
+static class C1
+{
+    public static void M1(this CancellationToken p1, object p2)
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs]: :bulb: It would be good to add a new test where a `CancellationToken` is passed as the second argument of a 3-argument extension method (a diagnostic should be reported in this case).

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs [hunk 2]
```diff
@@ -74,21 +74,29 @@ public override void Initialize(AnalysisContext context)
                             }
                         }
 
+                        // Skip ref, out and ref readonly parameters. By convention, they come at the end of a method signature.
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: 💭 I can't say I agree with the second sentence. I would prefer this comment be updated to the following, intentionally leaving out the reason why this occurs:

> Ignore parameters passed by reference when they appear at the end of the parameter list

Comment (jamesqo) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: @sharwell What is the reason, if not by convention?

Comment (sharwell) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs]: By the styles I'm most familiar with, they would not come last. I'm not sure why this case is excluded from analysis, but removing the special case is beyond the scope of this pull request.

**Comment by jamesqo** [comment]
@333fred / @sharwell Made changes per PR feedback. Is this good to go?

**Comment by 333fred** [comment]
@jamesqo thanks!
