### PR TITLE
Fix false positives for Dispose rules

### LINKED ISSUE #2245: CA2000 false positives with out parameters
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.0

#### Diagnostic ID

[CA2000](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope)

#### Repro steps

1. Try to dispose a bunch of disposable objects from a concurrent queue:

```c#
while (Handles.TryDequeue(out var handle))
                handle.Dispose();
```

-or-

1. Try to dispose a handle obtained via an out parameter using the IDisposable pattern

```c#
readonly CustomNativeHandle _handle;

internal TestConstructor()
{
    NativeMethods.GetHandle(out _handle);
}

public void Dispose()
{
    _handle.Dispose();
}
```

#### Expected behavior

No warning - both of these dispose of handles correctly, AFAICT. No warnings under last stable release.

#### Actual behavior

CA2000 warning

### LINKED ISSUE #2306: CA2213 False positive when Dispose is implemented in .Designer.cs file
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

2.9.1

#### Diagnostic ID

CA2213

#### Repro steps

Create a .net framework console app project.
Add FxCopAnalyzers
Add a Windows Service, for example Service1
Add a field with a disposable type to Service1.cs
Modify Dispose(bool) in Service1.Designer.cs to dispose 

#### Expected behavior
Does not trigger CA2213

#### Actual behavior
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA2213	'Service1' contains field 'timer' that is of IDisposable type 'Timer', but it is never disposed. Change the Dispose method on 'Service1' to call Close or Dispose on this field.	ConsoleApp1	ConsoleApp1\Service1.cs	33	Active

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #2306: CA2213 (DisposableFieldsShouldBeDisposed)
1. https://github.com/dotnet/roslyn-analyzers/commit/ba955a4f1204771477e64be8c4ff68b554e7151c: Ensure that analysis is executed on generated code to account for Dispose implementation in generated code files.

Fixes #2245 (2 scenarios): CA2000 (DisposeObjectsBeforeLosingScope)
1. https://github.com/dotnet/roslyn-analyzers/commit/74dd361b5ee472f4aafd7eb91dc31755819c5056: Handle escaping of disposable creations through ref/out field arguments.
2. https://github.com/dotnet/roslyn-analyzers/commit/5f3209af3fe77d83a5f2df9b20ac8892bbf7cf91: Prevent false positives for disposable `out` arguments of invocations within conditional expression. We assume that an `out` argument of an invocation returning false within a conditional branch is invalid and does not require disposing.

### CODE REVIEW

**Comment by mavasani** [comment]
Merging this in as we want to start testing the latest drop from this branch for 2.9.2 release. I'll address any PR feedback with a follow-up change.

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs [hunk 1]
```diff
@@ -351,8 +343,39 @@ void PostProcessEscapedArgument()
                         var pointsToValue = GetPointsToAbstractValue(operation.Value);
                         HandlePossibleEscapingOperation(operation, pointsToValue.Locations);
                     }
+                    else if (FlowBranchConditionKind == ControlFlowConditionKind.WhenFalse &&
+                        operation.Parameter.RefKind == RefKind.Out &&
+                        operation.Parent is IInvocationOperation invocation &&
+                        invocation.TargetMethod.ReturnType.SpecialType == SpecialType.System_Boolean)
+                    {
```
Comment (dotpaul) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis/DisposeAnalysis.DisposeDataFlowOperationVisitor.cs]: Can't think of anything of the top of my head, but this seems like a heuristic to keep an eye on in the future.  Otherwise LGTM.
