### PR TITLE
Fix #1088 CA1721 does not consider method/property accessibility

### LINKED ISSUE #1088: CA1721 does not consider method/property accessibility
#### Analyzer package

Microsoft.ApiDesignGuidelines.Analyzers

#### Analyzer

PropertyNamesShouldNotMatchGetMethods

#### Repro steps

```cs
public class Person
{
    // public property, private method
    public string Name
    {
        get { return "Roslyn"; }
    }

    private string GetName()
    {
        return Name;
    }

    // private property, public method (admittedly contrived)
    private int Age
    {
        get { return 30; }
    }

    public int GetAge()
    { 
        return Age;
    }
}
```

#### Expected behavior

Neither scenario above should cause CA1721 to fire because the rule states "The name of a **public** or **protected** member starts with 'Get' and otherwise matches the name of a **public** or **protected** property."

#### Actual behavior

Fires

### PR DESCRIPTION
**Pull request by pakdev**
Did a decent amount of refactoring as well. What's the deal with the bad unit test names?

### CODE REVIEW

**Comment by pakdev** [comment]
@mavasani or @srivatsn, are you guys monitoring this repo? Could one of you guys review my changes or contact someone that could? There are also some other PRs that could use some love.

**Comment by mavasani** [comment]
@pakdev Thank you so much for the PRs and sorry for the delay in the response.

We are currently heads down wrapping up on VS2017 release and hence haven't been able to move this repo forward as fast as we would have liked. Once the release wraps up, we are planning to revive this repo and that point will look at the PRs. Thank you again for the contribution.

**Comment by pakdev** [comment]
Hey @mavasani, any word about when this repo will be revived? It's frustrating to have to resolve a these merge conflicts for all my PRs.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs [hunk 1]
```diff
@@ -16,25 +16,24 @@ namespace Microsoft.ApiDesignGuidelines.Analyzers
...
-        private static readonly LocalizableString s_localizableMessage = new LocalizableResourceString(nameof(MicrosoftApiDesignGuidelinesAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsMessage), MicrosoftApiDesignGuidelinesAnalyzersResources.ResourceManager, typeof(MicrosoftApiDesignGuidelinesAnalyzersResources));
-        private static readonly LocalizableString s_localizableDescription = new LocalizableResourceString(nameof(MicrosoftApiDesignGuidelinesAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsDescription), MicrosoftApiDesignGuidelinesAnalyzersResources.ResourceManager, typeof(MicrosoftApiDesignGuidelinesAnalyzersResources));
+        private static readonly LocalizableString LocalizableTitle = new LocalizableResourceString(nameof(MicrosoftApiDesignGuidelinesAnalyzersResources.PropertyNamesShouldNotMatchGetMethodsTitle), MicrosoftApiDesignGuidelinesAnalyzersResources.ResourceManager, typeof(MicrosoftApiDesignGuidelinesAnalyzersResources));
```
Comment (sharwell) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: ❗️ Don't rename these (at least not as part of this review). The rest of the project uses the other naming convention.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs [hunk 2]
```diff
@@ -50,61 +49,55 @@ private static void AnalyzeSymbol(SymbolAnalysisContext context)
...
-                            break;
-                        }
+                        diagnostic = Diagnostic.Create(Rule, symbol.Locations[0], symbol.Name, identifier);
+                        break;
                     }
 
-                    //if no match found iterate to next in outer for loop
-                    if (!matchFound)
+                    // If the declared type is a method, was a matching property found? Although this
+                    // check seems redundant, it's the only way to catch violations of this rule when the
```
Comment (sharwell) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: ❗️ This comment is misleading. The containing type check isn't the "only way" to catch violations of the rule, but rather is included so we don't report two diagnostics for the same situation in the same type. When the property and method are in the same type, we intentionally only report the diagnostic on the property.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs [hunk 3]
```diff
@@ -50,61 +49,55 @@ private static void AnalyzeSymbol(SymbolAnalysisContext context)
...
+                    // method is declared in a more derived implementation.
+                    if (symbol.Kind == SymbolKind.Method &&
```
Comment (sharwell) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: :bulb: Consider splitting before the operator (moving `&&` to the next line here, and similar for other places that you changed) per the discussion in DotNetAnalyzers/StyleCopAnalyzers#748.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs (hunk 1 above)
Comment (pakdev) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: Yeah, after submitting this PR, I found the [Roslyn contribution guidelines](https://github.com/dotnet/roslyn/wiki/Contributing-Code) which linked to this page: [C# Coding Style](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md). It states "Prefix static fields with `s_`". Yet, all of the analyzers I've seen don't apply this to `Rule`s. Is that intentional?

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs (hunk 2 above)
Comment (pakdev) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: My comment is not referring to the `symbol.ContainingType.Equals(type)` condition. Imagine this is our hierarchy:

Type | Method(s) | Propertie(s)
----- | ---------- | -----------
Parent | GetName | 
Child | | Name, Age
Grandchild | GetAge |

If we only had the first check (`symbol.Kind == SymbolKind.Property && member.Kind == SymbolKind.Method`), we would get a diagnostic for Child's Name property, but not Age. That's why we need this "seemingly redundant" check. Only comparing properties against ascendant members might not descend into the hierarchy deep enough. But, with this check, we compare Grandchild's GetAge against Child's Age and get a diagnostic.

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs (hunk 3 above)
Comment (pakdev) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: Will do

File: src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs (hunk 2 above)
Comment (sharwell) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: In that hierarchy, wouldn't the warnings be reported on `Child.Name` and `Grandchild.GetAge`?

Comment (sharwell) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: 💭 I don't understand what about this test would be considered redundant. The only part that made me look twice was the `ContainingType` check. Otherwise it seems clear that the first one is the case where `symbol` is a property and the second case handles `symbol` as a method.

Comment (pakdev) [inline src/Microsoft.ApiDesignGuidelines.Analyzers/Core/PropertyNamesShouldNotMatchGetMethods.cs]: Ahh, I was thinking if I checked all properties against all methods, there was no need to do the reverse. But, I overlooked the fact that I wouldn't be checking all properties. If Child was in its own file and defined a method called `GetTitle`, I wouldn't iterate through the properties of Parent to find `Title`. Thus, I'll remove my comment.

To answer your question, where the warnings would be reported depends on how those classes are distributed into files. If they were each in their own file, then Child.cs would report `Name` and Grandchild.cs would report `GetAge`.

**Comment by pakdev** [comment]
@sharwell can you validate that I addressed your feedback?

**Comment by sharwell** [comment]
:memo: I confirmed that my feedback was addressed. I went on vacation between then and now so I didn't verify that my previous review was a comprehensive review of the entire pull request. 😄

**Comment by pakdev** [comment]
@mavasani Can you pull this?
