### PR TITLE
Check if the syntax list has any elements before calling .First()

### LINKED ISSUE #287: Error from BasicDoNotUseVerbatimCrefsAnalyzer
'Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'. BasicCodeAnalysis 1 Analyzer 'Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer' threw the following exception:
'System.InvalidOperationException: Operation is not valid due to the current state of the object.
at Microsoft.CodeAnalysis.SyntaxTokenList.First()
at Roslyn.Diagnostics.Analyzers.Documentation.DoNotUseVerbatimCrefsAnalyzer.ProcessAttribute(SyntaxNodeAnalysisContext context, SyntaxTokenList textTokens)
at Roslyn.Diagnostics.CodeFixes.VisualBasic.BasicDoNotUseVerbatimCrefsAnalyzer.AnalyzeXmlAttribute(SyntaxNodeAnalysisContext context)
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.b__1()
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

### PR DESCRIPTION
**Pull request by jmarolf**
Fixes #287

### CODE REVIEW

**Comment by jmarolf** [comment]
@genlu @tmeschter @srivatsn

File: src/Roslyn/Core/Documentation/DoNotUseVerbatimCrefsAnalyzer.cs [hunk 1]
```diff
@@ -37,6 +37,11 @@ public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
...
         protected void ProcessAttribute(SyntaxNodeAnalysisContext context, SyntaxTokenList textTokens)
         {
+            if (!textTokens.Any())
+            {
+                return;
+            }
+
             var token = textTokens.First();
 
             if (token.Span.Length >= 2)
```
Comment (genlu) [inline src/Roslyn/Core/Documentation/DoNotUseVerbatimCrefsAnalyzer.cs]: This is unrelated to the fix, but I think these hardcoded numbers deserve to have a comment :)

**Comment by genlu** [comment]
:+1:
