### PR TITLE
Chloduan/ca3075 xml document secure default xml resolver after net452

### LINKED ISSUE #1150: False positives in DoNotUseInsecureDtdProcessing
#### Analyzer package

Microsoft.NetFramework.Analyzers

#### Analyzer

DoNotUseInsecureDtdProcessing

#### Repro steps

a) var xmlDoc = new XmlDocument();
b) xmlDoc.Load (PathToXmlFile);
c) var reader = new XmlTextReader (PathToXmlFile);

Build with .NET 4.5.2 and higher

#### Expected behavior

No warnings

#### Actual behavior

Warnings like:
a) Warning	CA3075	An XmlDocument instance is created without setting its XmlResolver property to a secure value.
b) Warning	CA3075	Unsafe overload of 'Load' method.
c) Warning	CA3075	XmlTextReader instance created with insecure default settings.

#### Notes
@qinxgit There are comments in the analyzer like "for .NET framework >= 4.5.2, the default value for XmlResolver property is null", dotnet version is checked and IsSecureResolver is set to true if >= 4.5.2. However in XmlTextReader case for example it checks for
```
                    if (!(env.IsXmlResolverSet | env.IsSecureResolver) ||
                        !(env.IsDtdProcessingSet | env.IsDtdProcessingDisabled))
                    {
```
Do I miss something? Setting resolver to null by default effectively prevents XXE.

BTW, this difference between .NET 4.5.1 and .NET 4.5.2 is not covered by unit tests. There are some tests like
```
using System;
using System.Reflection;               
using System.Xml;   

[assembly: global::System.Runtime.Versioning.TargetFrameworkAttribute("".NETFramework,Version=v4.5.2"", FrameworkDisplayName = "".NET Framework 4.5.2"")]

namespace TestNamespace
```
but the [assembly] attribute has no effect at GetDotNetFrameworkVersion function the analyzer uses to detect .NET version it is supposed to analyze. However it is unit tests' issue (because of the way they reference mscorlib.dll), version detection in IDE works fine.
Unit tests pass because unit tests that verify there is no warning under 4.5.2 lack their counter parts to verify there is a warning under 4.5.1.

Regarding insecure overloads. I might agree that it is better to use an overload that requires to pass XmlReader explicitly in .NET >= 4.5.2 case, but it generates a lot of noise.

### PR DESCRIPTION
**Pull request by chloduan**
Fixes #1150

This change is made to account for the false positives created by analyzer CA3075 for XmlDocument after .NET version 4.5.2.

Before .NET 4.5.2, XmlDocument creates a new XmlUrlResolver object as XmlResolver if no object is provided as the default behaviour. After .NET 4.5.2, XmlDocument defaults XmlResolver as null.

This check for warning is done in DoNotUseInsecureDtdProcessing.cs, indicated by variables XmlDocumentEnvironment.IsXmlResolverSet and XmlDocumentEnvironment.IsSecureResolver.

Unit tests for XmlDocument is split into pre/post version 4.5.2 to test for CA3075 warning variations. Helper methods for .NET version variation (VerifyCSharpAnalyzerAsync, VerifyVisualBasicAnalyzerAsync) are added.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/roslyn-analyzers?pullRequest=3719) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn-analyzers?pullRequest=3719) before we can accept your contribution.<br/><br/>:x: chloduan [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn-analyzers?pullRequest=3719)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn-analyzers?pullRequest=3719) it.</sub>

File: src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs [hunk 1]
```diff
@@ -186,6 +199,11 @@ public void AnalyzeOperationBlock(OperationBlockAnalysisContext context)
                 foreach (KeyValuePair<ISymbol, XmlDocumentEnvironment> p in _xmlDocumentEnvironments)
                 {
                     XmlDocumentEnvironment env = p.Value;
+
+                    // secure 4.5.2 version not being checked for secure
+                    // if Version > 4.5.2 => XmlDocument = secure!!
+                    // Before 4.5.2, insecure if XmlResolver set as null for XmlUrlResolver
+                    // After 4.5.2, insecure only if XmlResolver set as XmlUrlResolver
                     if (!(env.IsXmlResolverSet | env.IsSecureResolver))
```
Comment (dotpaul) [inline src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs:207]: I'd remove the comments here, since I don't think they're matching the code here.

File: src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs [hunk 2]
```diff
@@ -326,18 +344,19 @@ private void AnalyzeObjectCreationInternal(OperationAnalysisContext context, ISy
...
+                    xmlDocumentEnvironment = new XmlDocumentEnvironment(_isFrameworkSecure);
                 }
 
                 xmlDocumentEnvironment.XmlDocumentDefinition = objCreation.Syntax;
                 SyntaxNode node = objCreation.Syntax;
-                bool isXmlDocumentSecureResolver = false;
+
+                // initial XmlResolver secure value dependent on whether framework version secure
+                // < .NET 4.5.2 insecure - XmlDocument would set XmlResolver as XmlUrlResolver
+                // > .NET 4.5.2 secure - XmlDocument would set XmlResolver as null
```
Comment (dotpaul) [inline src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs:358]:
```suggestion
                // >= .NET 4.5.2 secure - XmlDocument would set XmlResolver as null
```

File: src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs [hunk 3]
```diff
@@ -119,6 +119,19 @@ private class XmlDocumentEnvironment
...
+                {
+                    IsXmlResolverSet = false;
+                    if (isTargetFrameworkSecure)
+                    {
+                        IsSecureResolver = true;
+                    }
+                    else
+                    {
+                        IsSecureResolver = false;
+                    }
```
Comment (Evangelink) [inline src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs:133]:
```suggestion
                    IsSecureResolver = isTargetFrameworkSecure;
```

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs [hunk 4]
```diff
@@ -455,9 +456,11 @@ End Class
         }
 
         [Fact]
-        public async Task RealCodeSnippitFromCustomerShouldGenerateDiagnostic()
+        public async Task RealCodeSnippitFromCustomerPre452ShouldGenerateDiagnostic()
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs:459]:
```suggestion
        public async Task RealCodeSnippetFromCustomerPre452ShouldGenerateDiagnostic()
```

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs [hunk 5]
```diff
@@ -547,5 +552,101 @@ End Class
                 GetCA3075XmlDocumentWithNoSecureResolverBasicResultAt(11, 31)
             );
         }
+
+        [Fact]
+        public async Task RealCodeSnippitFromCustomerPost452ShouldNotGenerateDiagnostic()
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs:557]:
```suggestion
        public async Task RealCodeSnippetFromCustomerPost452ShouldNotGenerateDiagnostic()
```

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs [hunk 6]
```diff
@@ -506,7 +509,9 @@ public static string TestMethod(string inputRule)
                 GetCA3075XmlDocumentWithNoSecureResolverCSharpResultAt(15, 38)
             );
 
-            await VerifyVB.VerifyAnalyzerAsync(@"
+            await VerifyVisualBasicAnalyzerAsync(
+    ReferenceAssemblies.NetFramework.Net451.Default,
```
Comment (dotpaul) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs:513]: Nitpick: Use same indentation as VerifyCSharpAnalyzerAsync.

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentConstructedWithNoSecureResolverTests.cs [hunk 7]
```diff
@@ -580,9 +703,58 @@ End Class
         }
 
         [Fact]
-        public async Task XmlDocumentAsFieldSetResolverToInsecureResolverInOnlyMethodShouldGenerateDiagnostics()
+        public async Task XmlDocumentSetResolversInDifferentBlockPost452ShouldGenerateDiagnostic()
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentConstructedWithNoSecureResolverTests.cs:706]: Test is named as "should generate diagnostic" but there is no expected diagnostic listed.

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+using VerifyCS = Test.Utilities.CSharpSecurityCodeFixVerifier<
+    Microsoft.NetFramework.Analyzers.DoNotUseInsecureDtdProcessingAnalyzer,
+    Microsoft.CodeAnalysis.Testing.EmptyCodeFixProvider>;
+
+namespace Microsoft.NetFramework.Analyzers.UnitTests
+{
+    public partial class DoNotUseInsecureDtdProcessingAnalyzerTests
+    {
+        private static DiagnosticResult GetCSharpResultAt(int line, int column)
+        => VerifyCS.Diagnostic(DoNotUseInsecureDtdProcessingAnalyzer.RuleXmlDocumentWithNoSecureResolver).WithLocation(line, column);
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs:15]:
```suggestion
        	=> VerifyCS.Diagnostic(DoNotUseInsecureDtdProcessingAnalyzer.RuleXmlDocumentWithNoSecureResolver).WithLocation(line, column);
```

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+
+        [Fact]
+        public async Task XmlDocument_TargetFx451_ShouldGenerateDiagnostic()
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs:18]: [cosmetic] Could you use the same test method naming convention across your tests? I prefer this one but I think both are fine. I'll let @mavasani gives his preference.

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs [hunk 10]
```diff
@@ -0,0 +1,73 @@
...
+        {
+            await VerifyCSharpAnalyzerAsync(
+                ReferenceAssemblies.NetFramework.Net451.Default,
+                @"
+using System;
+using System.Reflection;               
+using System.Xml;
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs:25]:
```suggestion
using System.Reflection;
using System.Xml;
```

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+
+        [Fact]
+        public async Task XmlDocument_TargetFx452_ShouldNotGenerateDiagnostic()
+        {
+            await VerifyCSharpAnalyzerAsync(
+                ReferenceAssemblies.NetFramework.Net452.Default,
+                @"
+using System;
+using System.Reflection;               
+using System.Xml;
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs:54]:
```suggestion
using System.Reflection;
using System.Xml;
```

File: src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs [hunk 12]
```diff
@@ -390,11 +412,13 @@ private void AnalyzeObjectCreationForXmlDocument(OperationAnalysisContext contex
 
                 xmlDocumentEnvironment.IsSecureResolver = isXmlDocumentSecureResolver;
 
+                // if XmlDocument object not temporary (variable not null), add environment to dictionary
```
Comment (mavasani) [inline src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs:415]:
```suggestion
                // if XmlDocument object not temporary, add environment to dictionary
```

**Comment by dotpaul** [comment]
> Could you create a ticket linked to this PR with the explanation of the problem? I have seen that you have provided some description with the PR.

I updated the PR's description to note it fixes #1150

File: src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs (hunk 1 above)
Comment (chloduan) [reply src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessing.cs:200]: Removed

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs (hunk 6 above)
Comment (chloduan) [reply src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingCreateUsingInsecureInputXmlReaderSettingsTests.cs:513]: Done

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentConstructedWithNoSecureResolverTests.cs (hunk 7 above)
Comment (chloduan) [reply src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentConstructedWithNoSecureResolverTests.cs:706]: Thanks for pointing out. Fixed.

File: src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs (hunk 9 above)
Comment (chloduan) [reply src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingXmlDocumentSecureDefaultXmlResolverAnalyzerTests.cs:18]: Made the names consistent.
