### PR TITLE
Handle property initializers in RS1005

### LINKED ISSUE #1689: Analyzer for 'Reported diagnostic with ID 'XXX' is not supported by the analyzer.' does not work with property initializers
#### Analyzer package
Microsoft.CodeAnalysis.Analyzers

#### Repro steps

Warn if the analyzer reports diagnostic for a descriptor that is not in `SupportedDiagnostics`
```cs
namespace RoslynSandbox
{
    using System.Collections.Immutable;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.Diagnostics;

    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    internal class FooAnalyzer : DiagnosticAnalyzer
    {
        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get; } = ImmutableArray.Create(
            FooInfo.Descriptor);

        public override void Initialize(AnalysisContext context)
        {
            context.RegisterSyntaxNodeAction(
                c => c.ReportDiagnostic(
                    Diagnostic.Create(
                        BarInfo.Descriptor,
                        c.Node.GetLocation())),
                SyntaxKind.AbstractKeyword);
        }
    }

    internal static class FooInfo
    {
        public const string DiagnosticId = "FOO";

        internal static readonly DiagnosticDescriptor Descriptor = new DiagnosticDescriptor(
            id: DiagnosticId,
            title: "",
            messageFormat: "",
            category: "",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "");
    }

    internal static class BarInfo
    {
        public const string DiagnosticId = "BAR";

        internal static readonly DiagnosticDescriptor Descriptor = new DiagnosticDescriptor(
            id: DiagnosticId,
            title: "",
            messageFormat: "",
            category: "",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "");
    }
}
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #1689

### CODE REVIEW

File: src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -33,6 +33,23 @@ protected override IEnumerable<SyntaxNode> GetArgumentExpressions(InvocationExpr
...
             }
+
+            protected override SyntaxNode GetPropertyGetterBlockSyntax(SyntaxNode declaringSyntaxRefNode)
+            {
+                if (declaringSyntaxRefNode is AccessorDeclarationSyntax accessor &&
+                    accessor.Body == null &&
+                    accessor.ExpressionBody == null)
+                {
+                    // Walk up to the property initializer.
+                    var propertyDecl = accessor.FirstAncestorOrSelf<PropertyDeclarationSyntax>();
```
Comment (JohanLarsson) [inline src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs]: Why not `accessor.Parent`?

File: src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs [hunk 2]
```diff
@@ -33,6 +33,23 @@ protected override IEnumerable<SyntaxNode> GetArgumentExpressions(InvocationExpr
 
                 return null;
             }
+
+            protected override SyntaxNode GetPropertyGetterBlockSyntax(SyntaxNode declaringSyntaxRefNode)
```
Comment (JohanLarsson) [inline src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs]: The name is a bit weird now.

File: src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs (hunk 1 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs]: `accessor.Parent`, that seems to accessor list syntax. I felt this was much more safer.

File: src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs (hunk 2 above)
Comment (mavasani) [reply src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs]: I'd really like to switch this to an IOperation analyzer soonish to avoid more syntax related gymnastics.

File: src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs (hunk 1 above)
Comment (JohanLarsson) [reply src/Microsoft.CodeAnalysis.Analyzers/CSharp/MetaAnalyzers/CSharpReportDiagnosticAnalyzer.cs]: Derp, yes true.
