### PR TITLE
Consider pure functions as part of CA1806.

### LINKED ISSUE #1164: CA1806 (Do not ignore method results) could benefit from [PureAttribute]
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers

#### Analyzer

CA1806 (Do not ignore method results)

#### Repro steps

1. Declare a method which is marked with `[Pure]` and returns a value
1. Call the method, ignoring the return value

```csharp
[Pure]
public int Method()
  => 3;

public void Program()
{
  Method(); // CA1806??
}
```

#### Expected behavior

CA1806 could be reported.

#### Actual behavior

CA1806 is not reported.

:memo: The potential increase in false positives for this rule is unknown. However, the ability to use `var _ =` to explicitly ignore such return values could compensate for the higher rate of reports.

### PR DESCRIPTION
**Pull request by 333fred**
Functions that are marked `Pure` have no side effects, and should be considered when we check to see if function results are discarded without use. Fixes #1164. Tagging @dotnet/analyzer-ioperation @sharwell for review.

### CODE REVIEW

**Comment by sharwell** [comment]
@333fred I'd be interested in gathering some churn metrics in some common cases for this change. For example, how many more diagnostics were reported due to this change in:

* Roslyn.sln
* CodeContracts.sln (a pathological case we often use for analyzer testing)
* Json.NET

**Comment by 333fred** [comment]
@sharwell investigated:

* Roslyn - very little usage of `Pure`, no additional warnings
* CodeContracts - Lots of `Pure`, no new warnings. They do have a few for not ignoring HResults/dropping objects. I did have issues building the solution, so I can't 100% guarantee that it actually analyzed everything.
* Json.NET - Does not use `Pure`.

**Comment by 333fred** [comment]
Ping @sharwell @dotnet/roslyn-analysis for review here.

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/DoNotIgnoreMethodResults.cs [hunk 1]
```diff
@@ -6,6 +6,8 @@
 using Microsoft.CodeAnalysis;
 using Microsoft.CodeAnalysis.Diagnostics;
 using Microsoft.CodeAnalysis.Semantics;
+using System.Diagnostics.Contracts;
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/DoNotIgnoreMethodResults.cs]: Sort usings.
