### PR TITLE
Handle few more special cases of serializable fields in CA2235 (Mark …

### LINKED ISSUE #1274: CA2235: Throws InvalidOperationException on fields of generic type
#### Analyzer package

Microsoft.NetFramework.Analyzers

#### Analyzer

MarkAllNonSerializableFields

#### Repro steps

1. Create a generic class with [Serializable] attribute, e.g. `public class MyContainer<T>`.
1. Add a field of generic type, e.g. `private T _myField;`.
1. Diagnostic message appears. Hovering mouse over "Add Serializable attribute" throws InvalidOperationException.

#### Expected behavior

"Add Serializable attribute" quick fix should not be shown for fields of generic type.

#### Actual behavior

Add Serializable attribute" quick fix throws InvalidOperationException with the following stack trace:

          System.InvalidOperationException : Cannot generated a documentation comment id for symbol.
         at Microsoft.CodeAnalysis.DocumentationCommentId.DeclarationGenerator.DefaultVisit(ISymbol symbol)
         at Microsoft.CodeAnalysis.SymbolVisitor.VisitTypeParameter(ITypeParameterSymbol symbol)
         at Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol.Accept(SymbolVisitor visitor)
         at Microsoft.CodeAnalysis.SymbolVisitor.Visit(ISymbol symbol)
         at Microsoft.CodeAnalysis.DocumentationCommentId.CreateDeclarationId(ISymbol symbol)
         at async Microsoft.CodeAnalysis.Editing.SymbolEditor.GetCurrentSymbolAsync(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.Editing.SymbolEditor.EditOneDeclarationAsync(<Unknown Parameters>)
         at async Microsoft.NetFramework.Analyzers.MarkAllNonSerializableFieldsFixer.AddSerializableAttributeToType(<Unknown Parameters>)
         at async Microsoft.NetFramework.Analyzers.MarkAllNonSerializableFieldsFixer.<>c__DisplayClass3_0.<RegisterCodeFixesAsync>b__2(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
         at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

### PR DESCRIPTION
**Pull request by mavasani**
…all non-serializable fields)

Fixes #1274

### CODE REVIEW

File: src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs [hunk 1]
```diff
@@ -242,13 +242,34 @@ public void AnalyzeSymbol(SymbolAnalysisContext context)
                 }
             }
 
-            private bool IsSerializable(ITypeSymbol namedTypeSymbol)
+            private bool IsSerializable(ITypeSymbol type)
```
Comment (mavasani) [inline src/Microsoft.NetFramework.Analyzers/Core/SerializationRulesDiagnosticAnalyzer.cs]: Now matches legacy FxCop [implementation](http://index/?query=MarkAllNonSerializableFields&rightProject=FxCopSdk&file=RuleUtilities.cs&line=434)
