### PR TITLE
Re-implement CodeAnalysisTreatWarningsAsErrors with globalconfig files

### LINKED ISSUE #6281: Some rules can no longer be silenced with an .editorconfig file in .NET 7
### Analyzer

**Diagnostic ID**: [CA1848](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1848): `Use the LoggerMessage delegates` (among others)

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 7 SDK](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 7.0.100](https://dotnet.microsoft.com/download/dotnet/7.0)

### Describe the bug

Some rules' severity can no longer be set to none with a global .editorconfig file in .NET 7, but it could in .NET 6.

### Steps To Reproduce

Build [this solution](https://github.com/billybraga/EditorConfigNotUsed/tree/master/Net7EditorConfigNotUsed) with .NET 7.

### Expected behavior

The Net7Project**With**EditorConfigIgnore project builds successfully, like [its equivalent in .NET 6](https://github.com/billybraga/EditorConfigNotUsed/tree/master/Net6EditorConfigNotUsed).

### Actual behavior

The project Net7Project**With**EditorConfigIgnore fails to build because of CA1848 (CA1303 was successfully silenced, as we can see by the fact that Net7Project**Without**EditorConfigIgnore fails with CA1303).

## Additional context

See the [.editorconfig](https://github.com/billybraga/EditorConfigNotUsed/blob/master/Net7EditorConfigNotUsed/.editorconfig). It sets to none the severity of CA1303 and CA1848 in the Net7Project**With**EditorConfigIgnore folder.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6281

Prior implementation for `CodeAnalysisTreatWarningsAsErrors` passed `/warnaserror+:CAxxxx` to the compiler command line for each CA rule ID. This led to couple of issues:
1. All disabled by default CA warnings seem to get enabled as errors
2. Editorconfig/globalconfig based configuration of the enabled CA rules stops working.

The new implementation updates our globalconfig tooling to generate parallel globalconfigs with `_warnaserror` suffix, such that rules which would have had effective warning severity are set to error severity in the new globalconfig files. The targets/props that picks the appropriate globalconfig based on the `AnalysisLevel` property now chooses the file with `_warnaserror` suffix if user has enabled code analysis warnings to be treated as errors.

Another couple of notes:
1. Given that the buggy implementation of `CodeAnalysisTreatWarningsAsErrors` has already shipped in .NET7 and prior SDKs, we use a separate property `EffectiveCodeAnalysisTreatWarningsAsErrors`, so users using the newer NuGet package, but older .NET SDK can still get this functionality. Users that move to the newer .NET8 preview SDK with this fix can use `CodeAnalysisTreatWarningsAsErrors` itself.
2. I have adjusted the tooling to generate the config files into buildtransitive folder instead of build folder. This is needed as a follow-up to #6325 for globalconfig files to be correctly mapped.
3. I have also renamed all the tooling generated globalconfig files to have .globalconfig extension instead of .editorconfig extension, as that was misleading.

I have verified that `CodeAnalysisTreatWarningsAsErrors` works fine with the locally built package when `EffectiveCodeAnalysisTreatWarningsAsErrors` is set to true. If I manually edit the targets/props shipped inside .NET7 SDK to delete all the prior shipped `CodeAnalysisTreatWarningsAsErrors` logic, then setting `CodeAnalysisTreatWarningsAsErrors` also works fine.

### CODE REVIEW

**Comment by mavasani** [comment]
@jmarolf @Youssef1313 for review

File: src/Tools/GenerateAnalyzerNuspec/Program.cs [hunk 1]
```diff
@@ -235,15 +235,15 @@
...
 if (globalAnalyzerConfigsDir.Length > 0 && Directory.Exists(globalAnalyzerConfigsDir))
 {
-    foreach (string editorconfig in Directory.EnumerateFiles(globalAnalyzerConfigsDir))
+    foreach (string globalconfig in Directory.EnumerateFiles(globalAnalyzerConfigsDir))
     {
-        if (Path.GetExtension(editorconfig) == ".editorconfig")
+        if (Path.GetExtension(globalconfig) == ".globalconfig")
         {
-            result.AppendLine(FileElement(Path.Combine(globalAnalyzerConfigsDir, editorconfig), $"build\\config"));
+            result.AppendLine(FileElement(Path.Combine(globalAnalyzerConfigsDir, globalconfig), $"buildtransitive\\config"));
```
Comment (mavasani) [inline src/Tools/GenerateAnalyzerNuspec/Program.cs:242]: @Youssef1313 This is the fix to generate config files in `buildtransitive` next to props/targets

File: src/Tools/GenerateDocumentationAndConfigFiles/Program.cs [hunk 2]
```diff
@@ -310,20 +310,6 @@ string getDisableNetAnalyzersImport()
                 }
             }
 
-            string getCodeAnalysisTreatWarningsAsErrors()
```
Comment (mavasani) [inline src/Tools/GenerateDocumentationAndConfigFiles/Program.cs:313]: Older implementation of `CodeAnalysisTreatWarningsAsErrors`

**Review by Youssef1313 — APPROVED** [review]

**Comment by mavasani** [comment]
Thank you for the review @Youssef1313
