### PR TITLE
Fix: CA1822 Mark Members As Static should not trigger for methods containing only NotImplementedException #1544

### LINKED ISSUE #1544: CA1822 Mark Members As Static should not trigger for methods containing only NotImplementedException
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version 2.6.1-beta1-62512-01

#### Analyzer

MarkMembersAsStatic (CA1822)

#### Repro

Method that just throws NotImplementedException. For example:

```csharp
using System;

namespace CodeAnalysisTest
{
    public class Program
    {
        public void Foo()
        {
            throw new NotImplementedException();
        }

        public static void Main()
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

#### Expected behavior

No error. 

I think it is reasonable to assume that a method that currently always throws NotImplementedException is just a stub, and once implemented will access instance data. 

Checks for CA1801 were disabled for unimplemented methods in #1353 which is a similar situation.

#### Actual behavior

Check fails.

````
Program.cs(7,21,7,24): warning CA1822: Member Foo does not access instance data and can be marked as static (Shared in VisualBasic)
````

### PR DESCRIPTION
**Pull request by ChiragRupani**
Fixes #1544

This updates CA1822 to be aware of method bodies that are only throw NotImplementedException() and makes sure that diagnostics aren't registered for them.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs [hunk 1]
```diff
@@ -246,5 +246,75 @@ void Add(INamedTypeSymbol symbol)
...
+            // Mark Members as static should not trigger for methods containing only NotImplementedException 
+            
+            // Note that VB method bodies with 1 action have 3 operations.
+            // The first is the actual operation, the second is a label statement, and the third is a return
+            // statement. The last two are implicit in these scenarios.
+                        
+            var operationBlocks = context.OperationBlocks;
+            if (operationBlocks.Any(operation => operation.IsOperationNoneRoot()))
+            {
+                operationBlocks = operationBlocks.Where(operation => !operation.IsOperationNoneRoot()).ToImmutableArray();
```
Comment (Therzok) [inline src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: This could be a `WhereAsArray` call.

https://github.com/dotnet/roslyn-analyzers/blob/57318576d6a39f4858e1110b611ce201505183ef/src/Utilities/Extensions/IEnumerableExtensions.cs#L74

Comment (Therzok) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: And by that I mean, it handles the `Any` case without double iteration and allocations.

Comment (chiragrupani) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: Thanks for review, updated the same, also in unused parameters file where same construct is used.

File: src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs [hunk 2]
```diff
@@ -246,5 +246,71 @@ void Add(INamedTypeSymbol symbol)
 
             return builder?.ToImmutable() ?? ImmutableArray<INamedTypeSymbol>.Empty;
         }
+
+        private static bool IsMethodNotImplemented(OperationBlockAnalysisContext context)
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: Instead of cloning this code in 2 analyzers, can you make it an extension method on OperationBlockAnalysisContext (you can create a new extension file [here](https://github.com/dotnet/roslyn-analyzers/tree/master/src/Utilities/Extensions))?

Additionally, the current code for detection looks fragile as the IOperation tree shape is liable to change in future. Can you file a separate issue to think about a different strategy to implement it?

Comment (chiragrupani) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: Moved common code to extension and updated code accordingly. 
Regarding `IOperation` tree shape, please file it - as I don't know much about its details.

**Comment by mavasani** [comment]
@dotnet-bot retest this please
