### PR TITLE
Don't emit CA1508 in Debug.Assert

### LINKED ISSUE #6983: CA1508 fires for Debug.Assert
### Analyzer

**Diagnostic ID**: [CA1508](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Steps To Reproduce

1. Create a new C# Class Library, targeting `net8.0`
2. Edit the csproj and add `<AnalysisLevel>latest-all</AnalysisLevel>`
3. Define the following class:
```csharp
using System.Diagnostics;

namespace MyNamespace;

public static class MyClass1
{
    internal const int MyConstant = 16;

    public static void MyMethod()
    {
        Debug.Assert(MyConstant == 16);
    }
}
```

### Expected behavior

The analyzer should not trigger for a `Debug.Assert`. This is often used to handle code that may make assumptions based on the value of a constant, such as not handling larger code paths or having pre-defined static data and where it may need to be updated if the value of the constant ever changes.

### Actual behavior

The analyzer is triggered.

### PR DESCRIPTION
**Pull request by CollinAlpert**
Fixes #6983

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs [hunk 1]
```diff
@@ -73,13 +78,15 @@ public override void Initialize(AnalysisContext context)
...
+                        bool ShouldAnalyze(IOperation op) =>
+                                ((op as IBinaryOperation)?.IsComparisonOperator() == true ||
                                 op is IInvocationOperation { TargetMethod.ReturnType.SpecialType: SpecialType.System_Boolean } ||
                                 op.Kind == OperationKind.Coalesce ||
                                 op.Kind == OperationKind.ConditionalAccess ||
                                 op.Kind == OperationKind.IsNull ||
-                                op.Kind == OperationKind.IsPattern;
+                                op.Kind == OperationKind.IsPattern)
+                                && (op.Parent is not IArgumentOperation { Parent: IInvocationOperation invocation } ||
+                                    !debugAssertMethods.Contains(invocation.TargetMethod, SymbolEqualityComparer.Default));
```
Comment (mavasani) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs:89]: Will this work if Debug.Assert expressions is more complex, say `Debug.Assert(MyConstant == 16 && MyConstant2 == 17);` where `MyConstant2` is another constant with value `17`?

I think a better approach would be to revert the changes to `ShouldAnalyze` and instead add a `ShouldReport(IOperation op)` helper that gets called just prior to `context.ReportDiagnostic` calls in this analyzer, and that one can do a walk up the operation tree and check if any of the ancestor `IInvocationOperation` is a call to a debug assert method.

Comment (CollinAlpert) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs:89]: I thought about that approach as well, but was hesitant about implementing a plain walk-up, since we could have something like this, which IMO should be flagged: `Debug.Assert(MethodCall(MyConstant == 16));`

Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode.cs:89]: Sounds reasonable. We can revisit this in future if needed. Thanks for the fix.

**Review by mavasani — APPROVED** [review]
