### PR TITLE
Account for parameter RefKind while identifying alternate overloads.

### LINKED ISSUE #1734: CA1304 should ignore a CultureInfo parameter which is 'out'
#### Analyzer package

[System.Runtime.Analyzers](https://www.nuget.org/packages/System.Runtime.Analyzers)

#### Package Version

v1.1.0

#### Diagnostic ID

[CA1304](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1304-specify-cultureinfo)

#### Repro steps

1. Define methods with the signatures `void Foo(string a)` and `void Foo(string a, out CultureInfo b)`
2. Write a call to `Foo("")`
2. CA1304 fires, saying that the overload which takes a CultureInfo should be used

#### Expected behavior

CA1304 should ignore `out` parameters. The intent of CA1304 is to identify methods which have an overload allowing the user to specify an explicit CultureInfo, and another overload which infers the CultureInfo. However a CultureInfo which is an `out` parameter cannot be used to specify the CultureInfo to be used -- it obviously has another purpose -- and so CA1304 should not get involved.

#### Actual behavior

CA1304 does not ignore `out` parameters.

### PR DESCRIPTION
**Pull request by mavasani**
Affected rules: CA1304, CA1305 and CA1307
Fixes #1734

### CODE REVIEW

File: src/Utilities/Extensions/IEnumerableOfIMethodSymbolExtensions.cs [hunk 1]
```diff
@@ -48,20 +48,31 @@ internal static class IEnumerableOfIMethodSymbolExtensions
 
                 if (!trailingOnly && candidateMethod.Parameters.First().Type.Equals(expectedParameterType))
                 {
+                    // Bail out if RefKind of first parameter is not None.
```
Comment (333fred) [inline src/Utilities/Extensions/IEnumerableOfIMethodSymbolExtensions.cs]: Why? You could have a `ref` first parameter and a non-ref culture as the last parameter.

Comment (mavasani) [reply src/Utilities/Extensions/IEnumerableOfIMethodSymbolExtensions.cs]: Good catch, let me add a unit test and fix it.
