### PR TITLE
Fix analyzers/tests for non-local diagnostics

### LINKED ISSUE #6598: Analyzers should not try to fix non-local diagnostics
>              Can we file an issue to track fixing all analyzers reporting non-local diagnostics?
>
> _Originally posted by @mavasani in https://github.com/dotnet/roslyn-analyzers/pull/6560#discussion_r1172789018_

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6598

_Recommended to review ignoring whitespace differences_

- Move to latest Microsoft.CodeAnalysis package for unit tests
- Fix analyzers reporting non-local diagnostics
- Add comments to tests where `CodeFixTestBehaviors.SkipLocalDiagnosticCheck` cannot be removed
- Also fixed a code fixer relying on implicit tracking node functionality, which fails after moving to latest MS.CA bits.

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs [hunk 1]
```diff
@@ -76,13 +76,22 @@ public override void Initialize(AnalysisContext context)
             context.EnableConcurrentExecution();
             context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
 
-            context.RegisterSymbolAction(AnalyzeSymbol, SymbolKind.Method);
+            context.RegisterSymbolAction(context =>
```
Comment (sharwell) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs:79]: ❔ Would it be better to make this a symbol start/stop analyzer?

File: src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs [hunk 2]
```diff
@@ -17,6 +17,14 @@ namespace Microsoft.NetCore.Analyzers.Runtime.UnitTests
 {
     public class SealInternalTypesTests
     {
+        // NOTE: 'SealInternalTypes' analyzer reports a compilation end diagnostic.
+        //       Code fixes are not yet supported for compilation end diagnostics,
```
Comment (sharwell) [inline src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs:21]: > Code fixes are not yet supported for compilation end diagnostics

❔ Does this apply to dotnet-format?

File: src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb [hunk 3]
```diff
@@ -38,30 +38,38 @@ Namespace Microsoft.CodeQuality.VisualBasic.Analyzers.ApiDesignGuidelines
...
                     End If
 
                     symbolContext.ReportDiagnostic(type.CreateDiagnostic(Rule))
                 End Sub,
-                SymbolKind.Method)
+                SymbolKind.NamedType)
         End Sub
+
+        Private Shared Function HasEqualityOperator(type As INamedTypeSymbol) As Boolean
+            For Each method In type.GetMembers().OfType(Of IMethodSymbol)
```
Comment (sharwell) [inline src/NetAnalyzers/VisualBasic/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/BasicOverrideEqualsOnOverloadingOperatorEquals.vb:64]: 💡 Would be better to iterate over `GetMembers()` and have the `OfType<IMethodSymbol>()` check in the body.

**Review by sharwell — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
> Fix analyzers reporting non-local diagnostics

We did doc this somewhere, right?  Given the number of changes in roslyn itself, and here, this will def impact the ecossytem.  The wins are so great, it's def worth it.  I just want to make sure we did doc this so we can point people to the issue when they run into it on their end.  thanks!

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by mavasani** [comment]
Merging the PR as-is to unblock Cyrus. I’ll address @sharwell’s feedback with a follow up PR later today.

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs (hunk 1 above)
Comment (mavasani) [reply src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/OperatorOverloadsHaveNamedAlternates.cs:79]: We don't support registering nested symbol action callbacks, so this needs to be implemented as done here.

File: src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs (hunk 2 above)
Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SealInternalTypesTests.cs:21]: > Does this apply to dotnet-format?

I am not sure.
