### PR TITLE
Fix CA1508 false positive for pattern expressions

### LINKED ISSUE #6048: CA1508 - False positive for "is"-operator in catch-block with rethrow
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CA1508---False-positive-for-is-operato/10083678)._

---
[severity:It bothers me. A fix would be nice]
The following applies to projects with `AllEnabledByDefault`:

When a catch-block that ends with a `throw;`-statement contains an if-statement whose condition is of the form `if (x is Y y)`, where x is any variable of type X and Y is a sub-type of X, the if-condition is flagged with CA1508. However, since Y is a sub-type of X, this condition can be false, making this a false positive.

Minimal example to reproduce:
```
try
{
   throw new Random().NextDouble() > 0.5 ? new Exception() : new ArgumentException();
}
catch (Exception e)
{
   if (e is ArgumentException ae) // can be both true or false depending on the Exception thrown from the try-block, yet is flagged with CA1508 
      Console.Out.WriteLine("ArgumentException");

   throw;
}
```

Removing `throw;` or adding an else-part to the if-statement removes the false positive.

TargetFramework: net6.0, Visual Studio Version: 17.2.5

---
#### Feedback Bot on 6/29/2022, 06:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6048

`goto case DiscardPattern` had the required logic for setting the predicated value for the pattern value in true branch of the `is expression`, but it was also setting `predicateValueKind`, which is in turn used to identify redundant duplicate conditional checks. Latter is fixed by this change.

### CODE REVIEW

File: src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs [hunk 1]
```diff
@@ -1564,8 +1564,14 @@ private void PerformPredicateAnalysisCore(IOperation operation, TAnalysisData ta
...
                             }
 
-                            // Also set the predicated value for pattern value for true branch, i.e. for 'c' in "c is D d".
-                            goto case OperationKind.DiscardPattern;
+                            // Also set the predicated value for pattern value for true branch, i.e. for 'c' in "c is D d",
+                            // while explicitly ignore the returned 'predicateValueKind'.
+                            if (FlowBranchConditionKind == ControlFlowConditionKind.WhenTrue)
+                            {
+                                _ = SetValueForIsNullComparisonOperator(isPatternOperation.Value, equals: false, targetAnalysisData: targetAnalysisData);
+                            }
```
Comment (mavasani) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs:1572]: Added code is just the copy of code in the `case OperationKind.DiscardPattern` section right below this one, except that we ignore the returned value by `SetValueForIsNullComparisonOperator`

**Comment by mavasani** [comment]
@Youssef1313

**Review by Youssef1313 — APPROVED** [review]

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs [hunk 2]
```diff
@@ -7474,5 +7474,51 @@ public static List<T> Test1<T>(IEnumerable<T> source)
...
+
+    public static void M2()
+    {
+        try
+        {
+            throw new Exception();
+        }
+        catch (Exception e)
+        {
+            if (e is ArgumentException ae)
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs:7513]: Maybe add a test with `catch (ArgumentException)` and asserting that the condition is flagged as "always true"?

Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs:7513]: Sure, let me add it in the next PR.

Comment (mavasani) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs:7513]: @Youssef1313 It seems this is a false negative right now. I'll file a tracking issue for it

```csharp
using System;

class Test
{
    public static void M()
    {
        try
        {
            throw new Random().NextDouble() > 0.5 ? new Exception() : new ArgumentException();
        }
        catch (ArgumentException e)
        {
            if (e is ArgumentException ae)
                Console.Out.WriteLine(""ArgumentException"");

            throw;
        }
    }
}
```
