### PR TITLE
Handle attribute operation blocks in operation block analyzers

### LINKED ISSUE #1435: CA1801: Review unused parameters triggering on extern methods
#### Analyzer package

Microsoft.CodeAnalysis.FxCopAnalyzers, version [2.6.0-beta1]

#### Analyzer

CA1801: Review unused parameters

#### Repro steps

1. Create a "static extern" method for p/invoke

#### Expected behavior

According to https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters extern methods should be ignored.

#### Actual behavior

CA1801 warnings aplenty. This is a regression in 2.6.0-beta1 (didn't happen in 2.3.0-beta1)

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #1435

### CODE REVIEW

File: src/Utilities/Extensions/IOperationExtensions.cs [hunk 1]
```diff
@@ -153,5 +153,12 @@ public static ImmutableArray<IOperation> GetOperations(this ImmutableArray<IOper
                 return blockOperations;
             }
         }
+
+        public static bool IsAttribute(this IOperation operation)
+        {
```
Comment (heejaechang) [inline src/Utilities/Extensions/IOperationExtensions.cs]: isn't this a bit too naïve way to check whether it is Attribute?

Comment (mavasani) [reply src/Utilities/Extensions/IOperationExtensions.cs]: Yes, but do we have other option without making it syntax specific check? Any other suggestions are welcome :)

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs [hunk 2]
```diff
@@ -685,7 +686,8 @@ private bool ValidateOperation(IOperation operation)
                     case OperationKind.Try:
                         return ValidateTryOperation((ITryOperation)operation);
                     default:
-                        return false;
+                        // Ignore attribute operation blocks.
+                        return operation.IsAttribute();
```
Comment (heejaechang) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs]: comment seems wrong? code looks like "don't ignore attribute operation blocks"

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs [hunk 3]
```diff
@@ -206,7 +206,16 @@ public void OperationBlockEndAction(OperationBlockAnalysisContext context)
                 // Note that VB method bodies with 1 action have 3 operations.
                 // The first is the actual operation, the second is a label statement, and the third is a return
                 // statement. The last two are implicit in these scenarios.
-                if (context.OperationBlocks.Length == 1)
+
+                // Filter out Attribute operation blocks.
+                var operationBlocks = context.OperationBlocks;
+                if (operationBlocks.Any(operation => operation.IsAttribute()))
+                {
+                    operationBlocks = operationBlocks.Where(operation => !operation.IsAttribute()).ToImmutableArray();
```
Comment (heejaechang) [inline src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: can block ever been OperationKind.None exception attributes? it looks like it can just filter out all OperationKind.None block?

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs (hunk 2 above)
Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/ImplementIDisposableCorrectly.cs]: The validator returns true for ignore/valid operations.

File: src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs (hunk 3 above)
Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: Attribute is the only case that I know of. If we find more cases, we will need to change this code to correctly decide whether to ignore or the entire block or operate on the Children.

Comment (heejaechang) [reply src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/ReviewUnusedParameters.cs]: @mavasani curious. so, now in operation block, it put attributes as part of operation block like method body? rather than we calling attribute as its own operationblock?
