### PR TITLE
Fix CA1710 (IdentifiersShouldHaveCorrectSuffix) for event symbol type

### LINKED ISSUE #1822: Users should not be instructed to rename BCL types
Analyzer package: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)
Package Version: 2.6.2-beta2
Diagnostic ID: CA1710

```c#
class Example
{
    public event Action Foo;
}
```

> CA1710 Rename Action to end in 'EventHandler'.

This cannot be done since System.Action is not under the control of the user. The renaming rule should   probably only apply to types defined within the solution.

### PR DESCRIPTION
**Pull request by mavasani**
Fire CA1710 (Event type name should end with "EventHandler") only if event type matches event handler signature
Fixes #1822

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs [hunk 1]
```diff
@@ -147,16 +147,22 @@ private static void AnalyzeCompilationStart(CompilationStartAnalysisContext cont
...
                     {
-                        saContext.ReportDiagnostic(eventSymbol.CreateDiagnostic(DefaultRule, eventSymbol.Type.Name, eventHandlerString));
-                    }
-                },
-                SymbolKind.Event);
+                        const string eventHandlerString = "EventHandler";
+                        var eventSymbol = (IEventSymbol)saContext.Symbol;
+                        if (!eventSymbol.Type.Name.EndsWith(eventHandlerString, StringComparison.Ordinal) &&
+                            eventSymbol.Type.TypeKind == TypeKind.Delegate &&
+                            ((INamedTypeSymbol)eventSymbol.Type).DelegateInvokeMethod?.HasEventHandlerSignature(eventArgsType) == true)
```
Comment (heejaechang) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs]: don't you still need to check whether type is source symbol? otherwise, user still can't rename the symbol? also, since it shows squiggle on reference, it might show multiple squiggles on same delegate?

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs]: It matches legacy FxCop behavior, but I agree this will reduce noise further. Will add a check to verify symbol is in source.

> it might show multiple squiggles for same delegate

I think that is fine, given delegate might be used at non-event locations as well, so fix has to be per event with that type.

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/IdentifiersShouldHaveCorrectSuffix.cs]: Fixed with https://github.com/dotnet/roslyn-analyzers/pull/1980/commits/0df5197b78879c0cb4d52b11bff694ff75b20489

**Comment by mavasani** [comment]
@heejaechang, any further feedback? Thanks!

**Comment by mavasani** [comment]
Confirmed with Heejae offline that he is fine with us matching legacy FxCop behavior here.
