### PR TITLE
Fixed false positives of CA2217, enum values don't have to be there.

### LINKED ISSUE #1566: CA2217 creates a false-positive when an enum value is missing
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

CA2217: Do not mark enums with FlagsAttribute [MSDN](https://msdn.microsoft.com/en-us/library/ms182335.aspx)

#### Repro steps

Create an enumeration with the FlagsAttribute where a value is missing.

```csharp
    [Flags]
    public enum TestEnum
    {
        Monday = 1,
        Wednesday = 4,
        Thursday = 8,
        Friday = 16,
    }
```

#### Expected behavior
Analyzer does not report a warning for the enum. According to MSDN it is sufficient when each value is a power of two, or a combination of defined values. 

#### Actual behavior
Analyzer reports a warning because the value 2 is missing.

### PR DESCRIPTION
**Pull request by dnperfors**
This PR fixes #1566.

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumWithFlagsAttributeTests.cs [hunk 1]
```diff
@@ -278,8 +278,23 @@ public enum MultipleMissingPowerOfTwoEnumClass
     Two = 2,
     Four = 4,
     ThirtyTwo = 32
-}}
+}}";
+
+            // Verify CA1027: Mark enums with FlagsAttribute
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EnumWithFlagsAttributeTests.cs]: FxCop neither reports CA1027 nor CA2217 for `MissingPowerOfTwoEnumClass` case. However, I feel your fix is appropriate as the documentation indicates CA1027 should be reported.
