### PR TITLE
Fix predicated analysis within points to analysis

### LINKED ISSUE #6695: CA1508 false positive with ??-pattern
### Analyzer

**Diagnostic ID**: [CA1508](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**SDK**: Built-in CA analyzers in .NET 7 SDK

**Version**: SDK 7.0.304

### Describe the bug

False positive when using ?? pattern:

```c#
private void FailingMethod(IEnumerable<int>? items = null)
{
	var itemsToTest = items as IReadOnlyList<int> ??
					  items?.ToList() ??
					  (IReadOnlyList<int>)Array.Empty<int>();
}
```

### Steps To Reproduce

Add this method somewhere to your code and try to compile using all warnings as error.

### Expected behavior

No warning.

### Actual behavior

The line `items?.ToList()` produces `Error CA1508: 'items' is always 'null'. Remove or refactor the condition(s) to avoid dead code.`

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6695

Fix predicated value flow in points to analysis to handle different types between the targetAnalysisEntity and different analysisEntity that shares the same location but has a different type. We use the conversion info between target type and analysis entity type to ensure the value can be flowed.

This change may likely fix other CA1508 false positives which involve conversions. I am going to try to add tests for such cases and see if they are fixed, and if so, add unit tests for them in this PR.

### CODE REVIEW

File: src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs [hunk 1]
```diff
@@ -522,7 +492,67 @@ protected override PredicateValueKind SetValueForIsNullComparisonOperator(IOpera
...
+                            {
+                                return;
+                            }
+                        }
+                    }
+
+                    if (!sourceAnalysisData.TryGetValue(analysisEntity, out var existingValue))
+                    {
+                        existingValue = defaultPointsToValueGenerator.GetOrCreateDefaultValue(analysisEntity);
+                    }
```
Comment (Youssef1313) [inline src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:541]: I don't understand this area well, but wanted to make sure whether we want to add the `analysisEntity` and `existingValue` pair to `sourceAnalysisData` or not.

Comment (mavasani) [reply src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PointsToAnalysis/PointsToAnalysis.PointsToDataFlowOperationVisitor.cs:541]: This method is only designed to modify `targetAnalysisData`...

**Review by Youssef1313 — APPROVED** [review]

**Comment by mavasani** [comment]
Thanks @Youssef1313!
