### PR TITLE
Handle type parameters specially in ISymbolExtensions.ParameterTypesA…

### LINKED ISSUE #1495: FXCopAnalyzers throws CA1054 warnings even with an overload with Uri
#### Analyzer package

Microsoft.CodeQuality.Analyzers, version [2.6.0-beta2](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0-beta2)

#### Analyzer

Example: URIParametersShouldNotBeStrings (CA1054)

#### Repro steps

1. Have a method like this, which generates a warning
```
 Task<TResponse> PostAsync<TRequest, TResponse>(string requestUri, TRequest content, CancellationToken cancellationToken)
            where TRequest : HttpContent
            where TResponse : class;
```
2. Add an overload to the method
```
Task<TResponse> PostAsync<TRequest, TResponse>(string requestUri, TRequest content, CancellationToken cancellationToken)
            where TRequest : HttpContent
            where TResponse : class;

Task<TResponse> PostAsync<TRequest, TResponse>(Uri requestUri, TRequest content, CancellationToken cancellationToken)
            where TRequest : HttpContent
            where TResponse : class;
```

#### Expected behavior
Warning resolved
#### Actual behavior
The warning is still there, this in VS 15.5.2

  
Thanks

### PR DESCRIPTION
**Pull request by mavasani**
…reSame

Fixes #1495

### CODE REVIEW

File: src/Utilities/Extensions/ISymbolExtensions.cs [hunk 1]
```diff
@@ -268,9 +268,19 @@ public static bool ParameterTypesAreSame(this IMethodSymbol method1, IMethodSymb
             {
                 cancellationToken.ThrowIfCancellationRequested();
 
+                var type1 = method2.Parameters[index].Type.OriginalDefinition;
+                var type2 = method1.Parameters[index].Type.OriginalDefinition;
+
+                if (type1.TypeKind == TypeKind.TypeParameter &&
```
Comment (mavasani) [inline src/Utilities/Extensions/ISymbolExtensions.cs]: This matches our comparison in Roslyn: http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/SymbolEquivalenceComparer.EquivalenceVisitor.cs,570. Ideally, we would be able to use Roslyn's [SymbolEquivalenceComparer](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Shared/Utilities/SymbolEquivalenceComparer.cs,f93cc1c775e51f8b), but that is internal.

File: src/Utilities/Extensions/ISymbolExtensions.cs [hunk 2]
```diff
@@ -268,9 +268,19 @@ public static bool ParameterTypesAreSame(this IMethodSymbol method1, IMethodSymb
             {
                 cancellationToken.ThrowIfCancellationRequested();
 
+                var type1 = method2.Parameters[index].Type.OriginalDefinition;
```
Comment (ivanbasov) [inline src/Utilities/Extensions/ISymbolExtensions.cs]: >method2 [](start = 28, length = 7)

method1
