### PR TITLE
Fix NRE in AssigningSymbolAndItsMemberInSameStatement analyzer

### LINKED ISSUE #2889: AD0001 - NullReferenceException when running CA2246
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

[v2.9.5](https://github.com/dotnet/roslyn-analyzers/releases/tag/v2.9.5)

#### Diagnostic ID

[CA2246](https://github.com/dotnet/roslyn-analyzers/pull/2717)

#### Repro steps

Analyze the following code:
```csharp
public static class Class1
{
    public static void Foo()
    {
        var u = new System.UriBuilder();
        u.Host = u.Path = string.Empty;
    }
}
```
#### Expected behavior
No warning or error.

#### Actual behavior

> Analyzer 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'
> 
> Analyzer 'Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement' threw the following exception:
> 'Exception occurred with following context:
> Compilation: RoslynAnalyzersFalsePositives
> IOperation: SimpleAssignment
> SyntaxTree: D:\src\Rob\RoslynAnalyzersFalsePositives\RoslynAnalyzersFalsePositives\CA2246.cs
> SyntaxNode: u.Host = u.Path = string.Empty [AssignmentExpressionSyntax]@[193..223) (7,12)-(7,42)
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement.<>c.<AnalyzeAssignment>b__8_0(ILocalReferenceOperation a, ILocalReferenceOperation b)
>    at Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement.AnalyzeAssignmentToMember[T](ISimpleAssignmentOperation assignmentOperation, T instance, Func`3 equalityComparer)
>    at Microsoft.CodeQuality.Analyzers.QualityGuidelines.AssigningSymbolAndItsMemberInSameStatement.AnalyzeAssignment(OperationAnalysisContext context)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__54_0(ValueTuple`2 data)
>    at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #2889

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs [hunk 1]
```diff
@@ -80,8 +80,8 @@ private void AnalyzeAssignment(OperationAnalysisContext context)
             {
                 assignmentOperation = (ISimpleAssignmentOperation)assignmentOperation.Value;
 
-                var operationValue = assignmentOperation.Target as T;
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs]: Time to start dogfooding C# 8 nullable references in the repo :-)

Any takers @dotnet/roslyn-analysis? Otherwise, I will try to get to it next sprint.

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs]: We had a similar NRE just a few weeks ago: https://github.com/dotnet/roslyn-analyzers/pull/2762/files

Comment (genlu) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs]: Is it just a matter of bumping roslyn version? Or are you actually proposing a full scale NRT roll out in this repo? :)

---
In reply to: [330693127](https://github.com/dotnet/roslyn-analyzers/pull/2894#discussion_r330693127) [](ancestors = 330693127)

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs]: We can do staged work if that is easier :) Planning to bump master branch to MS.CA 3.0 soon.

Comment (genlu) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs]: I suspect we might need to annotate the analyzer/codefix API's first in Roslyn, to have a cleaner annotation here.
