### PR TITLE
Fix CA1822 (MarkMembersAsStatic) for property/event symbols

### LINKED ISSUE #1933: CA1822 fires on a property whose setter accesses instance data
#### Analyzer package

[Microsoft.CodeQuality.Analyzers](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers)

#### Package Version

v2.6.2

#### Diagnostic ID

[CA1822](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822-mark-members-as-static?view=vs-2017)

#### Repro steps

```
    public class MyClass
    {
        private static bool StaticThing;
        private bool InstanceThing;

        public bool Thing
        {
            get { return StaticThing; }
            set
            {
                StaticThing = value;
                InstanceThing = value;
            }
        }
    }
```

#### Expected behavior

`Thing` is not flagged as the setter accesses instance data

#### Actual behavior

`Thing` is flagged as can be marked static

### PR DESCRIPTION
**Pull request by mavasani**
Don't fire CA1822 on property/event symbols unless all its accessors are candidates for being marked static.

Fixes #1933

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs [hunk 1]
```diff
@@ -161,7 +170,8 @@ private static bool ShouldAnalyze(IMethodSymbol methodSymbol, Compilation compil
             // If this looks like an event handler don't flag such cases.
             if (methodSymbol.Parameters.Length == 2 &&
                 methodSymbol.Parameters[0].Type.SpecialType == SpecialType.System_Object &&
-                IsEventArgs(methodSymbol.Parameters[1].Type, compilation))
+                IsEventArgs(methodSymbol.Parameters[1].Type, compilation) &&
+                !methodSymbol.IsAccessorMethod())
```
Comment (sharwell) [inline src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: ❓ Which test covers this? It wasn't clear to me from reading why we'd need this.

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: Let me add a comment
