### PR TITLE
Handle conversion operation as operands of IThrowOperation

### LINKED ISSUE #6284: Not effective - CA2200: Rethrow to preserve stack details
### Analyzer

**Diagnostic ID**: [CA2200](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2200): `Rethrow to preserve stack details `

**Version**: [SDK 7.0.100]

### Describe the bug

`dotnet build` or the build action in Visual Studio for Mac didn't show the warning of CA2200.

### Steps To Reproduce

1. With .NET 7 SDK installed, create a new console app using `dotnet new console -o TestConsoleApp`
2. Replace all content with the following code in Program.cs.

```
class TestsRethrow
{
    static void Main()
    {
        TestsRethrow testRethrow = new TestsRethrow();
        testRethrow.CatchException();
    }

    void CatchException()
    {
        try
        {
            CatchAndRethrowExplicitly();
        }
        catch (ArithmeticException e)
        {
            Console.WriteLine("Explicitly specified:{0}{1}",
               Environment.NewLine, e.StackTrace);
        }

        try
        {
            CatchAndRethrowImplicitly();
        }
        catch (ArithmeticException e)
        {
            Console.WriteLine("{0}Implicitly specified:{0}{1}",
               Environment.NewLine, e.StackTrace);
        }
    }

    void CatchAndRethrowExplicitly()
    {
        try
        {
            ThrowException();
        }
        catch (ArithmeticException e)
        {
            // Violates the rule.
            throw e;
        }
    }

    void CatchAndRethrowImplicitly()
    {
        try
        {
            ThrowException();
        }
        catch (ArithmeticException)
        {
            // Satisfies the rule.
            throw;
        }
    }

    void ThrowException()
    {
        throw new ArithmeticException("illegal expression");
    }
}
```

Content of the .csproj file
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

```

### Expected behavior
Warning should be reported that CA2200 was found.

### Actual behavior
No warnings reported.

```
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored /Users/james/Projects/Temp/TestConsoleApp/TestConsoleApp.csproj (in 39 ms).
  TestConsoleApp -> /Users/james/Projects/Temp/TestConsoleApp/bin/Debug/net7.0/TestConsoleApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.64
```

## Additional context

.NET SDK: 7.0.100
OS: MacOS Ventura

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6284

Starting C# 8.0, C# compiler wraps the thrown operation within an implicit conversion to `System.Exception` type.

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313

**Comment by mavasani** [comment]
@sharwell The github action seems to always label my PRs as `Community` :-)

**Comment by Youssef1313** [comment]
> @sharwell The github action seems to always label my PRs as `Community` :-)

And it doesn't label mine as Community https://github.com/dotnet/roslyn-analyzers/pull/6295

File: src/Utilities/Compiler/Extensions/IOperationExtensions.cs [hunk 1]
```diff
@@ -741,7 +741,7 @@ public static IOperation WalkDownConversion(this IOperation operation, Func<ICon
             return operation;
         }
 
-        public static ITypeSymbol? GetThrownExceptionType(this IThrowOperation operation)
+        public static IOperation? GetThrownException(this IThrowOperation operation)
```
Comment (Youssef1313) [inline src/Utilities/Compiler/Extensions/IOperationExtensions.cs:744]: I see the code here is existing prior to the PR but wanted to make sure it is correct.

Should this method handle an explicit conversion? e.g, what happens for `throw (Exception)new ArgumentNullException())`

Could it just be `WalkDownConversion()` (which `UseExceptionThrowHelpers` was already using).

Comment (mavasani) [reply src/Utilities/Compiler/Extensions/IOperationExtensions.cs:744]: Good point, let me update the code.

**Review by Youssef1313 — APPROVED** [review]
LGTM
