### PR TITLE
Respect CodeAnalysisTreatWarningsAsErrors for IDE design-time builds

### LINKED ISSUE #4173: CodeAnalysisTreatWarningsAsErrors does not work in Visual Studio
**Version Used**: 
- **VS:** 16.8.0 Preview 4.0 [30518.80.main]
- **.NET SDK:** 5.0.100-rc.2.20468.8

**Steps to Reproduce**:

Create a project with .NET 5 RC2 with the following project file and code file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
```

```csharp
using System;

class C
{
    static void Main(string[] str)
    {
        int length = 3;
        for (int i = 0; i < length; i++)
        {
            Span<int> numbers = stackalloc int[length]; // CA2014
            numbers[i] = i;
        }
    }
}

```

**Expected Behavior**:

CA2014 is treated as a warning everywhere.

**Actual Behavior**:

It is treated as an error _only_ in visual studio
image

the commandline treats it as a warning:
```cmd
dotnet build
Microsoft (R) Build Engine version 16.8.0-preview-20464-02+0220c5eae for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
C:\source\jmarolf\scratch\analyzer-test\Program.cs(10,33): warning CA2014: Potential stack overflow. Move the stackalloc out of the loop. [C:\source\jmarolf\scratch\analyzer-test\analyzer-test.csproj]
  analyzer-test -> C:\source\jmarolf\scratch\analyzer-test\bin\Debug\net5.0\analyzer-test.dll

Build succeeded.

C:\source\jmarolf\scratch\analyzer-test\Program.cs(10,33): warning CA2014: Potential stack overflow. Move the stackalloc out of the loop. [C:\source\jmarolf\scratch\analyzer-test\analyzer-test.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.98
```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #4173

### CODE REVIEW

File: src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs [hunk 1]
```diff
@@ -477,6 +477,22 @@ static void AddMSBuildContentForItemOptions(StringBuilder builder)
                 }
             }
 
+            static string GetCodeAnalysisTreatWarningsAsErrorsTargetContents()
+            {
+                return $@"
+  <!--
+    Design-time target to prevent the rule ids implemented in this package to be bumped to errors in the IDE
```
Comment (mavasani) [inline src/Tools/GenerateGlobalAnalyzerConfigs/Program.cs:484]: It seems design time builds in IDE need this setting to be inside a target to get applied.

**Review by jmarolf — APPROVED** [review]
