### PR TITLE
Use api_surface = all for CA1021 tests

### LINKED ISSUE #5853: CA1021 Try* exception not applied to explicit interface implementation
### Analyzer

**Diagnostic ID**: [CA1021](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1021): `Avoid out parameters`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers 6.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers/6.0.0)

### Describe the bug

Rule supports [exception for Try pattern methods](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1021#try-pattern-methods), but it is not applied to methods, which a part of explicit interface implementation.

### Steps To Reproduce

```cs
public interface ITry
{
    bool TrySomething(out string? something);
}
public class Try : ITry
{
    bool ITry.TrySomething(out string? something)
    {
        something = null;
        return false;
    }

    public bool TryAnything(out string? something)
    {
        something = null;
        return false;
    }
}
```
### Expected behavior

No `CA1021` reports for both methods

### Actual behavior

`CA1021` reported for `bool ITry.TrySomething(out string? something)`

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #5853

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParameters.cs [hunk 1]
```diff
@@ -58,7 +58,7 @@ public void Analyze(SymbolAnalysisContext analysisContext)
                 var methodSymbol = (IMethodSymbol)analysisContext.Symbol;
                 if (methodSymbol.IsOverride ||
                     !analysisContext.Options.MatchesConfiguredVisibility(Rule, methodSymbol, analysisContext.Compilation) ||
-                    methodSymbol.IsImplementationOfAnyImplicitInterfaceMember())
+                    methodSymbol.IsImplementationOfAnyInterfaceMember())
```
Comment (Youssef1313) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParameters.cs:61]: NOTE: This change doesn't change any behavior. The test passes with and without it due to https://github.com/dotnet/roslyn-analyzers/issues/5878. I'm changing it just to match the intent.

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParametersTests.cs [hunk 2]
```diff
@@ -476,12 +476,25 @@ public class InterfaceBothImplicitAndExplicitImpl : IInterface
...
+") },
+                }
+            }.RunAsync();
+
+            var vbSource = @"
 Imports System.Runtime.InteropServices
 
 Interface IInterface
-    Sub InterfaceMethod(<Out> ByRef s As String)
+    Sub [|InterfaceMethod|](<Out> ByRef s As String)
```
Comment (mavasani) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParametersTests.cs:497]: So, the difference between this test and the C# test prior to this PR was that the interface was marked public for the C# test and is internal for VB test. I think we should keep both C# and VB tests in this test consistent - either both should declare the interface as internal and have the editorconfig setting `all` for `api_surface` OR both should declare the interface as public and not require any editorconfig setting.

Comment (Youssef1313) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/AvoidOutParametersTests.cs:497]: @mavasani editorconfig setting is needed either way to make sure we're testing the explicit interface implementation which is private. I'll update the VB test to match C# for consistency.

**Review by mavasani — APPROVED** [review]
