### PR TITLE
CA2119: Fix false negative with extended interface

### LINKED ISSUE #4406: CA2119 not triggered when extended interface is implemented
### Analyzer

**Diagnostic ID**: [CA2119](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2119): `Seal methods that satisfy private interfaces`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Describe the bug

When there are two internal interfaces, one extending another, methods from the "super" interface aren't spotted by CA2119 when a class implements the "extended" interface

### Steps To Reproduce

Source code:

```csharp
namespace FxCopRule
{
    internal interface IInternal1
    {
        void Method();
    }

    internal interface IInternal2 : IInternal1
    {
    }

    public abstract class ImplementationBase : IInternal2
    {
        public abstract void Method();
    }
}
```

### Expected behavior

CA2119 should be raised, as `ImplementationBase` still implements `IInternal1.Method` with an abstract method.

### Actual behavior

CA2119 is not raised.

## Additional context

Changing the class declaration to explicitly implement the "super" interface does cause the warning to be raised:

```csharp
public abstract class ImplementationBase : IInternal1, IInternal2
```

### PR DESCRIPTION
**Pull request by Evangelink**
Fix #4406

### CODE REVIEW

File: src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs [hunk 1]
```diff
@@ -52,7 +52,7 @@ private static void CheckTypes(SymbolAnalysisContext context)
                 (!type.Constructors.Any() || type.Constructors.Any(c => c.GetResultantVisibility().IsAtLeastAsVisibleAs(SymbolVisibility.Public))))
             {
                 // look for implementations of interfaces members declared on this type
-                foreach (var iface in type.Interfaces)
+                foreach (var iface in type.AllInterfaces)
```
Comment (Evangelink) [inline src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfaces.cs:55]: We were only looking at the direct interface.

**Review by Youssef1313 — APPROVED** [review]

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfacesTests.cs [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 using System.Threading.Tasks;
 using Microsoft.CodeAnalysis.Testing;
+using Test.Utilities;
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfacesTests.cs:5]: Is anything used from this namespace?

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfacesTests.cs [hunk 3]
```diff
@@ -423,6 +424,45 @@ End Class
 ");
         }
 
+        [Fact, WorkItem(4406, "https://github.com/dotnet/roslyn-analyzers/issues/4406")]
+        public async Task CA2119_ExtendedInterface()
+        {
+            await VerifyCS.VerifyAnalyzerAsync(@"
+namespace FxCopRule
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/SealMethodsThatSatisfyPrivateInterfacesTests.cs:431]: nit: No need for the namespace declaration.

**Review by mavasani — APPROVED** [review]
