### PR TITLE
Don't report unnamed parameters

### LINKED ISSUE #4039: ReviewUnusedParametersFixer error when no parameter name present
**Version Used**: 
VS2019 16.8 P1

**Steps to Reproduce**:

```csharp
    public class TestClass
    {
        public TestClass(ParClass ↓)
        {
        }
    }
```

Click on the light-bulb with cursor on ↓ position.

**Expected Behavior**:
No errors present. 
Probably CA1801 should not be reported at all.

**Actual Behavior**:
'ReviewUnusedParametersFixer' encountered an error and has been disabled.
Stacktrace:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at async Microsoft.CodeQuality.Analyzers.Maintainability.ReviewUnusedParametersFixer.GetNodesToRemoveAsync(<Unknown Parameters>)
   at async Microsoft.CodeQuality.Analyzers.Maintainability.ReviewUnusedParametersFixer.RemoveNodes(<Unknown Parameters>)
   at async Microsoft.CodeQuality.Analyzers.Maintainability.ReviewUnusedParametersFixer.<>c__DisplayClass3_1.<RegisterCodeFixesAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)```

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #4039

### CODE REVIEW

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs [hunk 1]
```diff
@@ -20,6 +20,19 @@ namespace Microsoft.CodeQuality.Analyzers.Maintainability.UnitTests
...
+        {
+            await VerifyCS.VerifyAnalyzerAsync(@"
+public class NeatCode
+{
+    public void DoSomething(string)
+    {
+    }
+}
+", DiagnosticResult.CompilerError("CS1001").WithLocation(4, 35));
+        }
```
Comment (Youssef1313) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/ReviewUnusedParametersTests.cs:35]: This only has a C# test. I think there is no parallel VB test. I can't find any way to get an empty parameter name in VB syntax tree. For example:

```
Public Sub M(As String)
```

This generates "As" as the name, and "String" as skipped trivia.
