### PR TITLE
Fix CA1721 - Do not report on overriden members

### LINKED ISSUE #2914: CA1721 should not raise on overrides
#### Analyzer package

[Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

#### Package Version

v2.9.6 (Latest)

#### Diagnostic ID

Example: [CA1721](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1721-property-names-should-not-match-get-methods)

#### Repro steps

```csharp
public class MyBase
{
    public object Content { get; }
    public virtual object GetContent() => null;
}

public class Foo
{
	// Issue is raised here but as I cannot change anything in here
    // there should be no issue raised.
    public override object GetContent() => this;
}
```

#### Expected behavior

No CA1721 is raised on `Foo.GetContent()` as there is no way to solve the issue except editing the base class which might not be under our control (cf `RadOpenFolderDialog` from Telerik).

#### Actual behavior

The issue is raised on `Foo.GetContent()`

I will try and have a PR fixing this issue if you are fine with it.

### PR DESCRIPTION
**Pull request by Evangelink**
When a base class with virtual members is not complying with the rule (i.e. has a property and a get method with the same name) and your derived class override one or two of the member you will get the issue raised upon your override. Sadly there is nothing much you can do if you don't own the base class so the analyzer should not raise an issue here.

I have tried to add test for C# and VB.NET for all the cases I could think of.

Fix #2914

### CODE REVIEW

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs [hunk 1]
```diff
@@ -94,6 +94,12 @@ private static void AnalyzeSymbol(SymbolAnalysisContext context)
                         continue;
                     }
 
+                    // Ignore declared type that overrides a base member
+                    if (symbol.IsOverride)
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: I am not sure if we want to ignore all overrides. For example, if base type defines a virtual/abstract method and derive type defines an override for it and also defines a new property with a name that violates it, we still want to flag the derive type's property. I think we only want to not flag when both the property and method symbol are override.

Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: Looks like the comment is not good enough. Basically if you look at the test you'll see that if you override the property or the method or both no issue is raised. On the other hand if you override one of the 2 and add the complementary member you will have an issue raised.

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs [hunk 2]
```diff
@@ -376,6 +376,151 @@ End Function
...
+        GetCA1721BasicResultAt(line: 3, column: 42, identifierName: "Value", otherIdentifierName: "GetValue"));
+        }
+
+        [Fact, WorkItem(2914, "https://github.com/dotnet/roslyn-analyzers/issues/2914")]
+        public void CA1721_OverrideWithLocalMemberDiagnostic()
+        {
+            VerifyCSharp(@"
+public class BaseClass1
+{
+    public virtual int Value { get; }
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]: Can you add a test where the virtual in base type is a method instead of a property?

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs (hunk 1 above)
Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: I understand why this works, just that it wasn’t clear from a quick glance. Is there a reason to have your newly added check inside the loop instead of bailing out right at the start of the method?

File: src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs (hunk 2 above)
Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethodsTests.cs]: See tests from line 466+. `BaseClass2` has a virtual method and `C2` adds the property.

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs (hunk 1 above)
Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: > It’s not the comment but the implementation that doesn’t seem tight enough. I would have expected the newly added if statement condition to check if both symbol.IsOverride and member.IsOverride is true, not just one.

Well if I have both `symbol.IsOverride` and `member.IsOverride` then I will keep reporting on cases where the base class defines both the property and the method and I override only one of them.
I will make some more tests to see if I can somehow find some more restrictive condition to add.

> I understand why your current implementation works, just that it wasn’t clear from a quick glance. Is there a reason to have your newly added check inside the loop instead of bailing out right at the start of the method?

Nope no good reason. I will fix it.

Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: Alright so according to this "truth table":

```
local P + nothing => no issue
local P + local M => issue
local P + base M => issue
local P + override M => issue
==> issue when local P + whatever M

override P + nothing => no issue
override P + local M => issue
override P + base M => no issue
override P + override M => no issue
==> issue when override P + local M

local M + nothing => no issue
local M + local P => issue
local M + base P => issue
local M + override P => issue
==> issue when local M + whatever P

override M + nothing => no issue
override M + local P => issue
override M + base P => no issue
override M + override P => no issue
==> issue when override M + local M
```

and based on the fact that the analyzer will kick-in for both the method and the property (when they are present), we could either keep the if located here update it to `symbol.IsOverride && member.ContainingType.Equals(type)` or we can move it to the beginning of the `AnalyzerSymbol` method. Indeed, when the member is an override, the only case where we want to report is when the other member is declared locally AND so the second check will take care of it.

Let me know what's your preference.

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: Thanks for the detailed explanation. I am fine with either approach, with a weaker preference towards just bailing out up front for symbols that are overrides.

Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: I will update to add the second part to the if then :D
Not trying to convince you of going for the other solution but do you think the overhead of the various visibility, loop and member checks are neglectable?

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: Yes, I think performance is not really a concern here. Best to come up with a clean, maintainable solution. I am fine with either of your proposed routes. Thanks!

File: src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs [hunk 3]
```diff
@@ -81,6 +81,14 @@ private static void AnalyzeSymbol(SymbolAnalysisContext context)
                 var exposedMembers = type.GetMembers(identifier).Where(member => configuredVisibilities.Contains(member.GetResultantVisibility()));
                 foreach (var member in exposedMembers)
                 {
+                    // We only want to report an issue when the user is free to update the member.
+                    // So we can bail out when the property or method (symbol) is override and the other member (member)
+                    // is not local (i.e. symbol and member are declared
+                    if (symbol.IsOverride && member.ContainingType.Equals(type))
```
Comment (mavasani) [inline src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: The comment says "is not local" but the check seems to validate it is local?

Comment (Evangelink) [reply src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/PropertyNamesShouldNotMatchGetMethods.cs]: You are absolutely right! Sadly I cannot simply negate the equal condition as we are looping through the different base types... And for the same reason this check is not enough `symbol.IsOverride && (!member.ContainingType.Equals(symbol.ContainingType) || member.IsOverride)` as we end up reporting multiple times for the same member when the member is overriden and a local member is declared. The only "workaround" I can think of is to access the original declaration to do the comparison but that's adding quite a lot of complexity IMO.

I am reverting to the simple `symbol.IsOverride` check and moving it to the top of the class with an updated comment.
