### PR TITLE
Handle target-typed new in CA1001

### LINKED ISSUE #5834: CA1001 is not shown for target-typed new expressions
### Analyzer

**Diagnostic ID**: [CA1001](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001): `Types that own disposable fields should be disposable`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.101](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug
The diagnostic CA1001 is not recognized for fields that are created with a target-typed new expression.

### Steps To Reproduce

1. Create a new .NET 6 class library project.
2. Add this to the csproj file: `<AnalysisMode>All</AnalysisMode>`
3. Add this class:
```cs
    public sealed class AsyncLock
    {
        private readonly SemaphoreSlim _semaphore = new SemaphoreSlim(1, 1);
    }
```
4. Notice that CA1001 is shown -> good
5. Use the quick fix for IDE0090 to simplify the new expression to a target-typed new expression (`private readonly SemaphoreSlim _semaphore = new(1, 1);`).
6. Notice that CA1001 is not shown any more -> bug

### Expected behavior
CA1001 should be shown for target-typed new expressions.

### Actual behavior
CA1001 is not shown for target-typed new expressions.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #5834

I also consolidated unit tests, eliminated usage of banned `WithLocation` overload, and verified codefix for all tests.

This is better reviewed commit-by-commit.

### CODE REVIEW

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs [hunk 1]
```diff
@@ -802,19 +794,5 @@ End Sub
 End Class
 ");
         }
-
-        private static DiagnosticResult GetCA1001CSharpResultAt(int line, int column, string objectName, string disposableFields)
```
[the remark this answers is not in the document]
Comment (sharwell) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:587]: ➡️ Looks like some tests already did this, so this elimination of the helper is fine as-is.

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs [hunk 2]
```diff
@@ -29,7 +29,8 @@ public CSharpDisposableFieldAnalyzer(Compilation compilation)
             {
                 if (node is AssignmentExpressionSyntax assignment)
                 {
-                    if (assignment.Right is ObjectCreationExpressionSyntax &&
+                    // ImplicitObjectCreationExpression	8659
+                    if (assignment.Right.RawKind is (int)SyntaxKind.ObjectCreationExpression or 8659 &&
```
Comment (sharwell) [inline src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs:33]:
```suggestion
                    if (assignment.Right.IsKind(SyntaxKind.ObjectCreationExpression, SyntaxKindEx.ImplicitObjectCreationExpression) &&
```

**Review by sharwell — CHANGES_REQUESTED** [review]

**Comment by sharwell** [comment]
📝 Needs to use `SyntaxKindEx.ImplicitObjectCreationExpression` instead of a literal. Easiest way is the two-argument `IsKind` helper, but other approaches to achieve the same goal are acceptable.

**Comment by Youssef1313** [comment]
@sharwell I recall I wanted to use the two-argument `IsKind` but didn't find it here. It exists in dotnet/roslyn only.

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs [hunk 3]
```diff
@@ -40,7 +41,8 @@ public CSharpDisposableFieldAnalyzer(Compilation compilation)
                 {
                     foreach (VariableDeclaratorSyntax fieldInit in fieldDeclarationSyntax.Declaration.Variables)
                     {
-                        if (fieldInit.Initializer?.Value is ObjectCreationExpressionSyntax &&
+                        // ImplicitObjectCreationExpression	8659
+                        if (fieldInit.Initializer?.Value.RawKind is (int)SyntaxKind.ObjectCreationExpression or 8659 &&
```
[the remark this answers is not in the document]
Comment (Youssef1313) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs:45]: Currently there is no `SyntaxKindEx` and there is a fixer that defines the `SyntaxKind` it wants privately:

https://github.com/dotnet/roslyn-analyzers/blob/97d7b2d0554dda1cccf60f74bcb01ee810cdfc16/src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/InteropServices/CSharpDynamicInterfaceCastableImplementation.Fixer.cs#L25-L26

I'll add `SyntaxKindEx` in `Lightup` and adjust the mentioned fixer and the analyzer modified in this PR.

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs (hunk 2 above)
Comment (Youssef1313) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs:33]: Adding `SyntaxKindEx` won't be straightforward. It requires MS.CA.CSharp which is not available for use in Lightup as the shared project is referenced by `MS.CA.NetAnalyzers`, not language-specific layers. Trying to move the reference down to CSharp didn't seem trivial.

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs (hunk 3 above)
[the remark this answers is not in the document]
Comment (Youssef1313) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs:45]: This wasn't trivial to do. ➡️ https://github.com/dotnet/roslyn-analyzers/pull/5880#discussion_r819393710

**Review by Youssef1313 — COMMENTED** [review]
Best I could do is b3aa798. @sharwell Can you take another look?

File: src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs (hunk 2 above)
Comment (sharwell) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs]: I don't understand. This file is a C#-specific file?

Comment (Youssef1313) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs]: @sharwell Yup this file is C#-specific. But where do I add `SyntaxKindEx`? Can't add it to `Lightup` because it's not C#-specific.

Comment (sharwell) [reply src/NetAnalyzers/CSharp/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/CSharpTypesThatOwnDisposableFieldsShouldBeDisposable.cs]: You can create a new C#-specific lightup folder for this project, or create a new shared project Analyzer.CSharp.Utilities (similar to how we have Refactoring.CSharp.Utilities)

**Comment by Youssef1313** [comment]
@sharwell Can you take another look?

File: src/Utilities/Compiler.CSharp/Extensions/SyntaxNodeExtensions.cs [hunk 4]
```diff
@@ -2,16 +2,16 @@
...
 namespace Analyzer.Utilities.Extensions
 {
     internal static partial class SyntaxNodeExtensions
     {
         public static SyntaxNode WalkDownParentheses(this SyntaxNode node)
         {
-            const int parenthesizedExpressionRawKind = 8632;
             SyntaxNode current = node;
-            while (current.RawKind == parenthesizedExpressionRawKind && current.ChildNodes().FirstOrDefault() is SyntaxNode expression)
+            while (current.IsKind(SyntaxKind.ParenthesizedExpression) && current.ChildNodes().FirstOrDefault() is SyntaxNode expression)
```
Comment (Youssef1313) [inline src/Utilities/Compiler.CSharp/Extensions/SyntaxNodeExtensions.cs:14]: This was in language-agnostic layer, but the code is specific for C# and won't walk down parentheses for VB. I moved it to the new C#-specific project to avoid accidental use of this extension method in VB-specific code.

**Comment by Youssef1313** [comment]
@sharwell Can you take a look? Thanks!

**Comment by Youssef1313** [comment]
@sharwell Can you take a look please?

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs [hunk 5]
```diff
@@ -44,25 +43,67 @@ public class NoDisposeClass
...
 
-    public class NoDisposeClass
+    public class [|NoDisposeClass|]
     {
         FileStream newFile1, newFile2 = new FileStream(""data.txt"", FileMode.Append);
     }
+", @"
+using System.IO;
+
+    public class NoDisposeClass : System.IDisposable
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:56]:
```suggestion
public class NoDisposeClass : System.IDisposable
```

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs [hunk 6]
```diff
@@ -44,25 +43,67 @@ public class NoDisposeClass
...
         {
-            await VerifyCS.VerifyAnalyzerAsync(@"
+            await VerifyCS.VerifyCodeFixAsync(@"
 using System.IO;
 
-    public class NoDisposeClass
+    public class [|NoDisposeClass|]
     {
         FileStream newFile1, newFile2 = new FileStream(""data.txt"", FileMode.Append);
     }
```
Comment (Evangelink) [inline src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:52]:
```suggestion
public class [|NoDisposeClass|]
{
    FileStream newFile1, newFile2 = new FileStream(""data.txt"", FileMode.Append);
}
```

Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:52]: Up to you, if you want to fix these indents or not (a few more tests have the same issue).

File: src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs (hunk 5 above)
Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:56]: Up to you, if you want to fix these indents or not (a few more tests have the same issue).

Comment (Evangelink) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:56]: Yeah I saw they were copied hence my "optional" suggestion :)

Comment (Youssef1313) [reply src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/TypesThatOwnDisposableFieldsShouldBeDisposableTests.cs:56]: I wanted to do that, but the reason didn't is I usually see pushback against those kind of changes (at least in dotnet/roslyn).

I'd be definitely happy to fix formatting if @sharwell/@mavasani agrees :)
