### PR TITLE
Fix CA1822 (MarkMembersAsStatic) to handle instance references in obj…

### LINKED ISSUE #1865: "Mark methods static" does not fire in some cases
#### Repro steps

The following code does not fire "mark methods static" despite it not touching "Me."

``` VB

    Friend Class SettingsValueSerializer

        Public Function Deserialize(ValueType As Type, serializedValue As String, culture As Globalization.CultureInfo) As Object
            If ValueType Is GetType(String) Then
                ' VsWhidbey 270764:
                ' Strings require special handling, since the ConfigHelper API assumes that all serialized representations
                ' of types that it will use anything but XML serialization to (de)serialize are correctly escaped.
                '
                Return serializedValue
            End If

            Dim Prop As New SettingsProperty("") With {
                .ThrowOnErrorDeserializing = True,
                .PropertyType = ValueType
            } ' We don't care about the name for the setting.... 
            Dim propVal As New SettingsPropertyValue(Prop)
            If ValueType IsNot Nothing Then
                Try
                    Dim configurationHelperService As New ConfigurationHelperService()
                    Prop.SerializeAs = configurationHelperService.GetSerializeAs(Prop.PropertyType)
                    Dim val As Object = Nothing
                    If Prop.SerializeAs = SettingsSerializeAs.String Then
                        ' We have to take care of this, cause we want to use the CultureInfo passed in to us when doing the deserialization
                        ' 
                        ' The runtime will always use InvariantCulture, but we sometimes have to show the default value in the UI, which 
                        ' means that we should use the current thread's culture...
                        Dim tc As TypeConverter = TypeDescriptor.GetConverter(ValueType)
#If DEBUG Then
                        Debug.Assert(tc.CanConvertFrom(GetType(String)), String.Format("Why were we told that serialization method was string for type {0} when type converter {1} can't convert from a string?", ValueType, tc))
                        Debug.Assert(tc.CanConvertTo(GetType(String)), String.Format("Why were we told that serialization method was string for type {0} when type converter {1} can't convert to a string?", ValueType, tc))
#End If
                        val = tc.ConvertFromString(Nothing, culture, serializedValue)
                    Else
                        propVal.SerializedValue = serializedValue
                        val = propVal.PropertyValue
                    End If

                    ' If the type converter was broken and returned an unknown type, we better stop it right here...
                    If val IsNot Nothing AndAlso Not ValueType.IsAssignableFrom(val.GetType()) Then
                        Return Nothing
                    End If

                    ' For some reason, enumerations' deserialization works even when the integer value is out of range...
                    ' Well, we know better - let's check for this funky case and return nothing :)
                    If val IsNot Nothing AndAlso GetType([Enum]).IsAssignableFrom(ValueType) AndAlso Not [Enum].IsDefined(ValueType, val) Then
                        ' If this is a flags attribute, we can't assume that the enum is defined
                        If ValueType.GetCustomAttributes(GetType(FlagsAttribute), False).Length = 0 Then
                            Return Nothing
                        End If
                    End If
                    Return val
                Catch Ex As Exception
                    ' Failed to convert - return NOTHING
                End Try
            End If

            ' Yet again we have some special handling for connection strings...
            If ValueType Is GetType(VSDesigner.VSDesignerPackage.SerializableConnectionString) AndAlso serializedValue <> "" Then
                Dim scs As New VSDesigner.VSDesignerPackage.SerializableConnectionString With {
                    .ConnectionString = serializedValue,
                    .ProviderName = ""
                }
                Return scs
            End If

            Return Nothing
        End Function
```

### PR DESCRIPTION
**Pull request by mavasani**
…ect initializers

Fixes #1865

### CODE REVIEW

**Comment by mavasani** [comment]
retest this please

File: src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs [hunk 1]
```diff
@@ -74,7 +74,10 @@ public override void Initialize(AnalysisContext analysisContext)
 
                     blockStartContext.RegisterOperationAction(operationContext =>
                     {
-                        isInstanceReferenced = true;
+                        if (((IInstanceReferenceOperation)operationContext.Operation).ReferenceKind == InstanceReferenceKind.ContainingTypeInstance)
```
Comment (heejaechang) [inline src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: don't need to check whether instance is pointing to the type the method belong to?

Comment (mavasani) [reply src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MarkMembersAsStatic.cs]: `ContainingTypeInstance` is used for `this` or `base`, both of which are candidates for us to consider method as requiring instance access.
