### PR TITLE
Fix GetHashCode and add System.HashCode.Compare

### LINKED ISSUE #4956: Incorrect RS1024 analysis when calling GetHashCode(ReadOnlySpan<char>, StringComparison)
### Analyzer

RS1024

### Analyzer source

**Version**: 3.10.0-2.21166.52

### Steps To Reproduce

1. Reference the 3.10.0-2.21166.52 of Roslyn binaries in a console app
2. Code:
```C#
ReadOnlySpan<char> foo = default;
int hashCode = string.GetHashCode(foo, StringComparison.OrdinalIgnoreCase);
```

### Actual behavior

```
error RS1024: Compare symbols correctly
```

### PR DESCRIPTION
**Pull request by ryzngard**
RS1024 is falsely reporting on any static method called "GetHashCode" and not checking arguments. 

RS1024 is not reporting on "System.HashCode.Combine" if it is used. 

Fixes #4956

### CODE REVIEW

**Comment by ryzngard** [comment]
cc @Youssef1313

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 1]
```diff
@@ -140,23 +142,29 @@ private static void HandleBinaryOperator(in OperationAnalysisContext context, IN
...
             var invocationOperation = (IInvocationOperation)context.Operation;
             var method = invocationOperation.TargetMethod;
 
             switch (method.Name)
             {
                 case WellKnownMemberNames.ObjectGetHashCode:
-                    if (IsNotInstanceInvocationOrNotOnSymbol(invocationOperation, symbolType))
+                    // This is a call for an instance of ISymbol.GetHashCode()
+                    // without the correct arguments
+                    if (IsSymbolType(invocationOperation.Instance, symbolType))
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:160]: IsSymbolType will crash if `invocationOperation.Instance` is null. This can happen if the static `object.GetHashCode` is called. Can you confirm and add a test?

File: src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs [hunk 2]
```diff
@@ -166,10 +174,21 @@ private static void HandleBinaryOperator(in OperationAnalysisContext context, IN
                     }
                     break;
 
+                case s_HashCodeCombineName:
+                    // A call System.HashCode.Combine(ISymbol) will do the wrong thing and should be avoided
+                    if (systemHashCodeType is not null &&
+                        invocationOperation.Instance is null &&
+                        systemHashCodeType.Equals(method.ContainingType) &&
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/Core/MetaAnalyzers/CompareSymbolsCorrectlyAnalyzer.cs:181]: Pass SymbolEqualityComparer?

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs [hunk 3]
```diff
@@ -1141,5 +1141,98 @@ public void M2(IEnumerable<IPropertySymbol> source, IEnumerable<IPropertySymbol>
...
+    public int GetHashCode(ISymbol symbol)
+    {
+        return HashCodeHelper.GetHashCode(symbol);
+    }
+
+    public int GetHashCode(object o)
+    {
+        if (o is ISymbol symbol)
+        {
+            return [|HashCode.Combine(symbol)|];
```
Comment (Youssef1313) [inline src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1206]: This test doesn't check the codefix behavior. If no codefix is offered, can you use the same source for FixedCode as well?

**Review by Youssef1313 — COMMENTED** [review]
Thanks for taking this :tada:

File: src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs (hunk 3 above)
Comment (ryzngard) [reply src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/CompareSymbolsCorrectlyTests.cs:1206]: Sure

**Review by mavasani — APPROVED** [review]
